/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '../auth.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from './signup.component';
import * as import3 from '@angular/router';
import * as import4 from '@angular/common';
import * as import5 from '@angular/forms';
import * as import6 from '../../models/auth.model.service';
import * as import7 from '../../../shared/services/meta/meta.service';
const styles_SignupComponent:any[] = [import0.styles];
export const RenderType_SignupComponent:import1.RendererTypeV2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_SignupComponent,
  data: {}
}
);
function View_SignupComponent_1():import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    import1.ɵeld(0,(null as any),(null as any),4,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵeld(0,(null as any),(null as any),1,'h3',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),[
      '',
      ''
    ]
    ),
    import1.ɵted((null as any),['\n        '])
  ]
  ,(null as any),(check,view) => {
    var comp:any = view.component;
    const currVal_0:any = comp.error;
    check(view,3,0,currVal_0);
  });
}
export function View_SignupComponent_0():import1.ɵViewDefinition {
  return import1.ɵvid(0,[
      import1.ɵeld(0,(null as any),(null as any),97,'section',[[
        'class',
        'container-fluid auth-contain'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n  ']),
      import1.ɵeld(0,(null as any),(null as any),1,'h1',[[
        'class',
        'sr-only'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Sign Up']),
    import1.ɵted((null as any),['\n  ']),
      import1.ɵeld(0,(null as any),(null as any),91,'div',[[
        'class',
        'row'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n    ']),
      import1.ɵeld(0,(null as any),(null as any),79,'article',[[
        'class',
        'col-sm-12 col-md-6 col-lg-5'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n      ']),
      import1.ɵeld(0,(null as any),(null as any),76,'section',[[
        'class',
        'form-contain'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n        ']),
      import1.ɵeld(0,(null as any),(null as any),8,'div',[[
        'class',
        'logo-contain'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵeld(0,(null as any),(null as any),5,'a',[
      [
        'class',
        'logo'
      ]
      ,
      [
        'routerLink',
        '/discover'
      ]

    ]
    ,[
      [
        0,
        'target',
        0
      ]
      ,
      [
        3,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.SignupComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,14).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdid(335872,(null as any),0,import3.RouterLinkWithHref,[
      import3.Router,
      import3.ActivatedRoute,
      import4.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵted((null as any),['\n            ']),
      import1.ɵeld(0,(null as any),(null as any),1,'span',[[
        'class',
        'sr-only'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Stitch']),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵted((null as any),['\n        ']),
    import1.ɵted((null as any),['\n        ']),
    import1.ɵand(8388608,(null as any),(null as any),1,(null as any),View_SignupComponent_1),
    import1.ɵdid(8192,(null as any),0,import4.NgIf,[
      import1.ViewContainerRef,
      import1.TemplateRef
    ]
      ,{ngIf: [
        0,
        'ngIf'
      ]
    },(null as any)),
    import1.ɵted((null as any),['\n        ']),
      import1.ɵeld(0,(null as any),(null as any),56,'form',[[
        'novalidate',
        ''
      ]
    ],[
      [
        1,
        'ng-untouched'
      ]
      ,
      [
        1,
        'ng-touched'
      ]
      ,
      [
        1,
        'ng-pristine'
      ]
      ,
      [
        1,
        'ng-dirty'
      ]
      ,
      [
        1,
        'ng-valid'
      ]
      ,
      [
        1,
        'ng-invalid'
      ]
      ,
      [
        1,
        'ng-pending'
      ]

    ]
    ,[
      [
        (null as any),
        'ngSubmit'
      ]
      ,
      [
        (null as any),
        'submit'
      ]
      ,
      [
        (null as any),
        'reset'
      ]

    ]
    ,(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.SignupComponent = view.component;
      if (('submit' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,26).onSubmit($event)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      if (('reset' === eventName)) {
        const pd_1:any = ((<any>import1.ɵnov(view,26).onReset()) !== false);
        allowDefault = (pd_1 && allowDefault);
      }
      if (('ngSubmit' === eventName)) {
        const pd_2:any = ((<any>comp.signup()) !== false);
        allowDefault = (pd_2 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdid(8192,(null as any),0,import5.ɵbf,([] as any[]),(null as any),(null as any)),
    import1.ɵdid(270336,(null as any),0,import5.FormGroupDirective,[
      [
        8,
        (null as any)
      ]
      ,
      [
        8,
        (null as any)
      ]

    ]
      ,{form: [
        0,
        'form'
      ]
    },{ngSubmit: 'ngSubmit'}),
    import1.ɵprd(1024,(null as any),import5.ControlContainer,(null as any),[import5.FormGroupDirective]),
    import1.ɵdid(8192,(null as any),0,import5.NgControlStatusGroup,[import5.ControlContainer],(null as any),(null as any)),
    import1.ɵted((null as any),['\n          ']),
      import1.ɵeld(0,(null as any),(null as any),19,'div',[[
        'class',
        'form-group'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵeld(0,(null as any),(null as any),1,'label',[
      [
        'class',
        'sr-only'
      ]
      ,
      [
        'for',
        'email'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Email Address']),
    import1.ɵted((null as any),['\n            ']),
      import1.ɵeld(0,(null as any),(null as any),13,'div',[[
        'class',
        'input-group'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n              ']),
      import1.ɵeld(0,(null as any),(null as any),1,'div',[[
        'class',
        'input-group-addon'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
      import1.ɵeld(0,(null as any),(null as any),0,'i',[[
        'class',
        'icon-mail'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n              ']),
    import1.ɵeld(0,(null as any),(null as any),7,'input',[
      [
        'class',
        'form-control'
      ]
      ,
      [
        'formControlName',
        'email'
      ]
      ,
      [
        'name',
        'email'
      ]
      ,
      [
        'placeholder',
        'awesome@email.com'
      ]
      ,
      [
        'required',
        ''
      ]
      ,
      [
        'type',
        'email'
      ]

    ]
    ,[
      [
        0,
        'required',
        0
      ]
      ,
      [
        1,
        'ng-untouched'
      ]
      ,
      [
        1,
        'ng-touched'
      ]
      ,
      [
        1,
        'ng-pristine'
      ]
      ,
      [
        1,
        'ng-dirty'
      ]
      ,
      [
        1,
        'ng-valid'
      ]
      ,
      [
        1,
        'ng-invalid'
      ]
      ,
      [
        1,
        'ng-pending'
      ]

    ]
    ,[
      [
        (null as any),
        'input'
      ]
      ,
      [
        (null as any),
        'blur'
      ]

    ]
    ,(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.SignupComponent = view.component;
      if (('input' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,41).onChange($event.target.value)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      if (('blur' === eventName)) {
        const pd_1:any = ((<any>import1.ɵnov(view,41).onTouched()) !== false);
        allowDefault = (pd_1 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdid(8192,(null as any),0,import5.DefaultValueAccessor,[
      import1.Renderer,
      import1.ElementRef
    ]
    ,(null as any),(null as any)),
      import1.ɵdid(8192,(null as any),0,import5.RequiredValidator,([] as any[]),{required: [
        0,
        'required'
      ]
    },(null as any)),
    import1.ɵprd(512,(null as any),import5.NG_VALIDATORS,(p0_0:any) => {
      return [p0_0];
    },[import5.RequiredValidator]),
    import1.ɵprd(512,(null as any),import5.NG_VALUE_ACCESSOR,(p0_0:any) => {
      return [p0_0];
    },[import5.DefaultValueAccessor]),
    import1.ɵdid(335872,(null as any),0,import5.FormControlName,[
      [
        3,
        import5.ControlContainer
      ]
      ,
      [
        2,
        import5.NG_VALIDATORS
      ]
      ,
      [
        8,
        (null as any)
      ]
      ,
      [
        2,
        import5.NG_VALUE_ACCESSOR
      ]

    ]
      ,{name: [
        0,
        'name'
      ]
    },(null as any)),
    import1.ɵprd(1024,(null as any),import5.NgControl,(null as any),[import5.FormControlName]),
    import1.ɵdid(8192,(null as any),0,import5.NgControlStatus,[import5.NgControl],(null as any),(null as any)),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵted((null as any),['\n          ']),
      import1.ɵeld(0,(null as any),(null as any),19,'div',[[
        'class',
        'form-group'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵeld(0,(null as any),(null as any),1,'label',[
      [
        'class',
        'sr-only'
      ]
      ,
      [
        'for',
        'password'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Password']),
    import1.ɵted((null as any),['\n            ']),
      import1.ɵeld(0,(null as any),(null as any),13,'div',[[
        'class',
        'input-group'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n              ']),
      import1.ɵeld(0,(null as any),(null as any),1,'div',[[
        'class',
        'input-group-addon'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
      import1.ɵeld(0,(null as any),(null as any),0,'i',[[
        'class',
        'icon-lock'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n              ']),
    import1.ɵeld(0,(null as any),(null as any),7,'input',[
      [
        'class',
        'form-control'
      ]
      ,
      [
        'formControlName',
        'password'
      ]
      ,
      [
        'name',
        'password'
      ]
      ,
      [
        'placeholder',
        '$up3r$3cr3tp@$$w0rd'
      ]
      ,
      [
        'required',
        ''
      ]
      ,
      [
        'type',
        'password'
      ]

    ]
    ,[
      [
        0,
        'required',
        0
      ]
      ,
      [
        1,
        'ng-untouched'
      ]
      ,
      [
        1,
        'ng-touched'
      ]
      ,
      [
        1,
        'ng-pristine'
      ]
      ,
      [
        1,
        'ng-dirty'
      ]
      ,
      [
        1,
        'ng-valid'
      ]
      ,
      [
        1,
        'ng-invalid'
      ]
      ,
      [
        1,
        'ng-pending'
      ]

    ]
    ,[
      [
        (null as any),
        'input'
      ]
      ,
      [
        (null as any),
        'blur'
      ]

    ]
    ,(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.SignupComponent = view.component;
      if (('input' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,62).onChange($event.target.value)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      if (('blur' === eventName)) {
        const pd_1:any = ((<any>import1.ɵnov(view,62).onTouched()) !== false);
        allowDefault = (pd_1 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdid(8192,(null as any),0,import5.DefaultValueAccessor,[
      import1.Renderer,
      import1.ElementRef
    ]
    ,(null as any),(null as any)),
      import1.ɵdid(8192,(null as any),0,import5.RequiredValidator,([] as any[]),{required: [
        0,
        'required'
      ]
    },(null as any)),
    import1.ɵprd(512,(null as any),import5.NG_VALIDATORS,(p0_0:any) => {
      return [p0_0];
    },[import5.RequiredValidator]),
    import1.ɵprd(512,(null as any),import5.NG_VALUE_ACCESSOR,(p0_0:any) => {
      return [p0_0];
    },[import5.DefaultValueAccessor]),
    import1.ɵdid(335872,(null as any),0,import5.FormControlName,[
      [
        3,
        import5.ControlContainer
      ]
      ,
      [
        2,
        import5.NG_VALIDATORS
      ]
      ,
      [
        8,
        (null as any)
      ]
      ,
      [
        2,
        import5.NG_VALUE_ACCESSOR
      ]

    ]
      ,{name: [
        0,
        'name'
      ]
    },(null as any)),
    import1.ɵprd(1024,(null as any),import5.NgControl,(null as any),[import5.FormControlName]),
    import1.ɵdid(8192,(null as any),0,import5.NgControlStatus,[import5.NgControl],(null as any),(null as any)),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵted((null as any),['\n          ']),
      import1.ɵeld(0,(null as any),(null as any),4,'div',[[
        'class',
        'error-block'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵeld(0,(null as any),(null as any),1,'button',[
      [
        'class',
        'btn btn-default btn-block'
      ]
      ,
      [
        'type',
        'submit'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Sign up']),
    import1.ɵted((null as any),['\n        ']),
    import1.ɵted((null as any),['\n        ']),
    import1.ɵeld(0,(null as any),(null as any),2,'a',[
      [
        'class',
        'nav-text'
      ]
      ,
      [
        'routerLink',
        '/login'
      ]

    ]
    ,[
      [
        0,
        'target',
        0
      ]
      ,
      [
        3,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.SignupComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,83).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdid(335872,(null as any),0,import3.RouterLinkWithHref,[
      import3.Router,
      import3.ActivatedRoute,
      import4.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵted((null as any),['Already have an account? Sign in here.']),
    import1.ɵted((null as any),['\n      ']),
    import1.ɵted((null as any),['\n    ']),
    import1.ɵted((null as any),['\n    ']),
      import1.ɵeld(0,(null as any),(null as any),7,'aside',[[
        'class',
        'hidden-sm col-md-6 col-lg-7'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n      ']),
    import1.ɵeld(0,(null as any),(null as any),4,'ul',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n        ']),
    import1.ɵeld(0,(null as any),(null as any),1,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Slide']),
    import1.ɵted((null as any),['\n      ']),
    import1.ɵted((null as any),['\n    ']),
    import1.ɵted((null as any),['\n  ']),
    import1.ɵted((null as any),['\n']),
    import1.ɵted((null as any),['\n'])
  ]
  ,(check,view) => {
    var comp:import2.SignupComponent = view.component;
    const currVal_0:any = '/discover';
    check(view,14,0,currVal_0);
    const currVal_1:any = comp.error;
    check(view,22,0,currVal_1);
    const currVal_2:any = comp.signupForm;
    check(view,26,0,currVal_2);
    const currVal_3:any = '';
    check(view,42,0,currVal_3);
    const currVal_4:any = 'email';
    check(view,45,0,currVal_4);
    const currVal_5:any = '';
    check(view,63,0,currVal_5);
    const currVal_6:any = 'password';
    check(view,66,0,currVal_6);
    const currVal_7:any = '/login';
    check(view,83,0,currVal_7);
  },(check,view) => {
    var comp:import2.SignupComponent = view.component;
    const currVal_0:any = import1.ɵnov(view,14).target;
    const currVal_1:any = import1.ɵnov(view,14).href;
    check(view,13,0,currVal_0,currVal_1);
    const currVal_2:any = import1.ɵnov(view,28).ngClassUntouched;
    const currVal_3:any = import1.ɵnov(view,28).ngClassTouched;
    const currVal_4:any = import1.ɵnov(view,28).ngClassPristine;
    const currVal_5:any = import1.ɵnov(view,28).ngClassDirty;
    const currVal_6:any = import1.ɵnov(view,28).ngClassValid;
    const currVal_7:any = import1.ɵnov(view,28).ngClassInvalid;
    const currVal_8:any = import1.ɵnov(view,28).ngClassPending;
    check(view,24,0,currVal_2,currVal_3,currVal_4,currVal_5,currVal_6,currVal_7,currVal_8);
    const currVal_9:any = (import1.ɵnov(view,42).required? '': (null as any));
    const currVal_10:any = import1.ɵnov(view,47).ngClassUntouched;
    const currVal_11:any = import1.ɵnov(view,47).ngClassTouched;
    const currVal_12:any = import1.ɵnov(view,47).ngClassPristine;
    const currVal_13:any = import1.ɵnov(view,47).ngClassDirty;
    const currVal_14:any = import1.ɵnov(view,47).ngClassValid;
    const currVal_15:any = import1.ɵnov(view,47).ngClassInvalid;
    const currVal_16:any = import1.ɵnov(view,47).ngClassPending;
    check(view,40,0,currVal_9,currVal_10,currVal_11,currVal_12,currVal_13,currVal_14,currVal_15,currVal_16);
    const currVal_17:any = (import1.ɵnov(view,63).required? '': (null as any));
    const currVal_18:any = import1.ɵnov(view,68).ngClassUntouched;
    const currVal_19:any = import1.ɵnov(view,68).ngClassTouched;
    const currVal_20:any = import1.ɵnov(view,68).ngClassPristine;
    const currVal_21:any = import1.ɵnov(view,68).ngClassDirty;
    const currVal_22:any = import1.ɵnov(view,68).ngClassValid;
    const currVal_23:any = import1.ɵnov(view,68).ngClassInvalid;
    const currVal_24:any = import1.ɵnov(view,68).ngClassPending;
    check(view,61,0,currVal_17,currVal_18,currVal_19,currVal_20,currVal_21,currVal_22,currVal_23,currVal_24);
    const currVal_25:any = import1.ɵnov(view,83).target;
    const currVal_26:any = import1.ɵnov(view,83).href;
    check(view,82,0,currVal_25,currVal_26);
  });
}
const RenderType_SignupComponent_Host:import1.RendererTypeV2 = import1.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_SignupComponent_Host_0():import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    import1.ɵeld(0,(null as any),(null as any),1,'signup',([] as any[]),(null as any),(null as any),(null as any),View_SignupComponent_0,RenderType_SignupComponent),
    import1.ɵdid(122880,(null as any),0,import2.SignupComponent,[
      import6.AuthModelService,
      import3.Router,
      import7.MetaService,
      import5.FormBuilder
    ]
    ,(null as any),(null as any))
  ]
  ,(check,view) => {
    check(view,1,0);
  },(null as any));
}
export const SignupComponentNgFactory:import1.ComponentFactory<import2.SignupComponent> = import1.ɵccf('signup',import2.SignupComponent,View_SignupComponent_Host_0);