/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './support.component';
const styles_SupportComponent:any[] = ([] as any[]);
export const RenderType_SupportComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_SupportComponent,
  data: {}
}
);
export function View_SupportComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Support component'])],(null as any),(null as any));
}
const RenderType_SupportComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_SupportComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'support',([] as any[]),(null as any),(null as any),(null as any),View_SupportComponent_0,RenderType_SupportComponent),
    import0.ɵdid(24576,(null as any),0,import1.SupportComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const SupportComponentNgFactory:import0.ComponentFactory<import1.SupportComponent> = import0.ɵccf('support',import1.SupportComponent,View_SupportComponent_Host_0);