/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './project-dashboard.component';
const styles_ProjectDashboardComponent:any[] = ([] as any[]);
export const RenderType_ProjectDashboardComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_ProjectDashboardComponent,
  data: {}
}
);
export function View_ProjectDashboardComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Project Dashboard component'])],(null as any),(null as any));
}
const RenderType_ProjectDashboardComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_ProjectDashboardComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'project-dashboard',([] as any[]),(null as any),(null as any),(null as any),View_ProjectDashboardComponent_0,RenderType_ProjectDashboardComponent),
    import0.ɵdid(24576,(null as any),0,import1.ProjectDashboardComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const ProjectDashboardComponentNgFactory:import0.ComponentFactory<import1.ProjectDashboardComponent> = import0.ɵccf('project-dashboard',import1.ProjectDashboardComponent,View_ProjectDashboardComponent_Host_0);