/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './featured.component';
const styles_FeaturedComponent:any[] = ([] as any[]);
export const RenderType_FeaturedComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_FeaturedComponent,
  data: {}
}
);
export function View_FeaturedComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Featured component'])],(null as any),(null as any));
}
const RenderType_FeaturedComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_FeaturedComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'featured',([] as any[]),(null as any),(null as any),(null as any),View_FeaturedComponent_0,RenderType_FeaturedComponent),
    import0.ɵdid(24576,(null as any),0,import1.FeaturedComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const FeaturedComponentNgFactory:import0.ComponentFactory<import1.FeaturedComponent> = import0.ɵccf('featured',import1.FeaturedComponent,View_FeaturedComponent_Host_0);