/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './user-routing.module';
import * as import2 from '@angular/router';
import * as import3 from './single/single-user.component.ngfactory';
import * as import4 from './single/single-user.component';
class UserRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.UserRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _UserRoutingModule_1:import1.UserRoutingModule;
  __ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,[import3.SingleUserComponentNgFactory],([] as any[]));
  }
  get _ROUTES_2():any[] {
        if ((this.__ROUTES_2 == null)) { (this.__ROUTES_2 = [[{
          path: 'user/:slug',
          component: import4.SingleUserComponent
        }
    ]]); }
    return this.__ROUTES_2;
  }
  createInternal():import1.UserRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)));
    this._UserRoutingModule_1 = new import1.UserRoutingModule();
    return this._UserRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.UserRoutingModule)) { return this._UserRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const UserRoutingModuleNgFactory:import0.NgModuleFactory<import1.UserRoutingModule> = new import0.NgModuleFactory<any>(UserRoutingModuleInjector,import1.UserRoutingModule);