/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './contact.component';
const styles_ContactComponent:any[] = ([] as any[]);
export const RenderType_ContactComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_ContactComponent,
  data: {}
}
);
export function View_ContactComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Contact component'])],(null as any),(null as any));
}
const RenderType_ContactComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_ContactComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'contact',([] as any[]),(null as any),(null as any),(null as any),View_ContactComponent_0,RenderType_ContactComponent),
    import0.ɵdid(24576,(null as any),0,import1.ContactComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const ContactComponentNgFactory:import0.ComponentFactory<import1.ContactComponent> = import0.ɵccf('contact',import1.ContactComponent,View_ContactComponent_Host_0);