/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './contact-routing.module';
import * as import2 from '@angular/router';
import * as import3 from './contact.component.ngfactory';
import * as import4 from './newsletters/newsletters.component.ngfactory';
import * as import5 from './contact.component';
import * as import6 from './newsletters/newsletters.component';
class ContactRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.ContactRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _ContactRoutingModule_1:import1.ContactRoutingModule;
  __ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,[
      import3.ContactComponentNgFactory,
      import4.NewslettersComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _ROUTES_2():any[] {
      if ((this.__ROUTES_2 == null)) { (this.__ROUTES_2 = [[
        {
          path: 'contact',
          component: import5.ContactComponent
        }
        ,
        {
          path: 'newsletters',
          component: import6.NewslettersComponent
        }

      ]
    ]); }
    return this.__ROUTES_2;
  }
  createInternal():import1.ContactRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)));
    this._ContactRoutingModule_1 = new import1.ContactRoutingModule();
    return this._ContactRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.ContactRoutingModule)) { return this._ContactRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ContactRoutingModuleNgFactory:import0.NgModuleFactory<import1.ContactRoutingModule> = new import0.NgModuleFactory<any>(ContactRoutingModuleInjector,import1.ContactRoutingModule);