/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './explore.component';
const styles_ExploreComponent:any[] = ([] as any[]);
export const RenderType_ExploreComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_ExploreComponent,
  data: {}
}
);
export function View_ExploreComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Explore component'])],(null as any),(null as any));
}
const RenderType_ExploreComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_ExploreComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'explore',([] as any[]),(null as any),(null as any),(null as any),View_ExploreComponent_0,RenderType_ExploreComponent),
    import0.ɵdid(24576,(null as any),0,import1.ExploreComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const ExploreComponentNgFactory:import0.ComponentFactory<import1.ExploreComponent> = import0.ɵccf('explore',import1.ExploreComponent,View_ExploreComponent_Host_0);