/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './explore-routing.module';
import * as import2 from '@angular/router';
import * as import3 from './explore.component.ngfactory';
import * as import4 from './featured/featured.component.ngfactory';
import * as import5 from './popular/popular.component.ngfactory';
import * as import6 from './categories/categories.component.ngfactory';
import * as import7 from './explore.component';
import * as import8 from './featured/featured.component';
import * as import9 from './popular/popular.component';
import * as import10 from './categories/categories.component';
class ExploreRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.ExploreRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _ExploreRoutingModule_1:import1.ExploreRoutingModule;
  __ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,[
      import3.ExploreComponentNgFactory,
      import4.FeaturedComponentNgFactory,
      import5.PopularComponentNgFactory,
      import6.CategoriesComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _ROUTES_2():any[] {
      if ((this.__ROUTES_2 == null)) { (this.__ROUTES_2 = [[
        {
          path: 'explore',
          component: import7.ExploreComponent
        }
        ,
        {
          path: 'explore/featured',
          component: import8.FeaturedComponent
        }
        ,
        {
          path: 'explore/popular',
          component: import9.PopularComponent
        }
        ,
        {
          path: 'explore/categories',
          component: import10.CategoriesComponent
        }

      ]
    ]); }
    return this.__ROUTES_2;
  }
  createInternal():import1.ExploreRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)));
    this._ExploreRoutingModule_1 = new import1.ExploreRoutingModule();
    return this._ExploreRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.ExploreRoutingModule)) { return this._ExploreRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ExploreRoutingModuleNgFactory:import0.NgModuleFactory<import1.ExploreRoutingModule> = new import0.NgModuleFactory<any>(ExploreRoutingModuleInjector,import1.ExploreRoutingModule);