/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './welcome.component';
const styles_WelcomeComponent:any[] = ([] as any[]);
export const RenderType_WelcomeComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_WelcomeComponent,
  data: {}
}
);
export function View_WelcomeComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Welcome component'])],(null as any),(null as any));
}
const RenderType_WelcomeComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_WelcomeComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'welcome',([] as any[]),(null as any),(null as any),(null as any),View_WelcomeComponent_0,RenderType_WelcomeComponent),
    import0.ɵdid(24576,(null as any),0,import1.WelcomeComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const WelcomeComponentNgFactory:import0.ComponentFactory<import1.WelcomeComponent> = import0.ɵccf('welcome',import1.WelcomeComponent,View_WelcomeComponent_Host_0);