/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './categories.component';
const styles_CategoriesComponent:any[] = ([] as any[]);
export const RenderType_CategoriesComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_CategoriesComponent,
  data: {}
}
);
export function View_CategoriesComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Categories component'])],(null as any),(null as any));
}
const RenderType_CategoriesComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_CategoriesComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'categories',([] as any[]),(null as any),(null as any),(null as any),View_CategoriesComponent_0,RenderType_CategoriesComponent),
    import0.ɵdid(24576,(null as any),0,import1.CategoriesComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const CategoriesComponentNgFactory:import0.ComponentFactory<import1.CategoriesComponent> = import0.ɵccf('categories',import1.CategoriesComponent,View_CategoriesComponent_Host_0);