/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './privacy.component';
const styles_PrivacyComponent:any[] = ([] as any[]);
export const RenderType_PrivacyComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_PrivacyComponent,
  data: {}
}
);
export function View_PrivacyComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Privacy component'])],(null as any),(null as any));
}
const RenderType_PrivacyComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_PrivacyComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'privacy',([] as any[]),(null as any),(null as any),(null as any),View_PrivacyComponent_0,RenderType_PrivacyComponent),
    import0.ɵdid(24576,(null as any),0,import1.PrivacyComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const PrivacyComponentNgFactory:import0.ComponentFactory<import1.PrivacyComponent> = import0.ɵccf('privacy',import1.PrivacyComponent,View_PrivacyComponent_Host_0);