/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './newsletters.component';
const styles_NewslettersComponent:any[] = ([] as any[]);
export const RenderType_NewslettersComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_NewslettersComponent,
  data: {}
}
);
export function View_NewslettersComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Newsletters component'])],(null as any),(null as any));
}
const RenderType_NewslettersComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_NewslettersComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'newsletters',([] as any[]),(null as any),(null as any),(null as any),View_NewslettersComponent_0,RenderType_NewslettersComponent),
    import0.ɵdid(24576,(null as any),0,import1.NewslettersComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const NewslettersComponentNgFactory:import0.ComponentFactory<import1.NewslettersComponent> = import0.ɵccf('newsletters',import1.NewslettersComponent,View_NewslettersComponent_Host_0);