/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './team-routing.module';
import * as import2 from '@angular/router';
import * as import3 from './single/single-team.component.ngfactory';
import * as import4 from './single/dashboard/team-dashboard.component.ngfactory';
import * as import5 from './single/single-team.component';
import * as import6 from './single/dashboard/team-dashboard.component';
class TeamRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.TeamRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _TeamRoutingModule_1:import1.TeamRoutingModule;
  __ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,[
      import3.SingleTeamComponentNgFactory,
      import4.TeamDashboardComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _ROUTES_2():any[] {
      if ((this.__ROUTES_2 == null)) { (this.__ROUTES_2 = [[
        {
          path: 'team/:slug',
          component: import5.SingleTeamComponent
        }
        ,
        {
          path: 'team/:slug/dashboard',
          component: import6.TeamDashboardComponent
        }

      ]
    ]); }
    return this.__ROUTES_2;
  }
  createInternal():import1.TeamRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)));
    this._TeamRoutingModule_1 = new import1.TeamRoutingModule();
    return this._TeamRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.TeamRoutingModule)) { return this._TeamRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const TeamRoutingModuleNgFactory:import0.NgModuleFactory<import1.TeamRoutingModule> = new import0.NgModuleFactory<any>(TeamRoutingModuleInjector,import1.TeamRoutingModule);