/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './popular.component';
const styles_PopularComponent:any[] = ([] as any[]);
export const RenderType_PopularComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_PopularComponent,
  data: {}
}
);
export function View_PopularComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Popular component'])],(null as any),(null as any));
}
const RenderType_PopularComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_PopularComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'popular',([] as any[]),(null as any),(null as any),(null as any),View_PopularComponent_0,RenderType_PopularComponent),
    import0.ɵdid(24576,(null as any),0,import1.PopularComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const PopularComponentNgFactory:import0.ComponentFactory<import1.PopularComponent> = import0.ɵccf('popular',import1.PopularComponent,View_PopularComponent_Host_0);