/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './single-application.component';
const styles_SingleApplicationComponent:any[] = ([] as any[]);
export const RenderType_SingleApplicationComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_SingleApplicationComponent,
  data: {}
}
);
export function View_SingleApplicationComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Single Application component'])],(null as any),(null as any));
}
const RenderType_SingleApplicationComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_SingleApplicationComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'single-application',([] as any[]),(null as any),(null as any),(null as any),View_SingleApplicationComponent_0,RenderType_SingleApplicationComponent),
    import0.ɵdid(24576,(null as any),0,import1.SingleApplicationComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const SingleApplicationComponentNgFactory:import0.ComponentFactory<import1.SingleApplicationComponent> = import0.ɵccf('single-application',import1.SingleApplicationComponent,View_SingleApplicationComponent_Host_0);