/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './trending-users.component';
const styles_TrendingUsersComponent:any[] = ([] as any[]);
export const RenderType_TrendingUsersComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_TrendingUsersComponent,
  data: {}
}
);
export function View_TrendingUsersComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Trending Users component'])],(null as any),(null as any));
}
const RenderType_TrendingUsersComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_TrendingUsersComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'trending-users',([] as any[]),(null as any),(null as any),(null as any),View_TrendingUsersComponent_0,RenderType_TrendingUsersComponent),
    import0.ɵdid(24576,(null as any),0,import1.TrendingUsersComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const TrendingUsersComponentNgFactory:import0.ComponentFactory<import1.TrendingUsersComponent> = import0.ɵccf('trending-users',import1.TrendingUsersComponent,View_TrendingUsersComponent_Host_0);