/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['article[_ngcontent-%COMP%] {position: relative;height: 100vh;box-shadow: 3px 0 6px rgba(0,0,0,0.16), 3px 0 6px rgba(0,0,0,0.23);z-index: 5;}\r\n\r\naside[_ngcontent-%COMP%] {height: 100vh;background-color: #ccc}\r\n\r\ninput[_ngcontent-%COMP%] {background: transparent;border-color: transparent;border-radius: 4px!important;}\r\n\r\n.auth-contain[_ngcontent-%COMP%] {overflow: hidden;}\r\n\r\n.logo[_ngcontent-%COMP%] {display: block;margin-bottom: 30px;width: 100%;height: 45px; background:transparent url(\'https://cdn.heystitch.io/web/common/images/logos/logotype-web.png\') no-repeat center center;background-size: contain;}\r\n.form-contain[_ngcontent-%COMP%] {position: absolute;top: 50%; left: 50%; -webkit-transform: translate(-50%, -50%); transform: translate(-50%, -50%);  min-width:250px; max-width: 300px;}\r\n\r\n.input-group-addon[_ngcontent-%COMP%] {border-color: transparent;background: transparent;}\r\n\r\n.nav-text[_ngcontent-%COMP%] {float: right;margin-top: 20px;}\r\n\r\n.ng-dirty.ng-touched.ng-invalid[_ngcontent-%COMP%] {border-color: #ee3f4a;}\r\n\r\n.error-block[_ngcontent-%COMP%]   p[_ngcontent-%COMP%] {display: block;}'];