/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './faq.component';
const styles_FaqComponent:any[] = ([] as any[]);
export const RenderType_FaqComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_FaqComponent,
  data: {}
}
);
export function View_FaqComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['FAQ component'])],(null as any),(null as any));
}
const RenderType_FaqComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_FaqComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'faq',([] as any[]),(null as any),(null as any),(null as any),View_FaqComponent_0,RenderType_FaqComponent),
    import0.ɵdid(24576,(null as any),0,import1.FaqComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const FaqComponentNgFactory:import0.ComponentFactory<import1.FaqComponent> = import0.ɵccf('faq',import1.FaqComponent,View_FaqComponent_Host_0);