/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './settings-routing.module';
import * as import2 from '@angular/router';
import * as import3 from './settings.component.ngfactory';
import * as import4 from './settings.component';
class SettingsRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.SettingsRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _SettingsRoutingModule_1:import1.SettingsRoutingModule;
  __ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,[import3.SettingsComponentNgFactory],([] as any[]));
  }
  get _ROUTES_2():any[] {
        if ((this.__ROUTES_2 == null)) { (this.__ROUTES_2 = [[{
          path: 'settings',
          component: import4.SettingsComponent
        }
    ]]); }
    return this.__ROUTES_2;
  }
  createInternal():import1.SettingsRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)));
    this._SettingsRoutingModule_1 = new import1.SettingsRoutingModule();
    return this._SettingsRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.SettingsRoutingModule)) { return this._SettingsRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const SettingsRoutingModuleNgFactory:import0.NgModuleFactory<import1.SettingsRoutingModule> = new import0.NgModuleFactory<any>(SettingsRoutingModuleInjector,import1.SettingsRoutingModule);