/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './settings.component';
const styles_SettingsComponent:any[] = ([] as any[]);
export const RenderType_SettingsComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_SettingsComponent,
  data: {}
}
);
export function View_SettingsComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Settings component'])],(null as any),(null as any));
}
const RenderType_SettingsComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_SettingsComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'settings',([] as any[]),(null as any),(null as any),(null as any),View_SettingsComponent_0,RenderType_SettingsComponent),
    import0.ɵdid(24576,(null as any),0,import1.SettingsComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const SettingsComponentNgFactory:import0.ComponentFactory<import1.SettingsComponent> = import0.ɵccf('settings',import1.SettingsComponent,View_SettingsComponent_Host_0);