/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './use.component';
const styles_UseComponent:any[] = ([] as any[]);
export const RenderType_UseComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_UseComponent,
  data: {}
}
);
export function View_UseComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Terms of Use component'])],(null as any),(null as any));
}
const RenderType_UseComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_UseComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'use',([] as any[]),(null as any),(null as any),(null as any),View_UseComponent_0,RenderType_UseComponent),
    import0.ɵdid(24576,(null as any),0,import1.UseComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const UseComponentNgFactory:import0.ComponentFactory<import1.UseComponent> = import0.ɵccf('use',import1.UseComponent,View_UseComponent_Host_0);