/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './create-routing.module';
import * as import2 from '@angular/router';
import * as import3 from './create.component.ngfactory';
import * as import4 from './create.component';
class CreateRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.CreateRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _CreateRoutingModule_1:import1.CreateRoutingModule;
  __ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,[import3.CreateComponentNgFactory],([] as any[]));
  }
  get _ROUTES_2():any[] {
        if ((this.__ROUTES_2 == null)) { (this.__ROUTES_2 = [[{
          path: 'create',
          component: import4.CreateComponent
        }
    ]]); }
    return this.__ROUTES_2;
  }
  createInternal():import1.CreateRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)));
    this._CreateRoutingModule_1 = new import1.CreateRoutingModule();
    return this._CreateRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.CreateRoutingModule)) { return this._CreateRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const CreateRoutingModuleNgFactory:import0.NgModuleFactory<import1.CreateRoutingModule> = new import0.NgModuleFactory<any>(CreateRoutingModuleInjector,import1.CreateRoutingModule);