/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './create.component';
const styles_CreateComponent:any[] = ([] as any[]);
export const RenderType_CreateComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_CreateComponent,
  data: {}
}
);
export function View_CreateComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Create component'])],(null as any),(null as any));
}
const RenderType_CreateComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_CreateComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'create',([] as any[]),(null as any),(null as any),(null as any),View_CreateComponent_0,RenderType_CreateComponent),
    import0.ɵdid(24576,(null as any),0,import1.CreateComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const CreateComponentNgFactory:import0.ComponentFactory<import1.CreateComponent> = import0.ɵccf('create',import1.CreateComponent,View_CreateComponent_Host_0);