/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './nav.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '@angular/router';
import * as import3 from './nav.component';
import * as import4 from '@angular/common';
import * as import5 from '../../../auth/models/auth.model.service';
const styles_MainNavComponent:any[] = [import0.styles];
export const RenderType_MainNavComponent:import1.RendererTypeV2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_MainNavComponent,
  data: {}
}
);
function View_MainNavComponent_1():import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    import1.ɵeld(0,(null as any),(null as any),11,'ul',[
      [
        'class',
        'nav navbar-nav navbar-right'
      ]
      ,
      [
        'style',
        'border-left: 1px solid #eee;padding-left: 25px;'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵeld(0,(null as any),(null as any),3,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵeld(0,(null as any),(null as any),2,'button',[
      [
        'class',
        'btn btn-primary navbar-btn'
      ]
      ,
      [
        'routerLink',
        'signup'
      ]
      ,
      [
        'type',
        'button'
      ]

    ]
      ,(null as any),[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:any = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,4).onClick()) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdid(8192,(null as any),0,import2.RouterLink,[
      import2.Router,
      import2.ActivatedRoute,
      [
        8,
        (null as any)
      ]
      ,
      import1.Renderer,
      import1.ElementRef
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵted((null as any),['Sign up']),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵeld(0,(null as any),(null as any),3,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵeld(0,(null as any),(null as any),2,'button',[
      [
        'class',
        'btn navbar-btn'
      ]
      ,
      [
        'routerLink',
        'login'
      ]
      ,
      [
        'type',
        'button'
      ]

    ]
      ,(null as any),[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:any = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,9).onClick()) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdid(8192,(null as any),0,import2.RouterLink,[
      import2.Router,
      import2.ActivatedRoute,
      [
        8,
        (null as any)
      ]
      ,
      import1.Renderer,
      import1.ElementRef
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵted((null as any),['Log in']),
    import1.ɵted((null as any),['\n        '])
  ]
  ,(check,view) => {
    var comp:any = view.component;
    const currVal_0:any = 'signup';
    check(view,4,0,currVal_0);
    const currVal_1:any = 'login';
    check(view,9,0,currVal_1);
  },(null as any));
}
function View_MainNavComponent_2():import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    import1.ɵeld(0,(null as any),(null as any),8,'ul',[
      [
        'class',
        'nav navbar-nav navbar-right'
      ]
      ,
      [
        'style',
        'border-left: 1px solid #eee;padding-left: 25px;'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵeld(0,(null as any),(null as any),1,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),[
      '',
      ''
    ]
    ),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵeld(0,(null as any),(null as any),2,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵeld(0,(null as any),(null as any),1,'button',[
      [
        'class',
        'btn navbar-btn'
      ]
      ,
      [
        'type',
        'button'
      ]

    ]
      ,(null as any),[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:any = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>comp.logout()) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵted((null as any),['Sign out']),
    import1.ɵted((null as any),['\n        '])
  ]
  ,(null as any),(check,view) => {
    var comp:any = view.component;
    const currVal_0:any = ((comp.authUser == null)? (null as any): comp.authUser.id);
    check(view,3,0,currVal_0);
  });
}
function View_MainNavComponent_3():import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    import1.ɵeld(0,(null as any),(null as any),10,'ul',[
      [
        'class',
        'nav navbar-nav navbar-right'
      ]
      ,
      [
        'style',
        'border-left: 1px solid #eee;padding: 0 7px;'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵeld(0,(null as any),(null as any),7,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵeld(0,(null as any),(null as any),6,'button',[
      [
        'class',
        'btn navbar-btn navbar-btn-icon navbar-btn-icon-bell active'
      ]
      ,
      [
        'type',
        'button'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵeld(0,(null as any),(null as any),0,'i',[
      [
        'class',
        'icon-bell'
      ]
      ,
      [
        'style',
        'font-size: 18px;'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n            ']),
      import1.ɵeld(0,(null as any),(null as any),1,'span',[[
        'class',
        'sr-only'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Notifications']),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵted((null as any),['\n        '])
  ]
  ,(null as any),(null as any));
}
function View_MainNavComponent_4():import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    import1.ɵeld(0,(null as any),(null as any),10,'ul',[
      [
        'class',
        'nav navbar-nav navbar-right'
      ]
      ,
      [
        'style',
        'border-left: 1px solid #eee;padding: 0 7px;'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵeld(0,(null as any),(null as any),7,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵeld(0,(null as any),(null as any),6,'button',[
      [
        'class',
        'btn navbar-btn navbar-btn-icon navbar-btn-icon-message active'
      ]
      ,
      [
        'type',
        'button'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵeld(0,(null as any),(null as any),0,'i',[
      [
        'class',
        'icon-message'
      ]
      ,
      [
        'style',
        'font-size: 18px;'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n            ']),
      import1.ɵeld(0,(null as any),(null as any),1,'span',[[
        'class',
        'sr-only'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Messages']),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵted((null as any),['\n        '])
  ]
  ,(null as any),(null as any));
}
export function View_MainNavComponent_0():import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    import1.ɵeld(0,(null as any),(null as any),83,'nav',[
      [
        'class',
        'navbar navbar-default'
      ]
      ,
      [
        'style',
        'margin-bottom:0;'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n    ']),
    import1.ɵeld(0,(null as any),(null as any),80,'div',[
      [
        'class',
        'container'
      ]
      ,
      [
        'style',
        'padding:0;'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n      ']),
      import1.ɵeld(0,(null as any),(null as any),22,'div',[[
        'class',
        'navbar-header'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n        ']),
    import1.ɵeld(0,(null as any),(null as any),10,'button',[
      [
        'aria-expanded',
        'false'
      ]
      ,
      [
        'class',
        'navbar-toggle collapsed'
      ]
      ,
      [
        'data-target',
        '#navbar-collapse'
      ]
      ,
      [
        'data-toggle',
        'collapse'
      ]
      ,
      [
        'type',
        'button'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n          ']),
      import1.ɵeld(0,(null as any),(null as any),1,'span',[[
        'class',
        'sr-only'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Toggle navigation']),
    import1.ɵted((null as any),['\n          ']),
      import1.ɵeld(0,(null as any),(null as any),0,'span',[[
        'class',
        'icon-bar'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n          ']),
      import1.ɵeld(0,(null as any),(null as any),0,'span',[[
        'class',
        'icon-bar'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n          ']),
      import1.ɵeld(0,(null as any),(null as any),0,'span',[[
        'class',
        'icon-bar'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n        ']),
    import1.ɵted((null as any),['\n        ']),
    import1.ɵeld(0,(null as any),(null as any),7,'a',[
      [
        'class',
        'navbar-brand'
      ]
      ,
      [
        'routerLink',
        'discover'
      ]

    ]
    ,[
      [
        0,
        'target',
        0
      ]
      ,
      [
        3,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import3.MainNavComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,19).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdid(335872,(null as any),0,import2.RouterLinkWithHref,[
      import2.Router,
      import2.ActivatedRoute,
      import4.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵeld(0,(null as any),(null as any),0,'img',[
      [
        'alt',
        'Stitch Icon'
      ]
      ,
      [
        'src',
        'https://cdn.heystitch.io/web/common/images/logos/logo-web.png'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n          ']),
      import1.ɵeld(0,(null as any),(null as any),1,'span',[[
        'class',
        'sr-only'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Stitch']),
    import1.ɵted((null as any),['\n        ']),
    import1.ɵted((null as any),['\n      ']),
    import1.ɵted((null as any),['\n      ']),
      import1.ɵeld(0,(null as any),(null as any),53,'div',[[
        'class',
        'collapse navbar-collapse'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n        ']),
    import1.ɵand(8388608,(null as any),(null as any),1,(null as any),View_MainNavComponent_1),
    import1.ɵdid(8192,(null as any),0,import4.NgIf,[
      import1.ViewContainerRef,
      import1.TemplateRef
    ]
      ,{ngIf: [
        0,
        'ngIf'
      ]
    },(null as any)),
    import1.ɵted((null as any),['\n        ']),
    import1.ɵand(8388608,(null as any),(null as any),1,(null as any),View_MainNavComponent_2),
    import1.ɵdid(8192,(null as any),0,import4.NgIf,[
      import1.ViewContainerRef,
      import1.TemplateRef
    ]
      ,{ngIf: [
        0,
        'ngIf'
      ]
    },(null as any)),
    import1.ɵted((null as any),['\n        ']),
    import1.ɵand(8388608,(null as any),(null as any),1,(null as any),View_MainNavComponent_3),
    import1.ɵdid(8192,(null as any),0,import4.NgIf,[
      import1.ViewContainerRef,
      import1.TemplateRef
    ]
      ,{ngIf: [
        0,
        'ngIf'
      ]
    },(null as any)),
    import1.ɵted((null as any),['\n        ']),
    import1.ɵand(8388608,(null as any),(null as any),1,(null as any),View_MainNavComponent_4),
    import1.ɵdid(8192,(null as any),0,import4.NgIf,[
      import1.ViewContainerRef,
      import1.TemplateRef
    ]
      ,{ngIf: [
        0,
        'ngIf'
      ]
    },(null as any)),
    import1.ɵted((null as any),['\n        ']),
    import1.ɵeld(0,(null as any),(null as any),11,'ul',[
      [
        'class',
        'nav navbar-nav navbar-right'
      ]
      ,
      [
        'style',
        'border-left: 1px solid #eee;padding: 0 7px;'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵeld(0,(null as any),(null as any),8,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵeld(0,(null as any),(null as any),7,'button',[
      [
        'class',
        'btn navbar-btn navbar-btn-icon'
      ]
      ,
      [
        'type',
        'button'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵeld(0,(null as any),(null as any),1,'i',[
      [
        'class',
        'icon-search'
      ]
      ,
      [
        'routerLink',
        'search'
      ]
      ,
      [
        'style',
        'font-size: 18px;'
      ]

    ]
      ,(null as any),[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import3.MainNavComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,48).onClick()) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdid(8192,(null as any),0,import2.RouterLink,[
      import2.Router,
      import2.ActivatedRoute,
      [
        8,
        (null as any)
      ]
      ,
      import1.Renderer,
      import1.ElementRef
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵted((null as any),['\n            ']),
      import1.ɵeld(0,(null as any),(null as any),1,'span',[[
        'class',
        'sr-only'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Search...']),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵted((null as any),['\n        ']),
    import1.ɵted((null as any),['\n        ']),
    import1.ɵeld(0,(null as any),(null as any),25,'ul',[
      [
        'class',
        'nav navbar-nav navbar-right'
      ]
      ,
      [
        'style',
        'padding-right: 10px;'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵeld(0,(null as any),(null as any),6,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵeld(0,(null as any),(null as any),5,'a',[
      [
        'routerLink',
        'discover'
      ]
      ,
      [
        'routerLinkActive',
        'router-link-active'
      ]

    ]
    ,[
      [
        0,
        'target',
        0
      ]
      ,
      [
        3,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import3.MainNavComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,59).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
      import1.ɵdid(335872,[[
        2,
        4
      ]
    ],0,import2.RouterLinkWithHref,[
      import2.Router,
      import2.ActivatedRoute,
      import4.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵdid(860160,(null as any),2,import2.RouterLinkActive,[
      import2.Router,
      import1.ElementRef,
      import1.Renderer,
      import1.ChangeDetectorRef
    ]
      ,{routerLinkActive: [
        0,
        'routerLinkActive'
      ]
    },(null as any)),
    import1.ɵqud(301989888,1,{links: 1}),
    import1.ɵqud(301989888,2,{linksWithHrefs: 1}),
    import1.ɵted((null as any),['Discover']),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵeld(0,(null as any),(null as any),6,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵeld(0,(null as any),(null as any),5,'a',[
      [
        'routerLink',
        'create'
      ]
      ,
      [
        'routerLinkActive',
        'router-link-active'
      ]

    ]
    ,[
      [
        0,
        'target',
        0
      ]
      ,
      [
        3,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import3.MainNavComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,67).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
      import1.ɵdid(335872,[[
        4,
        4
      ]
    ],0,import2.RouterLinkWithHref,[
      import2.Router,
      import2.ActivatedRoute,
      import4.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵdid(860160,(null as any),2,import2.RouterLinkActive,[
      import2.Router,
      import1.ElementRef,
      import1.Renderer,
      import1.ChangeDetectorRef
    ]
      ,{routerLinkActive: [
        0,
        'routerLinkActive'
      ]
    },(null as any)),
    import1.ɵqud(301989888,3,{links: 1}),
    import1.ɵqud(301989888,4,{linksWithHrefs: 1}),
    import1.ɵted((null as any),['Start a project']),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵeld(0,(null as any),(null as any),6,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵeld(0,(null as any),(null as any),5,'a',[
      [
        'routerLink',
        'about'
      ]
      ,
      [
        'routerLinkActive',
        'router-link-active'
      ]

    ]
    ,[
      [
        0,
        'target',
        0
      ]
      ,
      [
        3,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import3.MainNavComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,75).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
      import1.ɵdid(335872,[[
        6,
        4
      ]
    ],0,import2.RouterLinkWithHref,[
      import2.Router,
      import2.ActivatedRoute,
      import4.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵdid(860160,(null as any),2,import2.RouterLinkActive,[
      import2.Router,
      import1.ElementRef,
      import1.Renderer,
      import1.ChangeDetectorRef
    ]
      ,{routerLinkActive: [
        0,
        'routerLinkActive'
      ]
    },(null as any)),
    import1.ɵqud(301989888,5,{links: 1}),
    import1.ɵqud(301989888,6,{linksWithHrefs: 1}),
    import1.ɵted((null as any),['About']),
    import1.ɵted((null as any),['\n        ']),
    import1.ɵted((null as any),['\n      ']),
    import1.ɵted((null as any),['\n    ']),
    import1.ɵted((null as any),['\n  '])
  ]
  ,(check,view) => {
    var comp:import3.MainNavComponent = view.component;
    const currVal_0:any = 'discover';
    check(view,19,0,currVal_0);
    const currVal_1:boolean = !comp.isAuthenticated();
    check(view,31,0,currVal_1);
    const currVal_2:any = comp.isAuthenticated();
    check(view,34,0,currVal_2);
    const currVal_3:any = comp.isAuthenticated();
    check(view,37,0,currVal_3);
    const currVal_4:any = comp.isAuthenticated();
    check(view,40,0,currVal_4);
    const currVal_5:any = 'search';
    check(view,48,0,currVal_5);
    const currVal_6:any = 'discover';
    check(view,59,0,currVal_6);
    const currVal_7:any = 'router-link-active';
    check(view,60,0,currVal_7);
    const currVal_8:any = 'create';
    check(view,67,0,currVal_8);
    const currVal_9:any = 'router-link-active';
    check(view,68,0,currVal_9);
    const currVal_10:any = 'about';
    check(view,75,0,currVal_10);
    const currVal_11:any = 'router-link-active';
    check(view,76,0,currVal_11);
  },(check,view) => {
    var comp:import3.MainNavComponent = view.component;
    const currVal_0:any = import1.ɵnov(view,19).target;
    const currVal_1:any = import1.ɵnov(view,19).href;
    check(view,18,0,currVal_0,currVal_1);
    const currVal_2:any = import1.ɵnov(view,59).target;
    const currVal_3:any = import1.ɵnov(view,59).href;
    check(view,58,0,currVal_2,currVal_3);
    const currVal_4:any = import1.ɵnov(view,67).target;
    const currVal_5:any = import1.ɵnov(view,67).href;
    check(view,66,0,currVal_4,currVal_5);
    const currVal_6:any = import1.ɵnov(view,75).target;
    const currVal_7:any = import1.ɵnov(view,75).href;
    check(view,74,0,currVal_6,currVal_7);
  });
}
const RenderType_MainNavComponent_Host:import1.RendererTypeV2 = import1.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_MainNavComponent_Host_0():import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    import1.ɵeld(0,(null as any),(null as any),1,'main-nav',([] as any[]),(null as any),(null as any),(null as any),View_MainNavComponent_0,RenderType_MainNavComponent),
    import1.ɵdid(90112,(null as any),0,import3.MainNavComponent,[
      import5.AuthModelService,
      import2.Router
    ]
    ,(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const MainNavComponentNgFactory:import1.ComponentFactory<import3.MainNavComponent> = import1.ɵccf('main-nav',import3.MainNavComponent,View_MainNavComponent_Host_0);