/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.router-link-active[_ngcontent-%COMP%] {border-color:#51677a;}\r\n\r\n.navbar-btn-icon[_ngcontent-%COMP%] {position:relative;}\r\n\r\n.navbar-btn-icon.active[_ngcontent-%COMP%]:after {content:\'\';position:absolute;top:0px;right:10px;height:7px;width:7px;border:2px solid;border-radius:50px;}\r\n\r\n.navbar-btn-icon-message.active[_ngcontent-%COMP%]:after {border-color: #39f;}\r\n\r\n.navbar-btn-icon-bell.active[_ngcontent-%COMP%]:after {border-color: #fb617f;}'];