/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './cookies.component';
const styles_CookiesComponent:any[] = ([] as any[]);
export const RenderType_CookiesComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_CookiesComponent,
  data: {}
}
);
export function View_CookiesComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Cookies component'])],(null as any),(null as any));
}
const RenderType_CookiesComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_CookiesComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'cookies',([] as any[]),(null as any),(null as any),(null as any),View_CookiesComponent_0,RenderType_CookiesComponent),
    import0.ɵdid(24576,(null as any),0,import1.CookiesComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const CookiesComponentNgFactory:import0.ComponentFactory<import1.CookiesComponent> = import0.ɵccf('cookies',import1.CookiesComponent,View_CookiesComponent_Host_0);