/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './single-user.component';
const styles_SingleUserComponent:any[] = ([] as any[]);
export const RenderType_SingleUserComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_SingleUserComponent,
  data: {}
}
);
export function View_SingleUserComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Single User component'])],(null as any),(null as any));
}
const RenderType_SingleUserComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_SingleUserComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'single-user',([] as any[]),(null as any),(null as any),(null as any),View_SingleUserComponent_0,RenderType_SingleUserComponent),
    import0.ɵdid(24576,(null as any),0,import1.SingleUserComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const SingleUserComponentNgFactory:import0.ComponentFactory<import1.SingleUserComponent> = import0.ɵccf('single-user',import1.SingleUserComponent,View_SingleUserComponent_Host_0);