/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './search.component';
const styles_SearchComponent:any[] = ([] as any[]);
export const RenderType_SearchComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_SearchComponent,
  data: {}
}
);
export function View_SearchComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Search component'])],(null as any),(null as any));
}
const RenderType_SearchComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_SearchComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'search',([] as any[]),(null as any),(null as any),(null as any),View_SearchComponent_0,RenderType_SearchComponent),
    import0.ɵdid(24576,(null as any),0,import1.SearchComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const SearchComponentNgFactory:import0.ComponentFactory<import1.SearchComponent> = import0.ɵccf('search',import1.SearchComponent,View_SearchComponent_Host_0);