/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './trending-teams.component';
const styles_TrendingTeamsComponent:any[] = ([] as any[]);
export const RenderType_TrendingTeamsComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_TrendingTeamsComponent,
  data: {}
}
);
export function View_TrendingTeamsComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Trending Teams component'])],(null as any),(null as any));
}
const RenderType_TrendingTeamsComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_TrendingTeamsComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'trending-teams',([] as any[]),(null as any),(null as any),(null as any),View_TrendingTeamsComponent_0,RenderType_TrendingTeamsComponent),
    import0.ɵdid(24576,(null as any),0,import1.TrendingTeamsComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const TrendingTeamsComponentNgFactory:import0.ComponentFactory<import1.TrendingTeamsComponent> = import0.ɵccf('trending-teams',import1.TrendingTeamsComponent,View_TrendingTeamsComponent_Host_0);