/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './about-routing.module';
import * as import2 from '@angular/router';
import * as import3 from './about.component.ngfactory';
import * as import4 from './how-it-works/how-it-works.component.ngfactory';
import * as import5 from './welcome/welcome.component.ngfactory';
import * as import6 from './who-we-are/who-we-are.component.ngfactory';
import * as import7 from './press/press.component.ngfactory';
import * as import8 from './about.component';
import * as import9 from './how-it-works/how-it-works.component';
import * as import10 from './welcome/welcome.component';
import * as import11 from './who-we-are/who-we-are.component';
import * as import12 from './press/press.component';
class AboutRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.AboutRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _AboutRoutingModule_1:import1.AboutRoutingModule;
  __ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,[
      import3.AboutComponentNgFactory,
      import4.HowItWorksComponentNgFactory,
      import5.WelcomeComponentNgFactory,
      import6.WhoWeAreComponentNgFactory,
      import7.PressComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _ROUTES_2():any[] {
      if ((this.__ROUTES_2 == null)) { (this.__ROUTES_2 = [[
        {
          path: 'about',
          component: import8.AboutComponent
        }
        ,
        {
          path: 'about/how-it-works',
          component: import9.HowItWorksComponent
        }
        ,
        {
          path: 'about/welcome',
          component: import10.WelcomeComponent
        }
        ,
        {
          path: 'about/who-we-are',
          component: import11.WhoWeAreComponent
        }
        ,
        {
          path: 'about/press',
          component: import12.PressComponent
        }

      ]
    ]); }
    return this.__ROUTES_2;
  }
  createInternal():import1.AboutRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)));
    this._AboutRoutingModule_1 = new import1.AboutRoutingModule();
    return this._AboutRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.AboutRoutingModule)) { return this._AboutRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AboutRoutingModuleNgFactory:import0.NgModuleFactory<import1.AboutRoutingModule> = new import0.NgModuleFactory<any>(AboutRoutingModuleInjector,import1.AboutRoutingModule);