/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './about.component';
import * as import2 from '../shared/services/meta/meta.service';
const styles_AboutComponent:any[] = ([] as any[]);
export const RenderType_AboutComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_AboutComponent,
  data: {}
}
);
export function View_AboutComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['About component'])],(null as any),(null as any));
}
const RenderType_AboutComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_AboutComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'about',([] as any[]),(null as any),(null as any),(null as any),View_AboutComponent_0,RenderType_AboutComponent),
    import0.ɵdid(2121728,(null as any),0,import1.AboutComponent,[import2.MetaService],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const AboutComponentNgFactory:import0.ComponentFactory<import1.AboutComponent> = import0.ɵccf('about',import1.AboutComponent,View_AboutComponent_Host_0);