/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './jobs-routing.module';
import * as import2 from '@angular/router';
import * as import3 from './jobs.component.ngfactory';
import * as import4 from './jobs.component';
class JobsRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.JobsRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _JobsRoutingModule_1:import1.JobsRoutingModule;
  __ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,[import3.JobsComponentNgFactory],([] as any[]));
  }
  get _ROUTES_2():any[] {
        if ((this.__ROUTES_2 == null)) { (this.__ROUTES_2 = [[{
          path: 'jobs',
          component: import4.JobsComponent
        }
    ]]); }
    return this.__ROUTES_2;
  }
  createInternal():import1.JobsRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)));
    this._JobsRoutingModule_1 = new import1.JobsRoutingModule();
    return this._JobsRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.JobsRoutingModule)) { return this._JobsRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const JobsRoutingModuleNgFactory:import0.NgModuleFactory<import1.JobsRoutingModule> = new import0.NgModuleFactory<any>(JobsRoutingModuleInjector,import1.JobsRoutingModule);