/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './jobs.component';
const styles_JobsComponent:any[] = ([] as any[]);
export const RenderType_JobsComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_JobsComponent,
  data: {}
}
);
export function View_JobsComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Jobs component'])],(null as any),(null as any));
}
const RenderType_JobsComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_JobsComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'jobs',([] as any[]),(null as any),(null as any),(null as any),View_JobsComponent_0,RenderType_JobsComponent),
    import0.ɵdid(24576,(null as any),0,import1.JobsComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const JobsComponentNgFactory:import0.ComponentFactory<import1.JobsComponent> = import0.ɵccf('jobs',import1.JobsComponent,View_JobsComponent_Host_0);