/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './app-routing.module';
import * as import2 from '@angular/router';
class AppRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.AppRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _AppRoutingModule_1:import1.AppRoutingModule;
  __ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _ROUTES_2():any[] {
        if ((this.__ROUTES_2 == null)) { (this.__ROUTES_2 = [[{
          path: '',
          redirectTo: '/discover',
          pathMatch: 'full'
        }
    ]]); }
    return this.__ROUTES_2;
  }
  createInternal():import1.AppRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)));
    this._AppRoutingModule_1 = new import1.AppRoutingModule();
    return this._AppRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.AppRoutingModule)) { return this._AppRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AppRoutingModuleNgFactory:import0.NgModuleFactory<import1.AppRoutingModule> = new import0.NgModuleFactory<any>(AppRoutingModuleInjector,import1.AppRoutingModule);