/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './app.browser.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/platform-browser';
import * as import4 from '../modules/transfer-state/browser-transfer-state.module';
import * as import5 from '@angular/forms';
import * as import6 from '@angular/router';
import * as import7 from 'apollo-angular/build/src/ApolloModule';
import * as import8 from './shared/components/components.module';
import * as import9 from './shared/shared.module';
import * as import10 from './+about/about-routing.module';
import * as import11 from './+about/about.module';
import * as import12 from './auth/modules/auth-routing.module';
import * as import13 from './auth/modules/auth.module';
import * as import14 from './+contact/contact-routing.module';
import * as import15 from './+contact/contact.module';
import * as import16 from './create/create-routing.module';
import * as import17 from './create/create.module';
import * as import18 from './discover/discover-routing.module';
import * as import19 from './discover/discover.module';
import * as import20 from './+explore/explore-routing.module';
import * as import21 from './+explore/explore.module';
import * as import22 from './+help/help-routing.module';
import * as import23 from './+help/help.module';
import * as import24 from './+highlights/highlights-routing.module';
import * as import25 from './+highlights/highlights.module';
import * as import26 from './+jobs/jobs-routing.module';
import * as import27 from './+jobs/jobs.module';
import * as import28 from './+project/project-routing.module';
import * as import29 from './+project/project.module';
import * as import30 from './+search/search-routing.module';
import * as import31 from './+search/search.module';
import * as import32 from './+settings/settings-routing.module';
import * as import33 from './+settings/settings.module';
import * as import34 from './+team/team-routing.module';
import * as import35 from './+team/team.module';
import * as import36 from './+terms/terms-routing.module';
import * as import37 from './+terms/terms.module';
import * as import38 from './+trending/trending-routing.module';
import * as import39 from './+trending/trending.module';
import * as import40 from './+user/user-routing.module';
import * as import41 from './+user/user.module';
import * as import42 from './app-routing.module';
import * as import43 from './+404/404-routing.module';
import * as import44 from '@ngrx/store/src/ng2';
import * as import45 from './app.module';
import * as import46 from 'angular2-cookie/services/cookies.service';
import * as import47 from './shared/services/cache/cache.service';
import * as import48 from '@ngrx/store/src/dispatcher';
import * as import49 from './shared/services/cache/hash.service';
import * as import50 from './shared/services/api/api.service';
import * as import51 from './auth/models/auth.model.service';
import * as import52 from './shared/services/meta/meta.service';
import * as import53 from './+about/about.component.ngfactory';
import * as import54 from './+about/how-it-works/how-it-works.component.ngfactory';
import * as import55 from './+about/welcome/welcome.component.ngfactory';
import * as import56 from './+about/who-we-are/who-we-are.component.ngfactory';
import * as import57 from './+about/press/press.component.ngfactory';
import * as import58 from './auth/components/login/login.component.ngfactory';
import * as import59 from './auth/components/signup/signup.component.ngfactory';
import * as import60 from './+contact/contact.component.ngfactory';
import * as import61 from './+contact/newsletters/newsletters.component.ngfactory';
import * as import62 from './create/create.component.ngfactory';
import * as import63 from './discover/discover.component.ngfactory';
import * as import64 from './+explore/explore.component.ngfactory';
import * as import65 from './+explore/featured/featured.component.ngfactory';
import * as import66 from './+explore/popular/popular.component.ngfactory';
import * as import67 from './+explore/categories/categories.component.ngfactory';
import * as import68 from './+help/help.component.ngfactory';
import * as import69 from './+help/faq/faq.component.ngfactory';
import * as import70 from './+help/support/support.component.ngfactory';
import * as import71 from './+highlights/highlights.component.ngfactory';
import * as import72 from './+jobs/jobs.component.ngfactory';
import * as import73 from './+project/single/single-project.component.ngfactory';
import * as import74 from './+project/single/dashboard/project-dashboard.component.ngfactory';
import * as import75 from './+search/search.component.ngfactory';
import * as import76 from './+settings/settings.component.ngfactory';
import * as import77 from './+team/single/single-team.component.ngfactory';
import * as import78 from './+team/single/dashboard/team-dashboard.component.ngfactory';
import * as import79 from './+terms/terms.component.ngfactory';
import * as import80 from './+terms/use/use.component.ngfactory';
import * as import81 from './+terms/privacy/privacy.component.ngfactory';
import * as import82 from './+terms/cookies/cookies.component.ngfactory';
import * as import83 from './+trending/trending.component.ngfactory';
import * as import84 from './+trending/users/trending-users.component.ngfactory';
import * as import85 from './+trending/teams/trending-teams.component.ngfactory';
import * as import86 from './+user/single/single-user.component.ngfactory';
import * as import87 from './+404/404.component.ngfactory';
import * as import88 from './app.component.ngfactory';
import * as import89 from './+about/about.component';
import * as import90 from './+about/how-it-works/how-it-works.component';
import * as import91 from './+about/welcome/welcome.component';
import * as import92 from './+about/who-we-are/who-we-are.component';
import * as import93 from './+about/press/press.component';
import * as import94 from './auth/components/login/login.component';
import * as import95 from './auth/components/signup/signup.component';
import * as import96 from './+contact/contact.component';
import * as import97 from './+contact/newsletters/newsletters.component';
import * as import98 from './create/create.component';
import * as import99 from './discover/discover.component';
import * as import100 from './+explore/explore.component';
import * as import101 from './+explore/featured/featured.component';
import * as import102 from './+explore/popular/popular.component';
import * as import103 from './+explore/categories/categories.component';
import * as import104 from './+help/help.component';
import * as import105 from './+help/faq/faq.component';
import * as import106 from './+help/support/support.component';
import * as import107 from './+highlights/highlights.component';
import * as import108 from './+jobs/jobs.component';
import * as import109 from './+project/single/single-project.component';
import * as import110 from './+project/single/dashboard/project-dashboard.component';
import * as import111 from './+search/search.component';
import * as import112 from './+settings/settings.component';
import * as import113 from './+team/single/single-team.component';
import * as import114 from './+team/single/dashboard/team-dashboard.component';
import * as import115 from './+terms/terms.component';
import * as import116 from './+terms/use/use.component';
import * as import117 from './+terms/privacy/privacy.component';
import * as import118 from './+terms/cookies/cookies.component';
import * as import119 from './+trending/trending.component';
import * as import120 from './+trending/users/trending-users.component';
import * as import121 from './+trending/teams/trending-teams.component';
import * as import122 from './+user/single/single-user.component';
import * as import123 from './+404/404.component';
import * as import124 from 'angular2-cookie/services/base-cookie-options';
import * as import125 from './apollo.browser';
import * as import126 from 'apollo-angular/build/src/Apollo';
import * as import127 from './auth/reducers/auth.reducers';
import * as import128 from '@angular/http';
import * as import129 from '../modules/transfer-state/transfer-state';
import * as import130 from 'apollo-angular/build/src/tokens';
import * as import131 from '@ngrx/store/src/reducer';
import * as import132 from '@ngrx/store/src/state';
import * as import133 from '@ngrx/store/src/store';
import * as import134 from './auth/services/auth.service';
class BrowserAppModuleInjector extends import0.ɵNgModuleInjector<import1.BrowserAppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import0.ApplicationModule;
  _BrowserModule_2:import3.BrowserModule;
  _BrowserTransferStateModule_3:import4.BrowserTransferStateModule;
  _ɵba_4:import5.ɵba;
  _ReactiveFormsModule_5:import5.ReactiveFormsModule;
  _ɵa_6:any;
  _RouterModule_7:import6.RouterModule;
  _ApolloModule_8:import7.ApolloModule;
  _SharedComponentsModule_9:import8.SharedComponentsModule;
  _SharedModule_10:import9.SharedModule;
  _AboutRoutingModule_11:import10.AboutRoutingModule;
  _AboutModule_12:import11.AboutModule;
  _AuthRoutingModule_13:import12.AuthRoutingModule;
  _AuthModule_14:import13.AuthModule;
  _ContactRoutingModule_15:import14.ContactRoutingModule;
  _ContactModule_16:import15.ContactModule;
  _CreateRoutingModule_17:import16.CreateRoutingModule;
  _CreateModule_18:import17.CreateModule;
  _DiscoverRoutingModule_19:import18.DiscoverRoutingModule;
  _DiscoverModule_20:import19.DiscoverModule;
  _ExploreRoutingModule_21:import20.ExploreRoutingModule;
  _ExploreModule_22:import21.ExploreModule;
  _HelpRoutingModule_23:import22.HelpRoutingModule;
  _HelpModule_24:import23.HelpModule;
  _HighlightsRoutingModule_25:import24.HighlightsRoutingModule;
  _HighlightsModule_26:import25.HighlightsModule;
  _JobsRoutingModule_27:import26.JobsRoutingModule;
  _JobsModule_28:import27.JobsModule;
  _ProjectRoutingModule_29:import28.ProjectRoutingModule;
  _ProjectModule_30:import29.ProjectModule;
  _SearchRoutingModule_31:import30.SearchRoutingModule;
  _SearchModule_32:import31.SearchModule;
  _SettingsRoutingModule_33:import32.SettingsRoutingModule;
  _SettingsModule_34:import33.SettingsModule;
  _TeamRoutingModule_35:import34.TeamRoutingModule;
  _TeamModule_36:import35.TeamModule;
  _TermsRoutingModule_37:import36.TermsRoutingModule;
  _TermsModule_38:import37.TermsModule;
  _TrendingRoutingModule_39:import38.TrendingRoutingModule;
  _TrendingModule_40:import39.TrendingModule;
  _UserRoutingModule_41:import40.UserRoutingModule;
  _UserModule_42:import41.UserModule;
  _AppRoutingModule_43:import42.AppRoutingModule;
  _NotFoundRoutingModule_44:import43.NotFoundRoutingModule;
  _StoreModule_45:import44.StoreModule;
  _AppModule_46:import45.AppModule;
  _BrowserAppModule_47:import1.BrowserAppModule;
  __LOCALE_ID_48:any;
  __NgLocalization_49:import2.NgLocaleLocalization;
  _ErrorHandler_50:import1.RavenErrorHandler;
  _NgProbeToken_51:any[];
  _APP_ID_52:any;
  _ɵTRANSITION_ID_53:any;
  _APP_INITIALIZER_54:any[];
  _ApplicationInitStatus_55:import0.ApplicationInitStatus;
  _ɵf_56:import0.ɵf;
  __ApplicationRef_57:any;
  __Compiler_58:import0.Compiler;
  __IterableDiffers_59:any;
  __KeyValueDiffers_60:any;
  __DomSanitizer_61:import3.ɵe;
  __Sanitizer_62:any;
  __HAMMER_GESTURE_CONFIG_63:import3.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_64:any[];
  __EventManager_65:import3.EventManager;
  _ɵDomSharedStylesHost_66:import3.ɵDomSharedStylesHost;
  __ɵDomRendererFactoryV2_67:import3.ɵDomRendererFactoryV2;
  __RendererFactoryV2_68:any;
  __ɵSharedStylesHost_69:any;
  __Testability_70:import0.Testability;
  __Meta_71:import3.Meta;
  __Title_72:import3.Title;
  __TransferState_73:any;
  __FormBuilder_74:import5.FormBuilder;
  __ɵi_75:import5.ɵi;
  __ROUTES_76:any[];
  __CookieService_77:import46.CookieService;
  __isServer_78:any;
  __CLIENT_MAP_WRAPPER_79:any;
  __CLIENT_MAP_80:any;
  __Apollo_81:any;
  __LRU_82:any;
  __CacheService_83:import47.CacheService;
  __Dispatcher_84:import48.Dispatcher;
  ___INITIAL_REDUCER_85:any;
  __INITIAL_REDUCER_86:any;
  __Reducer_87:any;
  ___INITIAL_STATE_88:any;
  __INITIAL_STATE_89:any;
  __State_90:any;
  __Store_91:any;
  __HashService_92:import49.HashService;
  __ApiService_93:import50.ApiService;
  __AUTH_SERVICE_94:any;
  __AuthModelService_95:import51.AuthModelService;
  __APP_BASE_HREF_96:any;
  __ROUTER_CONFIGURATION_97:any;
  __LocationStrategy_98:any;
  __Location_99:import2.Location;
  __UrlSerializer_100:import6.DefaultUrlSerializer;
  __RouterOutletMap_101:import6.RouterOutletMap;
  __NgModuleFactoryLoader_102:import0.SystemJsNgModuleLoader;
  __Router_103:any;
  __ActivatedRoute_104:any;
  _NoPreloading_105:import6.NoPreloading;
  _PreloadingStrategy_106:any;
  _RouterPreloader_107:import6.RouterPreloader;
  __PreloadAllModules_108:import6.PreloadAllModules;
  __ROUTER_INITIALIZER_109:any;
  __APP_BOOTSTRAP_LISTENER_110:any[];
  __isBrowser_111:any;
  __MetaService_112:import52.MetaService;
  constructor(parent:import0.Injector) {
    super(parent,[
      import53.AboutComponentNgFactory,
      import54.HowItWorksComponentNgFactory,
      import55.WelcomeComponentNgFactory,
      import56.WhoWeAreComponentNgFactory,
      import57.PressComponentNgFactory,
      import58.LoginComponentNgFactory,
      import59.SignupComponentNgFactory,
      import60.ContactComponentNgFactory,
      import61.NewslettersComponentNgFactory,
      import62.CreateComponentNgFactory,
      import63.DiscoverComponentNgFactory,
      import64.ExploreComponentNgFactory,
      import65.FeaturedComponentNgFactory,
      import66.PopularComponentNgFactory,
      import67.CategoriesComponentNgFactory,
      import68.HelpComponentNgFactory,
      import69.FaqComponentNgFactory,
      import70.SupportComponentNgFactory,
      import71.HighlightsComponentNgFactory,
      import72.JobsComponentNgFactory,
      import73.SingleProjectComponentNgFactory,
      import74.ProjectDashboardComponentNgFactory,
      import75.SearchComponentNgFactory,
      import76.SettingsComponentNgFactory,
      import77.SingleTeamComponentNgFactory,
      import78.TeamDashboardComponentNgFactory,
      import79.TermsComponentNgFactory,
      import80.UseComponentNgFactory,
      import81.PrivacyComponentNgFactory,
      import82.CookiesComponentNgFactory,
      import83.TrendingComponentNgFactory,
      import84.TrendingUsersComponentNgFactory,
      import85.TrendingTeamsComponentNgFactory,
      import86.SingleUserComponentNgFactory,
      import87.NotFoundComponentNgFactory,
      import88.AppComponentNgFactory
    ]
    ,[import88.AppComponentNgFactory]);
  }
  get _LOCALE_ID_48():any {
    if ((this.__LOCALE_ID_48 == null)) { (this.__LOCALE_ID_48 = import0.ɵo(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_48;
  }
  get _NgLocalization_49():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_49 == null)) { (this.__NgLocalization_49 = new import2.NgLocaleLocalization(this._LOCALE_ID_48)); }
    return this.__NgLocalization_49;
  }
  get _ApplicationRef_57():any {
    if ((this.__ApplicationRef_57 == null)) { (this.__ApplicationRef_57 = this._ɵf_56); }
    return this.__ApplicationRef_57;
  }
  get _Compiler_58():import0.Compiler {
    if ((this.__Compiler_58 == null)) { (this.__Compiler_58 = new import0.Compiler()); }
    return this.__Compiler_58;
  }
  get _IterableDiffers_59():any {
    if ((this.__IterableDiffers_59 == null)) { (this.__IterableDiffers_59 = import0.ɵm()); }
    return this.__IterableDiffers_59;
  }
  get _KeyValueDiffers_60():any {
    if ((this.__KeyValueDiffers_60 == null)) { (this.__KeyValueDiffers_60 = import0.ɵn()); }
    return this.__KeyValueDiffers_60;
  }
  get _DomSanitizer_61():import3.ɵe {
    if ((this.__DomSanitizer_61 == null)) { (this.__DomSanitizer_61 = new import3.ɵe(this.parent.get(import3.DOCUMENT))); }
    return this.__DomSanitizer_61;
  }
  get _Sanitizer_62():any {
    if ((this.__Sanitizer_62 == null)) { (this.__Sanitizer_62 = this._DomSanitizer_61); }
    return this.__Sanitizer_62;
  }
  get _HAMMER_GESTURE_CONFIG_63():import3.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_63 == null)) { (this.__HAMMER_GESTURE_CONFIG_63 = new import3.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_63;
  }
  get _EVENT_MANAGER_PLUGINS_64():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_64 == null)) { (this.__EVENT_MANAGER_PLUGINS_64 = [
      new import3.ɵDomEventsPlugin(this.parent.get(import3.DOCUMENT)),
      new import3.ɵKeyEventsPlugin(this.parent.get(import3.DOCUMENT)),
      new import3.ɵHammerGesturesPlugin(this.parent.get(import3.DOCUMENT),this._HAMMER_GESTURE_CONFIG_63)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_64;
  }
  get _EventManager_65():import3.EventManager {
    if ((this.__EventManager_65 == null)) { (this.__EventManager_65 = new import3.EventManager(this._EVENT_MANAGER_PLUGINS_64,this.parent.get(import0.NgZone))); }
    return this.__EventManager_65;
  }
  get _ɵDomRendererFactoryV2_67():import3.ɵDomRendererFactoryV2 {
    if ((this.__ɵDomRendererFactoryV2_67 == null)) { (this.__ɵDomRendererFactoryV2_67 = new import3.ɵDomRendererFactoryV2(this._EventManager_65,this._ɵDomSharedStylesHost_66)); }
    return this.__ɵDomRendererFactoryV2_67;
  }
  get _RendererFactoryV2_68():any {
    if ((this.__RendererFactoryV2_68 == null)) { (this.__RendererFactoryV2_68 = this._ɵDomRendererFactoryV2_67); }
    return this.__RendererFactoryV2_68;
  }
  get _ɵSharedStylesHost_69():any {
    if ((this.__ɵSharedStylesHost_69 == null)) { (this.__ɵSharedStylesHost_69 = this._ɵDomSharedStylesHost_66); }
    return this.__ɵSharedStylesHost_69;
  }
  get _Testability_70():import0.Testability {
    if ((this.__Testability_70 == null)) { (this.__Testability_70 = new import0.Testability(this.parent.get(import0.NgZone))); }
    return this.__Testability_70;
  }
  get _Meta_71():import3.Meta {
    if ((this.__Meta_71 == null)) { (this.__Meta_71 = new import3.Meta(this.parent.get(import3.DOCUMENT))); }
    return this.__Meta_71;
  }
  get _Title_72():import3.Title {
    if ((this.__Title_72 == null)) { (this.__Title_72 = new import3.Title(this.parent.get(import3.DOCUMENT))); }
    return this.__Title_72;
  }
  get _TransferState_73():any {
    if ((this.__TransferState_73 == null)) { (this.__TransferState_73 = import4.getTransferState()); }
    return this.__TransferState_73;
  }
  get _FormBuilder_74():import5.FormBuilder {
    if ((this.__FormBuilder_74 == null)) { (this.__FormBuilder_74 = new import5.FormBuilder()); }
    return this.__FormBuilder_74;
  }
  get _ɵi_75():import5.ɵi {
    if ((this.__ɵi_75 == null)) { (this.__ɵi_75 = new import5.ɵi()); }
    return this.__ɵi_75;
  }
  get _ROUTES_76():any[] {
    if ((this.__ROUTES_76 == null)) { (this.__ROUTES_76 = [
      [
        {
          path: 'about',
          component: import89.AboutComponent
        }
        ,
        {
          path: 'about/how-it-works',
          component: import90.HowItWorksComponent
        }
        ,
        {
          path: 'about/welcome',
          component: import91.WelcomeComponent
        }
        ,
        {
          path: 'about/who-we-are',
          component: import92.WhoWeAreComponent
        }
        ,
        {
          path: 'about/press',
          component: import93.PressComponent
        }

      ]
      ,
      [
        {
          path: 'login',
          component: import94.LoginComponent
        }
        ,
        {
          path: 'signup',
          component: import95.SignupComponent
        }

      ]
      ,
      [
        {
          path: 'contact',
          component: import96.ContactComponent
        }
        ,
        {
          path: 'newsletters',
          component: import97.NewslettersComponent
        }

      ]
      ,
        [{
          path: 'create',
          component: import98.CreateComponent
        }
      ],
        [{
          path: 'discover',
          component: import99.DiscoverComponent
        }
      ],
      [
        {
          path: 'explore',
          component: import100.ExploreComponent
        }
        ,
        {
          path: 'explore/featured',
          component: import101.FeaturedComponent
        }
        ,
        {
          path: 'explore/popular',
          component: import102.PopularComponent
        }
        ,
        {
          path: 'explore/categories',
          component: import103.CategoriesComponent
        }

      ]
      ,
      [
        {
          path: 'help',
          component: import104.HelpComponent
        }
        ,
        {
          path: 'help/faq',
          component: import105.FaqComponent
        }
        ,
        {
          path: 'help/support',
          component: import106.SupportComponent
        }

      ]
      ,
        [{
          path: 'highlights',
          component: import107.HighlightsComponent
        }
      ],
        [{
          path: 'jobs',
          component: import108.JobsComponent
        }
      ],
      [
        {
          path: 'project/:slug',
          component: import109.SingleProjectComponent
        }
        ,
        {
          path: 'project/:slug/dashboard',
          component: import110.ProjectDashboardComponent
        }
        ,
        {
          path: 'project/:slug/dashboard/applications',
          component: import110.ProjectDashboardComponent
        }
        ,
        {
          path: 'project/:slug/dashboard/application/:application_id',
          component: import110.ProjectDashboardComponent
        }

      ]
      ,
        [{
          path: 'search',
          component: import111.SearchComponent
        }
      ],
        [{
          path: 'settings',
          component: import112.SettingsComponent
        }
      ],
      [
        {
          path: 'team/:slug',
          component: import113.SingleTeamComponent
        }
        ,
        {
          path: 'team/:slug/dashboard',
          component: import114.TeamDashboardComponent
        }

      ]
      ,
      [
        {
          path: 'terms',
          component: import115.TermsComponent
        }
        ,
        {
          path: 'terms/use',
          component: import116.UseComponent
        }
        ,
        {
          path: 'terms/privacy',
          component: import117.PrivacyComponent
        }
        ,
        {
          path: 'terms/cookies',
          component: import118.CookiesComponent
        }

      ]
      ,
      [
        {
          path: 'trending',
          component: import119.TrendingComponent
        }
        ,
        {
          path: 'trending/users',
          component: import120.TrendingUsersComponent
        }
        ,
        {
          path: 'trending/teams',
          component: import121.TrendingTeamsComponent
        }

      ]
      ,
        [{
          path: 'user/:slug',
          component: import122.SingleUserComponent
        }
      ],
        [{
          path: '',
          redirectTo: '/discover',
          pathMatch: 'full'
        }
      ],
      [
        {
          path: '404',
          component: import123.NotFoundComponent
        }
        ,
        {
          path: '**',
          redirectTo: '/404'
        }

      ]
      ,
      ([] as any[])
    ]
    ); }
    return this.__ROUTES_76;
  }
  get _CookieService_77():import46.CookieService {
    if ((this.__CookieService_77 == null)) { (this.__CookieService_77 = new import46.CookieService(this.parent.get(import124.CookieOptions))); }
    return this.__CookieService_77;
  }
  get _isServer_78():any {
    if ((this.__isServer_78 == null)) { (this.__isServer_78 = false); }
    return this.__isServer_78;
  }
  get _CLIENT_MAP_WRAPPER_79():any {
    if ((this.__CLIENT_MAP_WRAPPER_79 == null)) { (this.__CLIENT_MAP_WRAPPER_79 = import125.provideClient); }
    return this.__CLIENT_MAP_WRAPPER_79;
  }
  get _CLIENT_MAP_80():any {
    if ((this.__CLIENT_MAP_80 == null)) { (this.__CLIENT_MAP_80 = import126.getClientMap(this._CLIENT_MAP_WRAPPER_79)); }
    return this.__CLIENT_MAP_80;
  }
  get _Apollo_81():any {
    if ((this.__Apollo_81 == null)) { (this.__Apollo_81 = import126.createApollo(this._CLIENT_MAP_80)); }
    return this.__Apollo_81;
  }
  get _LRU_82():any {
    if ((this.__LRU_82 == null)) { (this.__LRU_82 = import1.getBrowserLRU()); }
    return this.__LRU_82;
  }
  get _CacheService_83():import47.CacheService {
    if ((this.__CacheService_83 == null)) { (this.__CacheService_83 = new import47.CacheService(this._LRU_82)); }
    return this.__CacheService_83;
  }
  get _Dispatcher_84():import48.Dispatcher {
    if ((this.__Dispatcher_84 == null)) { (this.__Dispatcher_84 = new import48.Dispatcher()); }
    return this.__Dispatcher_84;
  }
  get __INITIAL_REDUCER_85():any {
    if ((this.___INITIAL_REDUCER_85 == null)) { (this.___INITIAL_REDUCER_85 = {auth: import127.authReducer}); }
    return this.___INITIAL_REDUCER_85;
  }
  get _INITIAL_REDUCER_86():any {
    if ((this.__INITIAL_REDUCER_86 == null)) { (this.__INITIAL_REDUCER_86 = import44._initialReducerFactory(this.__INITIAL_REDUCER_85)); }
    return this.__INITIAL_REDUCER_86;
  }
  get _Reducer_87():any {
    if ((this.__Reducer_87 == null)) { (this.__Reducer_87 = import44._reducerFactory(this._Dispatcher_84,this._INITIAL_REDUCER_86)); }
    return this.__Reducer_87;
  }
  get __INITIAL_STATE_88():any {
    if ((this.___INITIAL_STATE_88 == null)) { (this.___INITIAL_STATE_88 = (undefined as any)); }
    return this.___INITIAL_STATE_88;
  }
  get _INITIAL_STATE_89():any {
    if ((this.__INITIAL_STATE_89 == null)) { (this.__INITIAL_STATE_89 = import44._initialStateFactory(this.__INITIAL_STATE_88,this._INITIAL_REDUCER_86)); }
    return this.__INITIAL_STATE_89;
  }
  get _State_90():any {
    if ((this.__State_90 == null)) { (this.__State_90 = import44._stateFactory(this._INITIAL_STATE_89,this._Dispatcher_84,this._Reducer_87)); }
    return this.__State_90;
  }
  get _Store_91():any {
    if ((this.__Store_91 == null)) { (this.__Store_91 = import44._storeFactory(this._Dispatcher_84,this._Reducer_87,this._State_90)); }
    return this.__Store_91;
  }
  get _HashService_92():import49.HashService {
    if ((this.__HashService_92 == null)) { (this.__HashService_92 = new import49.HashService()); }
    return this.__HashService_92;
  }
  get _ApiService_93():import50.ApiService {
    if ((this.__ApiService_93 == null)) { (this.__ApiService_93 = new import50.ApiService(this._isServer_78,this._Apollo_81,this._CacheService_83,this._Store_91,this._HashService_92)); }
    return this.__ApiService_93;
  }
  get _AUTH_SERVICE_94():any {
    if ((this.__AUTH_SERVICE_94 == null)) { (this.__AUTH_SERVICE_94 = import1.browserAuthServiceFactory(this._CookieService_77,this._ApiService_93,this.parent.get(import128.Http))); }
    return this.__AUTH_SERVICE_94;
  }
  get _AuthModelService_95():import51.AuthModelService {
    if ((this.__AuthModelService_95 == null)) { (this.__AuthModelService_95 = new import51.AuthModelService(this._AUTH_SERVICE_94,this._Store_91)); }
    return this.__AuthModelService_95;
  }
  get _APP_BASE_HREF_96():any {
    if ((this.__APP_BASE_HREF_96 == null)) { (this.__APP_BASE_HREF_96 = '/'); }
    return this.__APP_BASE_HREF_96;
  }
  get _ROUTER_CONFIGURATION_97():any {
    if ((this.__ROUTER_CONFIGURATION_97 == null)) { (this.__ROUTER_CONFIGURATION_97 = {useHash: false}); }
    return this.__ROUTER_CONFIGURATION_97;
  }
  get _LocationStrategy_98():any {
    if ((this.__LocationStrategy_98 == null)) { (this.__LocationStrategy_98 = import6.ɵc(this.parent.get(import2.PlatformLocation),this._APP_BASE_HREF_96,this._ROUTER_CONFIGURATION_97)); }
    return this.__LocationStrategy_98;
  }
  get _Location_99():import2.Location {
    if ((this.__Location_99 == null)) { (this.__Location_99 = new import2.Location(this._LocationStrategy_98)); }
    return this.__Location_99;
  }
  get _UrlSerializer_100():import6.DefaultUrlSerializer {
    if ((this.__UrlSerializer_100 == null)) { (this.__UrlSerializer_100 = new import6.DefaultUrlSerializer()); }
    return this.__UrlSerializer_100;
  }
  get _RouterOutletMap_101():import6.RouterOutletMap {
    if ((this.__RouterOutletMap_101 == null)) { (this.__RouterOutletMap_101 = new import6.RouterOutletMap()); }
    return this.__RouterOutletMap_101;
  }
  get _NgModuleFactoryLoader_102():import0.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_102 == null)) { (this.__NgModuleFactoryLoader_102 = new import0.SystemJsNgModuleLoader(this._Compiler_58,this.parent.get(import0.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_102;
  }
  get _Router_103():any {
    if ((this.__Router_103 == null)) { (this.__Router_103 = import6.ɵe(this._ApplicationRef_57,this._UrlSerializer_100,this._RouterOutletMap_101,this._Location_99,this,this._NgModuleFactoryLoader_102,this._Compiler_58,this._ROUTES_76,this._ROUTER_CONFIGURATION_97,this.parent.get(import6.UrlHandlingStrategy,(null as any)),this.parent.get(import6.RouteReuseStrategy,(null as any)))); }
    return this.__Router_103;
  }
  get _ActivatedRoute_104():any {
    if ((this.__ActivatedRoute_104 == null)) { (this.__ActivatedRoute_104 = import6.ɵf(this._Router_103)); }
    return this.__ActivatedRoute_104;
  }
  get _PreloadAllModules_108():import6.PreloadAllModules {
    if ((this.__PreloadAllModules_108 == null)) { (this.__PreloadAllModules_108 = new import6.PreloadAllModules()); }
    return this.__PreloadAllModules_108;
  }
  get _ROUTER_INITIALIZER_109():any {
    if ((this.__ROUTER_INITIALIZER_109 == null)) { (this.__ROUTER_INITIALIZER_109 = import6.ɵg(this._Router_103,this._ApplicationRef_57,this._RouterPreloader_107,this._ROUTER_CONFIGURATION_97)); }
    return this.__ROUTER_INITIALIZER_109;
  }
  get _APP_BOOTSTRAP_LISTENER_110():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_110 == null)) { (this.__APP_BOOTSTRAP_LISTENER_110 = [this._ROUTER_INITIALIZER_109]); }
    return this.__APP_BOOTSTRAP_LISTENER_110;
  }
  get _isBrowser_111():any {
    if ((this.__isBrowser_111 == null)) { (this.__isBrowser_111 = true); }
    return this.__isBrowser_111;
  }
  get _MetaService_112():import52.MetaService {
    if ((this.__MetaService_112 == null)) { (this.__MetaService_112 = new import52.MetaService(this._isServer_78,this._Title_72,this._Meta_71)); }
    return this.__MetaService_112;
  }
  createInternal():import1.BrowserAppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import0.ApplicationModule();
    this._BrowserModule_2 = new import3.BrowserModule(this.parent.get(import3.BrowserModule,(null as any)));
    this._BrowserTransferStateModule_3 = new import4.BrowserTransferStateModule();
    this._ɵba_4 = new import5.ɵba();
    this._ReactiveFormsModule_5 = new import5.ReactiveFormsModule();
    this._ɵa_6 = import6.ɵd(this.parent.get(import6.Router,(null as any)));
    this._RouterModule_7 = new import6.RouterModule(this._ɵa_6);
    this._ApolloModule_8 = new import7.ApolloModule();
    this._SharedComponentsModule_9 = new import8.SharedComponentsModule();
    this._SharedModule_10 = new import9.SharedModule();
    this._AboutRoutingModule_11 = new import10.AboutRoutingModule();
    this._AboutModule_12 = new import11.AboutModule();
    this._AuthRoutingModule_13 = new import12.AuthRoutingModule();
    this._AuthModule_14 = new import13.AuthModule();
    this._ContactRoutingModule_15 = new import14.ContactRoutingModule();
    this._ContactModule_16 = new import15.ContactModule();
    this._CreateRoutingModule_17 = new import16.CreateRoutingModule();
    this._CreateModule_18 = new import17.CreateModule();
    this._DiscoverRoutingModule_19 = new import18.DiscoverRoutingModule();
    this._DiscoverModule_20 = new import19.DiscoverModule();
    this._ExploreRoutingModule_21 = new import20.ExploreRoutingModule();
    this._ExploreModule_22 = new import21.ExploreModule();
    this._HelpRoutingModule_23 = new import22.HelpRoutingModule();
    this._HelpModule_24 = new import23.HelpModule();
    this._HighlightsRoutingModule_25 = new import24.HighlightsRoutingModule();
    this._HighlightsModule_26 = new import25.HighlightsModule();
    this._JobsRoutingModule_27 = new import26.JobsRoutingModule();
    this._JobsModule_28 = new import27.JobsModule();
    this._ProjectRoutingModule_29 = new import28.ProjectRoutingModule();
    this._ProjectModule_30 = new import29.ProjectModule();
    this._SearchRoutingModule_31 = new import30.SearchRoutingModule();
    this._SearchModule_32 = new import31.SearchModule();
    this._SettingsRoutingModule_33 = new import32.SettingsRoutingModule();
    this._SettingsModule_34 = new import33.SettingsModule();
    this._TeamRoutingModule_35 = new import34.TeamRoutingModule();
    this._TeamModule_36 = new import35.TeamModule();
    this._TermsRoutingModule_37 = new import36.TermsRoutingModule();
    this._TermsModule_38 = new import37.TermsModule();
    this._TrendingRoutingModule_39 = new import38.TrendingRoutingModule();
    this._TrendingModule_40 = new import39.TrendingModule();
    this._UserRoutingModule_41 = new import40.UserRoutingModule();
    this._UserModule_42 = new import41.UserModule();
    this._AppRoutingModule_43 = new import42.AppRoutingModule();
    this._NotFoundRoutingModule_44 = new import43.NotFoundRoutingModule();
    this._StoreModule_45 = new import44.StoreModule();
    this._AppModule_46 = new import45.AppModule();
    this._BrowserAppModule_47 = new import1.BrowserAppModule();
    this._ErrorHandler_50 = new import1.RavenErrorHandler();
    this._NgProbeToken_51 = [import6.ɵb()];
    this._APP_ID_52 = 'root-app';
    this._ɵTRANSITION_ID_53 = this._APP_ID_52;
    this._APP_INITIALIZER_54 = [
      import0.ɵp,
      import3.ɵc(this.parent.get(import3.NgProbeToken,(null as any)),this._NgProbeToken_51),
      import3.ɵf(this._ɵTRANSITION_ID_53,this.parent.get(import3.DOCUMENT))
    ]
    ;
    this._ApplicationInitStatus_55 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_54);
    this._ɵf_56 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_50,this,this._ApplicationInitStatus_55);
    this._ɵDomSharedStylesHost_66 = new import3.ɵDomSharedStylesHost(this.parent.get(import3.DOCUMENT));
    this._NoPreloading_105 = new import6.NoPreloading();
    this._PreloadingStrategy_106 = this._NoPreloading_105;
    this._RouterPreloader_107 = new import6.RouterPreloader(this._Router_103,this._NgModuleFactoryLoader_102,this._Compiler_58,this,this._PreloadingStrategy_106);
    return this._BrowserAppModule_47;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import3.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import4.BrowserTransferStateModule)) { return this._BrowserTransferStateModule_3; }
    if ((token === import5.ɵba)) { return this._ɵba_4; }
    if ((token === import5.ReactiveFormsModule)) { return this._ReactiveFormsModule_5; }
    if ((token === import6.ɵa)) { return this._ɵa_6; }
    if ((token === import6.RouterModule)) { return this._RouterModule_7; }
    if ((token === import7.ApolloModule)) { return this._ApolloModule_8; }
    if ((token === import8.SharedComponentsModule)) { return this._SharedComponentsModule_9; }
    if ((token === import9.SharedModule)) { return this._SharedModule_10; }
    if ((token === import10.AboutRoutingModule)) { return this._AboutRoutingModule_11; }
    if ((token === import11.AboutModule)) { return this._AboutModule_12; }
    if ((token === import12.AuthRoutingModule)) { return this._AuthRoutingModule_13; }
    if ((token === import13.AuthModule)) { return this._AuthModule_14; }
    if ((token === import14.ContactRoutingModule)) { return this._ContactRoutingModule_15; }
    if ((token === import15.ContactModule)) { return this._ContactModule_16; }
    if ((token === import16.CreateRoutingModule)) { return this._CreateRoutingModule_17; }
    if ((token === import17.CreateModule)) { return this._CreateModule_18; }
    if ((token === import18.DiscoverRoutingModule)) { return this._DiscoverRoutingModule_19; }
    if ((token === import19.DiscoverModule)) { return this._DiscoverModule_20; }
    if ((token === import20.ExploreRoutingModule)) { return this._ExploreRoutingModule_21; }
    if ((token === import21.ExploreModule)) { return this._ExploreModule_22; }
    if ((token === import22.HelpRoutingModule)) { return this._HelpRoutingModule_23; }
    if ((token === import23.HelpModule)) { return this._HelpModule_24; }
    if ((token === import24.HighlightsRoutingModule)) { return this._HighlightsRoutingModule_25; }
    if ((token === import25.HighlightsModule)) { return this._HighlightsModule_26; }
    if ((token === import26.JobsRoutingModule)) { return this._JobsRoutingModule_27; }
    if ((token === import27.JobsModule)) { return this._JobsModule_28; }
    if ((token === import28.ProjectRoutingModule)) { return this._ProjectRoutingModule_29; }
    if ((token === import29.ProjectModule)) { return this._ProjectModule_30; }
    if ((token === import30.SearchRoutingModule)) { return this._SearchRoutingModule_31; }
    if ((token === import31.SearchModule)) { return this._SearchModule_32; }
    if ((token === import32.SettingsRoutingModule)) { return this._SettingsRoutingModule_33; }
    if ((token === import33.SettingsModule)) { return this._SettingsModule_34; }
    if ((token === import34.TeamRoutingModule)) { return this._TeamRoutingModule_35; }
    if ((token === import35.TeamModule)) { return this._TeamModule_36; }
    if ((token === import36.TermsRoutingModule)) { return this._TermsRoutingModule_37; }
    if ((token === import37.TermsModule)) { return this._TermsModule_38; }
    if ((token === import38.TrendingRoutingModule)) { return this._TrendingRoutingModule_39; }
    if ((token === import39.TrendingModule)) { return this._TrendingModule_40; }
    if ((token === import40.UserRoutingModule)) { return this._UserRoutingModule_41; }
    if ((token === import41.UserModule)) { return this._UserModule_42; }
    if ((token === import42.AppRoutingModule)) { return this._AppRoutingModule_43; }
    if ((token === import43.NotFoundRoutingModule)) { return this._NotFoundRoutingModule_44; }
    if ((token === import44.StoreModule)) { return this._StoreModule_45; }
    if ((token === import45.AppModule)) { return this._AppModule_46; }
    if ((token === import1.BrowserAppModule)) { return this._BrowserAppModule_47; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_48; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_49; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_50; }
    if ((token === import0.NgProbeToken)) { return this._NgProbeToken_51; }
    if ((token === import0.APP_ID)) { return this._APP_ID_52; }
    if ((token === import3.ɵTRANSITION_ID)) { return this._ɵTRANSITION_ID_53; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_54; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_55; }
    if ((token === import0.ɵf)) { return this._ɵf_56; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_57; }
    if ((token === import0.Compiler)) { return this._Compiler_58; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_59; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_60; }
    if ((token === import3.DomSanitizer)) { return this._DomSanitizer_61; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_62; }
    if ((token === import3.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_63; }
    if ((token === import3.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_64; }
    if ((token === import3.EventManager)) { return this._EventManager_65; }
    if ((token === import3.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_66; }
    if ((token === import3.ɵDomRendererFactoryV2)) { return this._ɵDomRendererFactoryV2_67; }
    if ((token === import0.RendererFactoryV2)) { return this._RendererFactoryV2_68; }
    if ((token === import3.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_69; }
    if ((token === import0.Testability)) { return this._Testability_70; }
    if ((token === import3.Meta)) { return this._Meta_71; }
    if ((token === import3.Title)) { return this._Title_72; }
    if ((token === import129.TransferState)) { return this._TransferState_73; }
    if ((token === import5.FormBuilder)) { return this._FormBuilder_74; }
    if ((token === import5.ɵi)) { return this._ɵi_75; }
    if ((token === import6.ROUTES)) { return this._ROUTES_76; }
    if ((token === import46.CookieService)) { return this._CookieService_77; }
    if ((token === 'isServer')) { return this._isServer_78; }
    if ((token === import130.CLIENT_MAP_WRAPPER)) { return this._CLIENT_MAP_WRAPPER_79; }
    if ((token === import130.CLIENT_MAP)) { return this._CLIENT_MAP_80; }
    if ((token === import126.Apollo)) { return this._Apollo_81; }
    if ((token === 'LRU')) { return this._LRU_82; }
    if ((token === import47.CacheService)) { return this._CacheService_83; }
    if ((token === import48.Dispatcher)) { return this._Dispatcher_84; }
    if ((token === import44._INITIAL_REDUCER)) { return this.__INITIAL_REDUCER_85; }
    if ((token === import44.INITIAL_REDUCER)) { return this._INITIAL_REDUCER_86; }
    if ((token === import131.Reducer)) { return this._Reducer_87; }
    if ((token === import44._INITIAL_STATE)) { return this.__INITIAL_STATE_88; }
    if ((token === import44.INITIAL_STATE)) { return this._INITIAL_STATE_89; }
    if ((token === import132.State)) { return this._State_90; }
    if ((token === import133.Store)) { return this._Store_91; }
    if ((token === import49.HashService)) { return this._HashService_92; }
    if ((token === import50.ApiService)) { return this._ApiService_93; }
    if ((token === import134.AUTH_SERVICE)) { return this._AUTH_SERVICE_94; }
    if ((token === import51.AuthModelService)) { return this._AuthModelService_95; }
    if ((token === import2.APP_BASE_HREF)) { return this._APP_BASE_HREF_96; }
    if ((token === import6.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_97; }
    if ((token === import2.LocationStrategy)) { return this._LocationStrategy_98; }
    if ((token === import2.Location)) { return this._Location_99; }
    if ((token === import6.UrlSerializer)) { return this._UrlSerializer_100; }
    if ((token === import6.RouterOutletMap)) { return this._RouterOutletMap_101; }
    if ((token === import0.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_102; }
    if ((token === import6.Router)) { return this._Router_103; }
    if ((token === import6.ActivatedRoute)) { return this._ActivatedRoute_104; }
    if ((token === import6.NoPreloading)) { return this._NoPreloading_105; }
    if ((token === import6.PreloadingStrategy)) { return this._PreloadingStrategy_106; }
    if ((token === import6.RouterPreloader)) { return this._RouterPreloader_107; }
    if ((token === import6.PreloadAllModules)) { return this._PreloadAllModules_108; }
    if ((token === import6.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_109; }
    if ((token === import0.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_110; }
    if ((token === 'isBrowser')) { return this._isBrowser_111; }
    if ((token === import52.MetaService)) { return this._MetaService_112; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_56.ngOnDestroy();
    this._ɵDomSharedStylesHost_66.ngOnDestroy();
    this._RouterPreloader_107.ngOnDestroy();
  }
}
export const BrowserAppModuleNgFactory:import0.NgModuleFactory<import1.BrowserAppModule> = new import0.NgModuleFactory<any>(BrowserAppModuleInjector,import1.BrowserAppModule);