/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './app.server.module';
import * as import2 from '@angular/http';
import * as import3 from '@angular/common';
import * as import4 from '@angular/platform-browser';
import * as import5 from '@angular/platform-server';
import * as import6 from '../modules/transfer-state/server-transfer-state.module';
import * as import7 from '@angular/forms';
import * as import8 from '@angular/router';
import * as import9 from 'apollo-angular/build/src/ApolloModule';
import * as import10 from './shared/components/components.module';
import * as import11 from './shared/shared.module';
import * as import12 from './+about/about-routing.module';
import * as import13 from './+about/about.module';
import * as import14 from './auth/modules/auth-routing.module';
import * as import15 from './auth/modules/auth.module';
import * as import16 from './+contact/contact-routing.module';
import * as import17 from './+contact/contact.module';
import * as import18 from './create/create-routing.module';
import * as import19 from './create/create.module';
import * as import20 from './discover/discover-routing.module';
import * as import21 from './discover/discover.module';
import * as import22 from './+explore/explore-routing.module';
import * as import23 from './+explore/explore.module';
import * as import24 from './+help/help-routing.module';
import * as import25 from './+help/help.module';
import * as import26 from './+highlights/highlights-routing.module';
import * as import27 from './+highlights/highlights.module';
import * as import28 from './+jobs/jobs-routing.module';
import * as import29 from './+jobs/jobs.module';
import * as import30 from './+project/project-routing.module';
import * as import31 from './+project/project.module';
import * as import32 from './+search/search-routing.module';
import * as import33 from './+search/search.module';
import * as import34 from './+settings/settings-routing.module';
import * as import35 from './+settings/settings.module';
import * as import36 from './+team/team-routing.module';
import * as import37 from './+team/team.module';
import * as import38 from './+terms/terms-routing.module';
import * as import39 from './+terms/terms.module';
import * as import40 from './+trending/trending-routing.module';
import * as import41 from './+trending/trending.module';
import * as import42 from './+user/user-routing.module';
import * as import43 from './+user/user.module';
import * as import44 from './app-routing.module';
import * as import45 from './+404/404-routing.module';
import * as import46 from '@ngrx/store/src/ng2';
import * as import47 from './app.module';
import * as import48 from '../modules/transfer-state/transfer-state';
import * as import49 from './shared/services/cache/cache.service';
import * as import50 from '@ngrx/store/src/dispatcher';
import * as import51 from './shared/services/cache/hash.service';
import * as import52 from './shared/services/api/api.service';
import * as import53 from './auth/services/auth.server.service';
import * as import54 from './auth/models/auth.model.service';
import * as import55 from './shared/services/meta/meta.service';
import * as import56 from './+about/about.component.ngfactory';
import * as import57 from './+about/how-it-works/how-it-works.component.ngfactory';
import * as import58 from './+about/welcome/welcome.component.ngfactory';
import * as import59 from './+about/who-we-are/who-we-are.component.ngfactory';
import * as import60 from './+about/press/press.component.ngfactory';
import * as import61 from './auth/components/login/login.component.ngfactory';
import * as import62 from './auth/components/signup/signup.component.ngfactory';
import * as import63 from './+contact/contact.component.ngfactory';
import * as import64 from './+contact/newsletters/newsletters.component.ngfactory';
import * as import65 from './create/create.component.ngfactory';
import * as import66 from './discover/discover.component.ngfactory';
import * as import67 from './+explore/explore.component.ngfactory';
import * as import68 from './+explore/featured/featured.component.ngfactory';
import * as import69 from './+explore/popular/popular.component.ngfactory';
import * as import70 from './+explore/categories/categories.component.ngfactory';
import * as import71 from './+help/help.component.ngfactory';
import * as import72 from './+help/faq/faq.component.ngfactory';
import * as import73 from './+help/support/support.component.ngfactory';
import * as import74 from './+highlights/highlights.component.ngfactory';
import * as import75 from './+jobs/jobs.component.ngfactory';
import * as import76 from './+project/single/single-project.component.ngfactory';
import * as import77 from './+project/single/dashboard/project-dashboard.component.ngfactory';
import * as import78 from './+search/search.component.ngfactory';
import * as import79 from './+settings/settings.component.ngfactory';
import * as import80 from './+team/single/single-team.component.ngfactory';
import * as import81 from './+team/single/dashboard/team-dashboard.component.ngfactory';
import * as import82 from './+terms/terms.component.ngfactory';
import * as import83 from './+terms/use/use.component.ngfactory';
import * as import84 from './+terms/privacy/privacy.component.ngfactory';
import * as import85 from './+terms/cookies/cookies.component.ngfactory';
import * as import86 from './+trending/trending.component.ngfactory';
import * as import87 from './+trending/users/trending-users.component.ngfactory';
import * as import88 from './+trending/teams/trending-teams.component.ngfactory';
import * as import89 from './+user/single/single-user.component.ngfactory';
import * as import90 from './+404/404.component.ngfactory';
import * as import91 from './app.component.ngfactory';
import * as import92 from './+about/about.component';
import * as import93 from './+about/how-it-works/how-it-works.component';
import * as import94 from './+about/welcome/welcome.component';
import * as import95 from './+about/who-we-are/who-we-are.component';
import * as import96 from './+about/press/press.component';
import * as import97 from './auth/components/login/login.component';
import * as import98 from './auth/components/signup/signup.component';
import * as import99 from './+contact/contact.component';
import * as import100 from './+contact/newsletters/newsletters.component';
import * as import101 from './create/create.component';
import * as import102 from './discover/discover.component';
import * as import103 from './+explore/explore.component';
import * as import104 from './+explore/featured/featured.component';
import * as import105 from './+explore/popular/popular.component';
import * as import106 from './+explore/categories/categories.component';
import * as import107 from './+help/help.component';
import * as import108 from './+help/faq/faq.component';
import * as import109 from './+help/support/support.component';
import * as import110 from './+highlights/highlights.component';
import * as import111 from './+jobs/jobs.component';
import * as import112 from './+project/single/single-project.component';
import * as import113 from './+project/single/dashboard/project-dashboard.component';
import * as import114 from './+search/search.component';
import * as import115 from './+settings/settings.component';
import * as import116 from './+team/single/single-team.component';
import * as import117 from './+team/single/dashboard/team-dashboard.component';
import * as import118 from './+terms/terms.component';
import * as import119 from './+terms/use/use.component';
import * as import120 from './+terms/privacy/privacy.component';
import * as import121 from './+terms/cookies/cookies.component';
import * as import122 from './+trending/trending.component';
import * as import123 from './+trending/users/trending-users.component';
import * as import124 from './+trending/teams/trending-teams.component';
import * as import125 from './+user/single/single-user.component';
import * as import126 from './+404/404.component';
import * as import127 from './apollo.server';
import * as import128 from 'apollo-angular/build/src/Apollo';
import * as import129 from './auth/reducers/auth.reducers';
import * as import130 from 'apollo-angular/build/src/tokens';
import * as import131 from '@ngrx/store/src/reducer';
import * as import132 from '@ngrx/store/src/state';
import * as import133 from '@ngrx/store/src/store';
import * as import134 from './auth/services/auth.service';
class ServerAppModuleInjector extends import0.ɵNgModuleInjector<import1.ServerAppModule> {
  _HttpModule_0:import2.HttpModule;
  _CommonModule_1:import3.CommonModule;
  _ApplicationModule_2:import0.ApplicationModule;
  _BrowserModule_3:import4.BrowserModule;
  _ServerModule_4:import5.ServerModule;
  _ServerTransferStateModule_5:import6.ServerTransferStateModule;
  _ɵba_6:import7.ɵba;
  _ReactiveFormsModule_7:import7.ReactiveFormsModule;
  _ɵa_8:any;
  _RouterModule_9:import8.RouterModule;
  _ApolloModule_10:import9.ApolloModule;
  _SharedComponentsModule_11:import10.SharedComponentsModule;
  _SharedModule_12:import11.SharedModule;
  _AboutRoutingModule_13:import12.AboutRoutingModule;
  _AboutModule_14:import13.AboutModule;
  _AuthRoutingModule_15:import14.AuthRoutingModule;
  _AuthModule_16:import15.AuthModule;
  _ContactRoutingModule_17:import16.ContactRoutingModule;
  _ContactModule_18:import17.ContactModule;
  _CreateRoutingModule_19:import18.CreateRoutingModule;
  _CreateModule_20:import19.CreateModule;
  _DiscoverRoutingModule_21:import20.DiscoverRoutingModule;
  _DiscoverModule_22:import21.DiscoverModule;
  _ExploreRoutingModule_23:import22.ExploreRoutingModule;
  _ExploreModule_24:import23.ExploreModule;
  _HelpRoutingModule_25:import24.HelpRoutingModule;
  _HelpModule_26:import25.HelpModule;
  _HighlightsRoutingModule_27:import26.HighlightsRoutingModule;
  _HighlightsModule_28:import27.HighlightsModule;
  _JobsRoutingModule_29:import28.JobsRoutingModule;
  _JobsModule_30:import29.JobsModule;
  _ProjectRoutingModule_31:import30.ProjectRoutingModule;
  _ProjectModule_32:import31.ProjectModule;
  _SearchRoutingModule_33:import32.SearchRoutingModule;
  _SearchModule_34:import33.SearchModule;
  _SettingsRoutingModule_35:import34.SettingsRoutingModule;
  _SettingsModule_36:import35.SettingsModule;
  _TeamRoutingModule_37:import36.TeamRoutingModule;
  _TeamModule_38:import37.TeamModule;
  _TermsRoutingModule_39:import38.TermsRoutingModule;
  _TermsModule_40:import39.TermsModule;
  _TrendingRoutingModule_41:import40.TrendingRoutingModule;
  _TrendingModule_42:import41.TrendingModule;
  _UserRoutingModule_43:import42.UserRoutingModule;
  _UserModule_44:import43.UserModule;
  _AppRoutingModule_45:import44.AppRoutingModule;
  _NotFoundRoutingModule_46:import45.NotFoundRoutingModule;
  _StoreModule_47:import46.StoreModule;
  _AppModule_48:import47.AppModule;
  _ServerAppModule_49:import1.ServerAppModule;
  __BrowserXhr_50:import5.ɵc;
  __ResponseOptions_51:import2.BaseResponseOptions;
  __XSRFStrategy_52:import5.ɵd;
  __XHRBackend_53:import2.XHRBackend;
  __RequestOptions_54:import2.BaseRequestOptions;
  __Http_55:any;
  __LOCALE_ID_56:any;
  __NgLocalization_57:import3.NgLocaleLocalization;
  _ErrorHandler_58:any;
  _NgProbeToken_59:any[];
  _APP_INITIALIZER_60:any[];
  _ApplicationInitStatus_61:import0.ApplicationInitStatus;
  _ɵf_62:import0.ɵf;
  __ApplicationRef_63:any;
  __Compiler_64:import0.Compiler;
  __APP_ID_65:any;
  __IterableDiffers_66:any;
  __KeyValueDiffers_67:any;
  __DomSanitizer_68:import4.ɵe;
  __Sanitizer_69:any;
  __HAMMER_GESTURE_CONFIG_70:import4.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_71:any[];
  __EventManager_72:import4.EventManager;
  _ɵDomSharedStylesHost_73:import4.ɵDomSharedStylesHost;
  __ɵDomRendererFactoryV2_74:import4.ɵDomRendererFactoryV2;
  __ɵb_75:import5.ɵb;
  __ɵSharedStylesHost_76:any;
  __ɵa_77:import5.ɵa;
  __RendererFactoryV2_78:any;
  __Testability_79:any;
  __Meta_80:import4.Meta;
  __Title_81:import4.Title;
  __TransferState_82:import48.TransferState;
  __FormBuilder_83:import7.FormBuilder;
  __ɵi_84:import7.ɵi;
  __ROUTES_85:any[];
  __isServer_86:any;
  __CLIENT_MAP_WRAPPER_87:any;
  __CLIENT_MAP_88:any;
  __Apollo_89:any;
  __LRU_90:any;
  __CacheService_91:import49.CacheService;
  __Dispatcher_92:import50.Dispatcher;
  ___INITIAL_REDUCER_93:any;
  __INITIAL_REDUCER_94:any;
  __Reducer_95:any;
  ___INITIAL_STATE_96:any;
  __INITIAL_STATE_97:any;
  __State_98:any;
  __Store_99:any;
  __HashService_100:import51.HashService;
  __ApiService_101:import52.ApiService;
  __req_102:any;
  __AuthService_103:import53.ServerAuthService;
  __AuthModelService_104:import54.AuthModelService;
  __APP_BASE_HREF_105:any;
  __ROUTER_CONFIGURATION_106:any;
  __LocationStrategy_107:any;
  __Location_108:import3.Location;
  __UrlSerializer_109:import8.DefaultUrlSerializer;
  __RouterOutletMap_110:import8.RouterOutletMap;
  __NgModuleFactoryLoader_111:import0.SystemJsNgModuleLoader;
  __Router_112:any;
  __ActivatedRoute_113:any;
  _NoPreloading_114:import8.NoPreloading;
  _PreloadingStrategy_115:any;
  _RouterPreloader_116:import8.RouterPreloader;
  __PreloadAllModules_117:import8.PreloadAllModules;
  __ROUTER_INITIALIZER_118:any;
  __APP_BOOTSTRAP_LISTENER_119:any[];
  __isBrowser_120:any;
  __res_121:any;
  __MetaService_122:import55.MetaService;
  constructor(parent:import0.Injector) {
    super(parent,[
      import56.AboutComponentNgFactory,
      import57.HowItWorksComponentNgFactory,
      import58.WelcomeComponentNgFactory,
      import59.WhoWeAreComponentNgFactory,
      import60.PressComponentNgFactory,
      import61.LoginComponentNgFactory,
      import62.SignupComponentNgFactory,
      import63.ContactComponentNgFactory,
      import64.NewslettersComponentNgFactory,
      import65.CreateComponentNgFactory,
      import66.DiscoverComponentNgFactory,
      import67.ExploreComponentNgFactory,
      import68.FeaturedComponentNgFactory,
      import69.PopularComponentNgFactory,
      import70.CategoriesComponentNgFactory,
      import71.HelpComponentNgFactory,
      import72.FaqComponentNgFactory,
      import73.SupportComponentNgFactory,
      import74.HighlightsComponentNgFactory,
      import75.JobsComponentNgFactory,
      import76.SingleProjectComponentNgFactory,
      import77.ProjectDashboardComponentNgFactory,
      import78.SearchComponentNgFactory,
      import79.SettingsComponentNgFactory,
      import80.SingleTeamComponentNgFactory,
      import81.TeamDashboardComponentNgFactory,
      import82.TermsComponentNgFactory,
      import83.UseComponentNgFactory,
      import84.PrivacyComponentNgFactory,
      import85.CookiesComponentNgFactory,
      import86.TrendingComponentNgFactory,
      import87.TrendingUsersComponentNgFactory,
      import88.TrendingTeamsComponentNgFactory,
      import89.SingleUserComponentNgFactory,
      import90.NotFoundComponentNgFactory,
      import91.AppComponentNgFactory
    ]
    ,[import91.AppComponentNgFactory]);
  }
  get _BrowserXhr_50():import5.ɵc {
    if ((this.__BrowserXhr_50 == null)) { (this.__BrowserXhr_50 = new import5.ɵc()); }
    return this.__BrowserXhr_50;
  }
  get _ResponseOptions_51():import2.BaseResponseOptions {
    if ((this.__ResponseOptions_51 == null)) { (this.__ResponseOptions_51 = new import2.BaseResponseOptions()); }
    return this.__ResponseOptions_51;
  }
  get _XSRFStrategy_52():import5.ɵd {
    if ((this.__XSRFStrategy_52 == null)) { (this.__XSRFStrategy_52 = new import5.ɵd()); }
    return this.__XSRFStrategy_52;
  }
  get _XHRBackend_53():import2.XHRBackend {
    if ((this.__XHRBackend_53 == null)) { (this.__XHRBackend_53 = new import2.XHRBackend(this._BrowserXhr_50,this._ResponseOptions_51,this._XSRFStrategy_52)); }
    return this.__XHRBackend_53;
  }
  get _RequestOptions_54():import2.BaseRequestOptions {
    if ((this.__RequestOptions_54 == null)) { (this.__RequestOptions_54 = new import2.BaseRequestOptions()); }
    return this.__RequestOptions_54;
  }
  get _Http_55():any {
    if ((this.__Http_55 == null)) { (this.__Http_55 = import5.ɵe(this._XHRBackend_53,this._RequestOptions_54)); }
    return this.__Http_55;
  }
  get _LOCALE_ID_56():any {
    if ((this.__LOCALE_ID_56 == null)) { (this.__LOCALE_ID_56 = import0.ɵo(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_56;
  }
  get _NgLocalization_57():import3.NgLocaleLocalization {
    if ((this.__NgLocalization_57 == null)) { (this.__NgLocalization_57 = new import3.NgLocaleLocalization(this._LOCALE_ID_56)); }
    return this.__NgLocalization_57;
  }
  get _ApplicationRef_63():any {
    if ((this.__ApplicationRef_63 == null)) { (this.__ApplicationRef_63 = this._ɵf_62); }
    return this.__ApplicationRef_63;
  }
  get _Compiler_64():import0.Compiler {
    if ((this.__Compiler_64 == null)) { (this.__Compiler_64 = new import0.Compiler()); }
    return this.__Compiler_64;
  }
  get _APP_ID_65():any {
    if ((this.__APP_ID_65 == null)) { (this.__APP_ID_65 = import0.ɵg()); }
    return this.__APP_ID_65;
  }
  get _IterableDiffers_66():any {
    if ((this.__IterableDiffers_66 == null)) { (this.__IterableDiffers_66 = import0.ɵm()); }
    return this.__IterableDiffers_66;
  }
  get _KeyValueDiffers_67():any {
    if ((this.__KeyValueDiffers_67 == null)) { (this.__KeyValueDiffers_67 = import0.ɵn()); }
    return this.__KeyValueDiffers_67;
  }
  get _DomSanitizer_68():import4.ɵe {
    if ((this.__DomSanitizer_68 == null)) { (this.__DomSanitizer_68 = new import4.ɵe(this.parent.get(import4.DOCUMENT))); }
    return this.__DomSanitizer_68;
  }
  get _Sanitizer_69():any {
    if ((this.__Sanitizer_69 == null)) { (this.__Sanitizer_69 = this._DomSanitizer_68); }
    return this.__Sanitizer_69;
  }
  get _HAMMER_GESTURE_CONFIG_70():import4.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_70 == null)) { (this.__HAMMER_GESTURE_CONFIG_70 = new import4.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_70;
  }
  get _EVENT_MANAGER_PLUGINS_71():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_71 == null)) { (this.__EVENT_MANAGER_PLUGINS_71 = [
      new import4.ɵDomEventsPlugin(this.parent.get(import4.DOCUMENT)),
      new import4.ɵKeyEventsPlugin(this.parent.get(import4.DOCUMENT)),
      new import4.ɵHammerGesturesPlugin(this.parent.get(import4.DOCUMENT),this._HAMMER_GESTURE_CONFIG_70)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_71;
  }
  get _EventManager_72():import4.EventManager {
    if ((this.__EventManager_72 == null)) { (this.__EventManager_72 = new import4.EventManager(this._EVENT_MANAGER_PLUGINS_71,this.parent.get(import0.NgZone))); }
    return this.__EventManager_72;
  }
  get _ɵDomRendererFactoryV2_74():import4.ɵDomRendererFactoryV2 {
    if ((this.__ɵDomRendererFactoryV2_74 == null)) { (this.__ɵDomRendererFactoryV2_74 = new import4.ɵDomRendererFactoryV2(this._EventManager_72,this._ɵDomSharedStylesHost_73)); }
    return this.__ɵDomRendererFactoryV2_74;
  }
  get _ɵb_75():import5.ɵb {
    if ((this.__ɵb_75 == null)) { (this.__ɵb_75 = new import5.ɵb(this.parent.get(import4.DOCUMENT),this.parent.get(import4.ɵTRANSITION_ID,(null as any)))); }
    return this.__ɵb_75;
  }
  get _ɵSharedStylesHost_76():any {
    if ((this.__ɵSharedStylesHost_76 == null)) { (this.__ɵSharedStylesHost_76 = this._ɵb_75); }
    return this.__ɵSharedStylesHost_76;
  }
  get _ɵa_77():import5.ɵa {
    if ((this.__ɵa_77 == null)) { (this.__ɵa_77 = new import5.ɵa(this.parent.get(import0.NgZone),this.parent.get(import4.DOCUMENT),this._ɵSharedStylesHost_76)); }
    return this.__ɵa_77;
  }
  get _RendererFactoryV2_78():any {
    if ((this.__RendererFactoryV2_78 == null)) { (this.__RendererFactoryV2_78 = this._ɵa_77); }
    return this.__RendererFactoryV2_78;
  }
  get _Testability_79():any {
    if ((this.__Testability_79 == null)) { (this.__Testability_79 = (null as any)); }
    return this.__Testability_79;
  }
  get _Meta_80():import4.Meta {
    if ((this.__Meta_80 == null)) { (this.__Meta_80 = new import4.Meta(this.parent.get(import4.DOCUMENT))); }
    return this.__Meta_80;
  }
  get _Title_81():import4.Title {
    if ((this.__Title_81 == null)) { (this.__Title_81 = new import4.Title(this.parent.get(import4.DOCUMENT))); }
    return this.__Title_81;
  }
  get _TransferState_82():import48.TransferState {
    if ((this.__TransferState_82 == null)) { (this.__TransferState_82 = new import48.TransferState()); }
    return this.__TransferState_82;
  }
  get _FormBuilder_83():import7.FormBuilder {
    if ((this.__FormBuilder_83 == null)) { (this.__FormBuilder_83 = new import7.FormBuilder()); }
    return this.__FormBuilder_83;
  }
  get _ɵi_84():import7.ɵi {
    if ((this.__ɵi_84 == null)) { (this.__ɵi_84 = new import7.ɵi()); }
    return this.__ɵi_84;
  }
  get _ROUTES_85():any[] {
    if ((this.__ROUTES_85 == null)) { (this.__ROUTES_85 = [
      [
        {
          path: 'about',
          component: import92.AboutComponent
        }
        ,
        {
          path: 'about/how-it-works',
          component: import93.HowItWorksComponent
        }
        ,
        {
          path: 'about/welcome',
          component: import94.WelcomeComponent
        }
        ,
        {
          path: 'about/who-we-are',
          component: import95.WhoWeAreComponent
        }
        ,
        {
          path: 'about/press',
          component: import96.PressComponent
        }

      ]
      ,
      [
        {
          path: 'login',
          component: import97.LoginComponent
        }
        ,
        {
          path: 'signup',
          component: import98.SignupComponent
        }

      ]
      ,
      [
        {
          path: 'contact',
          component: import99.ContactComponent
        }
        ,
        {
          path: 'newsletters',
          component: import100.NewslettersComponent
        }

      ]
      ,
        [{
          path: 'create',
          component: import101.CreateComponent
        }
      ],
        [{
          path: 'discover',
          component: import102.DiscoverComponent
        }
      ],
      [
        {
          path: 'explore',
          component: import103.ExploreComponent
        }
        ,
        {
          path: 'explore/featured',
          component: import104.FeaturedComponent
        }
        ,
        {
          path: 'explore/popular',
          component: import105.PopularComponent
        }
        ,
        {
          path: 'explore/categories',
          component: import106.CategoriesComponent
        }

      ]
      ,
      [
        {
          path: 'help',
          component: import107.HelpComponent
        }
        ,
        {
          path: 'help/faq',
          component: import108.FaqComponent
        }
        ,
        {
          path: 'help/support',
          component: import109.SupportComponent
        }

      ]
      ,
        [{
          path: 'highlights',
          component: import110.HighlightsComponent
        }
      ],
        [{
          path: 'jobs',
          component: import111.JobsComponent
        }
      ],
      [
        {
          path: 'project/:slug',
          component: import112.SingleProjectComponent
        }
        ,
        {
          path: 'project/:slug/dashboard',
          component: import113.ProjectDashboardComponent
        }
        ,
        {
          path: 'project/:slug/dashboard/applications',
          component: import113.ProjectDashboardComponent
        }
        ,
        {
          path: 'project/:slug/dashboard/application/:application_id',
          component: import113.ProjectDashboardComponent
        }

      ]
      ,
        [{
          path: 'search',
          component: import114.SearchComponent
        }
      ],
        [{
          path: 'settings',
          component: import115.SettingsComponent
        }
      ],
      [
        {
          path: 'team/:slug',
          component: import116.SingleTeamComponent
        }
        ,
        {
          path: 'team/:slug/dashboard',
          component: import117.TeamDashboardComponent
        }

      ]
      ,
      [
        {
          path: 'terms',
          component: import118.TermsComponent
        }
        ,
        {
          path: 'terms/use',
          component: import119.UseComponent
        }
        ,
        {
          path: 'terms/privacy',
          component: import120.PrivacyComponent
        }
        ,
        {
          path: 'terms/cookies',
          component: import121.CookiesComponent
        }

      ]
      ,
      [
        {
          path: 'trending',
          component: import122.TrendingComponent
        }
        ,
        {
          path: 'trending/users',
          component: import123.TrendingUsersComponent
        }
        ,
        {
          path: 'trending/teams',
          component: import124.TrendingTeamsComponent
        }

      ]
      ,
        [{
          path: 'user/:slug',
          component: import125.SingleUserComponent
        }
      ],
        [{
          path: '',
          redirectTo: '/discover',
          pathMatch: 'full'
        }
      ],
      [
        {
          path: '404',
          component: import126.NotFoundComponent
        }
        ,
        {
          path: '**',
          redirectTo: '/404'
        }

      ]
      ,
      ([] as any[])
    ]
    ); }
    return this.__ROUTES_85;
  }
  get _isServer_86():any {
    if ((this.__isServer_86 == null)) { (this.__isServer_86 = false); }
    return this.__isServer_86;
  }
  get _CLIENT_MAP_WRAPPER_87():any {
    if ((this.__CLIENT_MAP_WRAPPER_87 == null)) { (this.__CLIENT_MAP_WRAPPER_87 = import127.provideClient); }
    return this.__CLIENT_MAP_WRAPPER_87;
  }
  get _CLIENT_MAP_88():any {
    if ((this.__CLIENT_MAP_88 == null)) { (this.__CLIENT_MAP_88 = import128.getClientMap(this._CLIENT_MAP_WRAPPER_87)); }
    return this.__CLIENT_MAP_88;
  }
  get _Apollo_89():any {
    if ((this.__Apollo_89 == null)) { (this.__Apollo_89 = import128.createApollo(this._CLIENT_MAP_88)); }
    return this.__Apollo_89;
  }
  get _LRU_90():any {
    if ((this.__LRU_90 == null)) { (this.__LRU_90 = import1.getServerLRU()); }
    return this.__LRU_90;
  }
  get _CacheService_91():import49.CacheService {
    if ((this.__CacheService_91 == null)) { (this.__CacheService_91 = new import49.CacheService(this._LRU_90)); }
    return this.__CacheService_91;
  }
  get _Dispatcher_92():import50.Dispatcher {
    if ((this.__Dispatcher_92 == null)) { (this.__Dispatcher_92 = new import50.Dispatcher()); }
    return this.__Dispatcher_92;
  }
  get __INITIAL_REDUCER_93():any {
    if ((this.___INITIAL_REDUCER_93 == null)) { (this.___INITIAL_REDUCER_93 = {auth: import129.authReducer}); }
    return this.___INITIAL_REDUCER_93;
  }
  get _INITIAL_REDUCER_94():any {
    if ((this.__INITIAL_REDUCER_94 == null)) { (this.__INITIAL_REDUCER_94 = import46._initialReducerFactory(this.__INITIAL_REDUCER_93)); }
    return this.__INITIAL_REDUCER_94;
  }
  get _Reducer_95():any {
    if ((this.__Reducer_95 == null)) { (this.__Reducer_95 = import46._reducerFactory(this._Dispatcher_92,this._INITIAL_REDUCER_94)); }
    return this.__Reducer_95;
  }
  get __INITIAL_STATE_96():any {
    if ((this.___INITIAL_STATE_96 == null)) { (this.___INITIAL_STATE_96 = (undefined as any)); }
    return this.___INITIAL_STATE_96;
  }
  get _INITIAL_STATE_97():any {
    if ((this.__INITIAL_STATE_97 == null)) { (this.__INITIAL_STATE_97 = import46._initialStateFactory(this.__INITIAL_STATE_96,this._INITIAL_REDUCER_94)); }
    return this.__INITIAL_STATE_97;
  }
  get _State_98():any {
    if ((this.__State_98 == null)) { (this.__State_98 = import46._stateFactory(this._INITIAL_STATE_97,this._Dispatcher_92,this._Reducer_95)); }
    return this.__State_98;
  }
  get _Store_99():any {
    if ((this.__Store_99 == null)) { (this.__Store_99 = import46._storeFactory(this._Dispatcher_92,this._Reducer_95,this._State_98)); }
    return this.__Store_99;
  }
  get _HashService_100():import51.HashService {
    if ((this.__HashService_100 == null)) { (this.__HashService_100 = new import51.HashService()); }
    return this.__HashService_100;
  }
  get _ApiService_101():import52.ApiService {
    if ((this.__ApiService_101 == null)) { (this.__ApiService_101 = new import52.ApiService(this._isServer_86,this._Apollo_89,this._CacheService_91,this._Store_99,this._HashService_100)); }
    return this.__ApiService_101;
  }
  get _req_102():any {
    if ((this.__req_102 == null)) { (this.__req_102 = import1.getRequest()); }
    return this.__req_102;
  }
  get _AuthService_103():import53.ServerAuthService {
    if ((this.__AuthService_103 == null)) { (this.__AuthService_103 = new import53.ServerAuthService(this._ApiService_101,this._Http_55,this._req_102)); }
    return this.__AuthService_103;
  }
  get _AuthModelService_104():import54.AuthModelService {
    if ((this.__AuthModelService_104 == null)) { (this.__AuthModelService_104 = new import54.AuthModelService(this._AuthService_103,this._Store_99)); }
    return this.__AuthModelService_104;
  }
  get _APP_BASE_HREF_105():any {
    if ((this.__APP_BASE_HREF_105 == null)) { (this.__APP_BASE_HREF_105 = '/'); }
    return this.__APP_BASE_HREF_105;
  }
  get _ROUTER_CONFIGURATION_106():any {
    if ((this.__ROUTER_CONFIGURATION_106 == null)) { (this.__ROUTER_CONFIGURATION_106 = {useHash: false}); }
    return this.__ROUTER_CONFIGURATION_106;
  }
  get _LocationStrategy_107():any {
    if ((this.__LocationStrategy_107 == null)) { (this.__LocationStrategy_107 = import8.ɵc(this.parent.get(import3.PlatformLocation),this._APP_BASE_HREF_105,this._ROUTER_CONFIGURATION_106)); }
    return this.__LocationStrategy_107;
  }
  get _Location_108():import3.Location {
    if ((this.__Location_108 == null)) { (this.__Location_108 = new import3.Location(this._LocationStrategy_107)); }
    return this.__Location_108;
  }
  get _UrlSerializer_109():import8.DefaultUrlSerializer {
    if ((this.__UrlSerializer_109 == null)) { (this.__UrlSerializer_109 = new import8.DefaultUrlSerializer()); }
    return this.__UrlSerializer_109;
  }
  get _RouterOutletMap_110():import8.RouterOutletMap {
    if ((this.__RouterOutletMap_110 == null)) { (this.__RouterOutletMap_110 = new import8.RouterOutletMap()); }
    return this.__RouterOutletMap_110;
  }
  get _NgModuleFactoryLoader_111():import0.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_111 == null)) { (this.__NgModuleFactoryLoader_111 = new import0.SystemJsNgModuleLoader(this._Compiler_64,this.parent.get(import0.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_111;
  }
  get _Router_112():any {
    if ((this.__Router_112 == null)) { (this.__Router_112 = import8.ɵe(this._ApplicationRef_63,this._UrlSerializer_109,this._RouterOutletMap_110,this._Location_108,this,this._NgModuleFactoryLoader_111,this._Compiler_64,this._ROUTES_85,this._ROUTER_CONFIGURATION_106,this.parent.get(import8.UrlHandlingStrategy,(null as any)),this.parent.get(import8.RouteReuseStrategy,(null as any)))); }
    return this.__Router_112;
  }
  get _ActivatedRoute_113():any {
    if ((this.__ActivatedRoute_113 == null)) { (this.__ActivatedRoute_113 = import8.ɵf(this._Router_112)); }
    return this.__ActivatedRoute_113;
  }
  get _PreloadAllModules_117():import8.PreloadAllModules {
    if ((this.__PreloadAllModules_117 == null)) { (this.__PreloadAllModules_117 = new import8.PreloadAllModules()); }
    return this.__PreloadAllModules_117;
  }
  get _ROUTER_INITIALIZER_118():any {
    if ((this.__ROUTER_INITIALIZER_118 == null)) { (this.__ROUTER_INITIALIZER_118 = import8.ɵg(this._Router_112,this._ApplicationRef_63,this._RouterPreloader_116,this._ROUTER_CONFIGURATION_106)); }
    return this.__ROUTER_INITIALIZER_118;
  }
  get _APP_BOOTSTRAP_LISTENER_119():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_119 == null)) { (this.__APP_BOOTSTRAP_LISTENER_119 = [this._ROUTER_INITIALIZER_118]); }
    return this.__APP_BOOTSTRAP_LISTENER_119;
  }
  get _isBrowser_120():any {
    if ((this.__isBrowser_120 == null)) { (this.__isBrowser_120 = false); }
    return this.__isBrowser_120;
  }
  get _res_121():any {
    if ((this.__res_121 == null)) { (this.__res_121 = import1.getResponse()); }
    return this.__res_121;
  }
  get _MetaService_122():import55.MetaService {
    if ((this.__MetaService_122 == null)) { (this.__MetaService_122 = new import55.MetaService(this._isServer_86,this._Title_81,this._Meta_80)); }
    return this.__MetaService_122;
  }
  createInternal():import1.ServerAppModule {
    this._HttpModule_0 = new import2.HttpModule();
    this._CommonModule_1 = new import3.CommonModule();
    this._ApplicationModule_2 = new import0.ApplicationModule();
    this._BrowserModule_3 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._ServerModule_4 = new import5.ServerModule();
    this._ServerTransferStateModule_5 = new import6.ServerTransferStateModule();
    this._ɵba_6 = new import7.ɵba();
    this._ReactiveFormsModule_7 = new import7.ReactiveFormsModule();
    this._ɵa_8 = import8.ɵd(this.parent.get(import8.Router,(null as any)));
    this._RouterModule_9 = new import8.RouterModule(this._ɵa_8);
    this._ApolloModule_10 = new import9.ApolloModule();
    this._SharedComponentsModule_11 = new import10.SharedComponentsModule();
    this._SharedModule_12 = new import11.SharedModule();
    this._AboutRoutingModule_13 = new import12.AboutRoutingModule();
    this._AboutModule_14 = new import13.AboutModule();
    this._AuthRoutingModule_15 = new import14.AuthRoutingModule();
    this._AuthModule_16 = new import15.AuthModule();
    this._ContactRoutingModule_17 = new import16.ContactRoutingModule();
    this._ContactModule_18 = new import17.ContactModule();
    this._CreateRoutingModule_19 = new import18.CreateRoutingModule();
    this._CreateModule_20 = new import19.CreateModule();
    this._DiscoverRoutingModule_21 = new import20.DiscoverRoutingModule();
    this._DiscoverModule_22 = new import21.DiscoverModule();
    this._ExploreRoutingModule_23 = new import22.ExploreRoutingModule();
    this._ExploreModule_24 = new import23.ExploreModule();
    this._HelpRoutingModule_25 = new import24.HelpRoutingModule();
    this._HelpModule_26 = new import25.HelpModule();
    this._HighlightsRoutingModule_27 = new import26.HighlightsRoutingModule();
    this._HighlightsModule_28 = new import27.HighlightsModule();
    this._JobsRoutingModule_29 = new import28.JobsRoutingModule();
    this._JobsModule_30 = new import29.JobsModule();
    this._ProjectRoutingModule_31 = new import30.ProjectRoutingModule();
    this._ProjectModule_32 = new import31.ProjectModule();
    this._SearchRoutingModule_33 = new import32.SearchRoutingModule();
    this._SearchModule_34 = new import33.SearchModule();
    this._SettingsRoutingModule_35 = new import34.SettingsRoutingModule();
    this._SettingsModule_36 = new import35.SettingsModule();
    this._TeamRoutingModule_37 = new import36.TeamRoutingModule();
    this._TeamModule_38 = new import37.TeamModule();
    this._TermsRoutingModule_39 = new import38.TermsRoutingModule();
    this._TermsModule_40 = new import39.TermsModule();
    this._TrendingRoutingModule_41 = new import40.TrendingRoutingModule();
    this._TrendingModule_42 = new import41.TrendingModule();
    this._UserRoutingModule_43 = new import42.UserRoutingModule();
    this._UserModule_44 = new import43.UserModule();
    this._AppRoutingModule_45 = new import44.AppRoutingModule();
    this._NotFoundRoutingModule_46 = new import45.NotFoundRoutingModule();
    this._StoreModule_47 = new import46.StoreModule();
    this._AppModule_48 = new import47.AppModule();
    this._ServerAppModule_49 = new import1.ServerAppModule();
    this._ErrorHandler_58 = import4.ɵa();
    this._NgProbeToken_59 = [import8.ɵb()];
    this._APP_INITIALIZER_60 = [
      import0.ɵp,
      import4.ɵc(this.parent.get(import4.NgProbeToken,(null as any)),this._NgProbeToken_59)
    ]
    ;
    this._ApplicationInitStatus_61 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_60);
    this._ɵf_62 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_58,this,this._ApplicationInitStatus_61);
    this._ɵDomSharedStylesHost_73 = new import4.ɵDomSharedStylesHost(this.parent.get(import4.DOCUMENT));
    this._NoPreloading_114 = new import8.NoPreloading();
    this._PreloadingStrategy_115 = this._NoPreloading_114;
    this._RouterPreloader_116 = new import8.RouterPreloader(this._Router_112,this._NgModuleFactoryLoader_111,this._Compiler_64,this,this._PreloadingStrategy_115);
    return this._ServerAppModule_49;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.HttpModule)) { return this._HttpModule_0; }
    if ((token === import3.CommonModule)) { return this._CommonModule_1; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_2; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_3; }
    if ((token === import5.ServerModule)) { return this._ServerModule_4; }
    if ((token === import6.ServerTransferStateModule)) { return this._ServerTransferStateModule_5; }
    if ((token === import7.ɵba)) { return this._ɵba_6; }
    if ((token === import7.ReactiveFormsModule)) { return this._ReactiveFormsModule_7; }
    if ((token === import8.ɵa)) { return this._ɵa_8; }
    if ((token === import8.RouterModule)) { return this._RouterModule_9; }
    if ((token === import9.ApolloModule)) { return this._ApolloModule_10; }
    if ((token === import10.SharedComponentsModule)) { return this._SharedComponentsModule_11; }
    if ((token === import11.SharedModule)) { return this._SharedModule_12; }
    if ((token === import12.AboutRoutingModule)) { return this._AboutRoutingModule_13; }
    if ((token === import13.AboutModule)) { return this._AboutModule_14; }
    if ((token === import14.AuthRoutingModule)) { return this._AuthRoutingModule_15; }
    if ((token === import15.AuthModule)) { return this._AuthModule_16; }
    if ((token === import16.ContactRoutingModule)) { return this._ContactRoutingModule_17; }
    if ((token === import17.ContactModule)) { return this._ContactModule_18; }
    if ((token === import18.CreateRoutingModule)) { return this._CreateRoutingModule_19; }
    if ((token === import19.CreateModule)) { return this._CreateModule_20; }
    if ((token === import20.DiscoverRoutingModule)) { return this._DiscoverRoutingModule_21; }
    if ((token === import21.DiscoverModule)) { return this._DiscoverModule_22; }
    if ((token === import22.ExploreRoutingModule)) { return this._ExploreRoutingModule_23; }
    if ((token === import23.ExploreModule)) { return this._ExploreModule_24; }
    if ((token === import24.HelpRoutingModule)) { return this._HelpRoutingModule_25; }
    if ((token === import25.HelpModule)) { return this._HelpModule_26; }
    if ((token === import26.HighlightsRoutingModule)) { return this._HighlightsRoutingModule_27; }
    if ((token === import27.HighlightsModule)) { return this._HighlightsModule_28; }
    if ((token === import28.JobsRoutingModule)) { return this._JobsRoutingModule_29; }
    if ((token === import29.JobsModule)) { return this._JobsModule_30; }
    if ((token === import30.ProjectRoutingModule)) { return this._ProjectRoutingModule_31; }
    if ((token === import31.ProjectModule)) { return this._ProjectModule_32; }
    if ((token === import32.SearchRoutingModule)) { return this._SearchRoutingModule_33; }
    if ((token === import33.SearchModule)) { return this._SearchModule_34; }
    if ((token === import34.SettingsRoutingModule)) { return this._SettingsRoutingModule_35; }
    if ((token === import35.SettingsModule)) { return this._SettingsModule_36; }
    if ((token === import36.TeamRoutingModule)) { return this._TeamRoutingModule_37; }
    if ((token === import37.TeamModule)) { return this._TeamModule_38; }
    if ((token === import38.TermsRoutingModule)) { return this._TermsRoutingModule_39; }
    if ((token === import39.TermsModule)) { return this._TermsModule_40; }
    if ((token === import40.TrendingRoutingModule)) { return this._TrendingRoutingModule_41; }
    if ((token === import41.TrendingModule)) { return this._TrendingModule_42; }
    if ((token === import42.UserRoutingModule)) { return this._UserRoutingModule_43; }
    if ((token === import43.UserModule)) { return this._UserModule_44; }
    if ((token === import44.AppRoutingModule)) { return this._AppRoutingModule_45; }
    if ((token === import45.NotFoundRoutingModule)) { return this._NotFoundRoutingModule_46; }
    if ((token === import46.StoreModule)) { return this._StoreModule_47; }
    if ((token === import47.AppModule)) { return this._AppModule_48; }
    if ((token === import1.ServerAppModule)) { return this._ServerAppModule_49; }
    if ((token === import2.BrowserXhr)) { return this._BrowserXhr_50; }
    if ((token === import2.ResponseOptions)) { return this._ResponseOptions_51; }
    if ((token === import2.XSRFStrategy)) { return this._XSRFStrategy_52; }
    if ((token === import2.XHRBackend)) { return this._XHRBackend_53; }
    if ((token === import2.RequestOptions)) { return this._RequestOptions_54; }
    if ((token === import2.Http)) { return this._Http_55; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_56; }
    if ((token === import3.NgLocalization)) { return this._NgLocalization_57; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_58; }
    if ((token === import0.NgProbeToken)) { return this._NgProbeToken_59; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_60; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_61; }
    if ((token === import0.ɵf)) { return this._ɵf_62; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_63; }
    if ((token === import0.Compiler)) { return this._Compiler_64; }
    if ((token === import0.APP_ID)) { return this._APP_ID_65; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_66; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_67; }
    if ((token === import4.DomSanitizer)) { return this._DomSanitizer_68; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_69; }
    if ((token === import4.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_70; }
    if ((token === import4.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_71; }
    if ((token === import4.EventManager)) { return this._EventManager_72; }
    if ((token === import4.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_73; }
    if ((token === import4.ɵDomRendererFactoryV2)) { return this._ɵDomRendererFactoryV2_74; }
    if ((token === import5.ɵb)) { return this._ɵb_75; }
    if ((token === import4.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_76; }
    if ((token === import5.ɵa)) { return this._ɵa_77; }
    if ((token === import0.RendererFactoryV2)) { return this._RendererFactoryV2_78; }
    if ((token === import0.Testability)) { return this._Testability_79; }
    if ((token === import4.Meta)) { return this._Meta_80; }
    if ((token === import4.Title)) { return this._Title_81; }
    if ((token === import48.TransferState)) { return this._TransferState_82; }
    if ((token === import7.FormBuilder)) { return this._FormBuilder_83; }
    if ((token === import7.ɵi)) { return this._ɵi_84; }
    if ((token === import8.ROUTES)) { return this._ROUTES_85; }
    if ((token === 'isServer')) { return this._isServer_86; }
    if ((token === import130.CLIENT_MAP_WRAPPER)) { return this._CLIENT_MAP_WRAPPER_87; }
    if ((token === import130.CLIENT_MAP)) { return this._CLIENT_MAP_88; }
    if ((token === import128.Apollo)) { return this._Apollo_89; }
    if ((token === 'LRU')) { return this._LRU_90; }
    if ((token === import49.CacheService)) { return this._CacheService_91; }
    if ((token === import50.Dispatcher)) { return this._Dispatcher_92; }
    if ((token === import46._INITIAL_REDUCER)) { return this.__INITIAL_REDUCER_93; }
    if ((token === import46.INITIAL_REDUCER)) { return this._INITIAL_REDUCER_94; }
    if ((token === import131.Reducer)) { return this._Reducer_95; }
    if ((token === import46._INITIAL_STATE)) { return this.__INITIAL_STATE_96; }
    if ((token === import46.INITIAL_STATE)) { return this._INITIAL_STATE_97; }
    if ((token === import132.State)) { return this._State_98; }
    if ((token === import133.Store)) { return this._Store_99; }
    if ((token === import51.HashService)) { return this._HashService_100; }
    if ((token === import52.ApiService)) { return this._ApiService_101; }
    if ((token === 'req')) { return this._req_102; }
    if ((token === import134.AuthService)) { return this._AuthService_103; }
    if ((token === import54.AuthModelService)) { return this._AuthModelService_104; }
    if ((token === import3.APP_BASE_HREF)) { return this._APP_BASE_HREF_105; }
    if ((token === import8.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_106; }
    if ((token === import3.LocationStrategy)) { return this._LocationStrategy_107; }
    if ((token === import3.Location)) { return this._Location_108; }
    if ((token === import8.UrlSerializer)) { return this._UrlSerializer_109; }
    if ((token === import8.RouterOutletMap)) { return this._RouterOutletMap_110; }
    if ((token === import0.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_111; }
    if ((token === import8.Router)) { return this._Router_112; }
    if ((token === import8.ActivatedRoute)) { return this._ActivatedRoute_113; }
    if ((token === import8.NoPreloading)) { return this._NoPreloading_114; }
    if ((token === import8.PreloadingStrategy)) { return this._PreloadingStrategy_115; }
    if ((token === import8.RouterPreloader)) { return this._RouterPreloader_116; }
    if ((token === import8.PreloadAllModules)) { return this._PreloadAllModules_117; }
    if ((token === import8.ROUTER_INITIALIZER)) { return this._ROUTER_INITIALIZER_118; }
    if ((token === import0.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_119; }
    if ((token === 'isBrowser')) { return this._isBrowser_120; }
    if ((token === 'res')) { return this._res_121; }
    if ((token === import55.MetaService)) { return this._MetaService_122; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_62.ngOnDestroy();
    this._ɵDomSharedStylesHost_73.ngOnDestroy();
    this._RouterPreloader_116.ngOnDestroy();
  }
}
export const ServerAppModuleNgFactory:import0.NgModuleFactory<import1.ServerAppModule> = new import0.NgModuleFactory<any>(ServerAppModuleInjector,import1.ServerAppModule);