/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['main[_ngcontent-%COMP%] {min-height: calc(100vh - 327px);background:#fff;}\r\n\r\nfooter[_ngcontent-%COMP%] {padding:40px 0;background:#011627;color:#fff;}\r\n\r\nfooter[_ngcontent-%COMP%]   h3[_ngcontent-%COMP%] {color:#fff;}'];