/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './who-we-are.component';
const styles_WhoWeAreComponent:any[] = ([] as any[]);
export const RenderType_WhoWeAreComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_WhoWeAreComponent,
  data: {}
}
);
export function View_WhoWeAreComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Who We Arecomponent'])],(null as any),(null as any));
}
const RenderType_WhoWeAreComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_WhoWeAreComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'who-we-are',([] as any[]),(null as any),(null as any),(null as any),View_WhoWeAreComponent_0,RenderType_WhoWeAreComponent),
    import0.ɵdid(24576,(null as any),0,import1.WhoWeAreComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const WhoWeAreComponentNgFactory:import0.ComponentFactory<import1.WhoWeAreComponent> = import0.ɵccf('who-we-are',import1.WhoWeAreComponent,View_WhoWeAreComponent_Host_0);