/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './how-it-works.component';
const styles_HowItWorksComponent:any[] = ([] as any[]);
export const RenderType_HowItWorksComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_HowItWorksComponent,
  data: {}
}
);
export function View_HowItWorksComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['How It Works component'])],(null as any),(null as any));
}
const RenderType_HowItWorksComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_HowItWorksComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'how-it-works',([] as any[]),(null as any),(null as any),(null as any),View_HowItWorksComponent_0,RenderType_HowItWorksComponent),
    import0.ɵdid(24576,(null as any),0,import1.HowItWorksComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const HowItWorksComponentNgFactory:import0.ComponentFactory<import1.HowItWorksComponent> = import0.ɵccf('how-it-works',import1.HowItWorksComponent,View_HowItWorksComponent_Host_0);