/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './footer.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from './footer.component';
import * as import3 from '@angular/router';
import * as import4 from '@angular/common';
import * as import5 from '@angular/forms';
const styles_MainFooterComponent:any[] = [import0.styles];
export const RenderType_MainFooterComponent:import1.RendererTypeV2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_MainFooterComponent,
  data: {}
}
);
export function View_MainFooterComponent_0():import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    import1.ɵeld(0,(null as any),(null as any),156,'section',[
      [
        'class',
        'container'
      ]
      ,
      [
        'style',
        'padding:0 0 20px;border-bottom:1px solid rgba(255,255,255,0.25);'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n    ']),
    import1.ɵeld(0,(null as any),(null as any),153,'div',[
      [
        'class',
        'row'
      ]
      ,
      [
        'style',
        'margin:0;'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n      ']),
    import1.ɵeld(0,(null as any),(null as any),126,'nav',[
      [
        'class',
        'col-xs-12 col-md-7'
      ]
      ,
      [
        'style',
        'border-right:1px solid rgba(255,255,255,0.25);'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n        ']),
      import1.ɵeld(0,(null as any),(null as any),123,'div',[[
        'class',
        'row'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵeld(0,(null as any),(null as any),34,'ul',[
      [
        'class',
        'col-xs-6 col-md-3'
      ]
      ,
      [
        'style',
        'padding:0;list-style:none;'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n            ']),
      import1.ɵeld(0,(null as any),(null as any),1,'h5',[[
        'style',
        'text-transform:uppercase;letter-spacing:1px;font-weight:bold;'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Explore']),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵeld(0,(null as any),(null as any),3,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
      import1.ɵeld(0,(null as any),(null as any),2,'a',[[
        'routerLink',
        'explore/featured'
      ]
    ],[
      [
        0,
        'target',
        0
      ]
      ,
      [
        3,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.MainFooterComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,15).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdid(335872,(null as any),0,import3.RouterLinkWithHref,[
      import3.Router,
      import3.ActivatedRoute,
      import4.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵted((null as any),['Featured']),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵeld(0,(null as any),(null as any),3,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
      import1.ɵeld(0,(null as any),(null as any),2,'a',[[
        'routerLink',
        'explore/popular'
      ]
    ],[
      [
        0,
        'target',
        0
      ]
      ,
      [
        3,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.MainFooterComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,20).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdid(335872,(null as any),0,import3.RouterLinkWithHref,[
      import3.Router,
      import3.ActivatedRoute,
      import4.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵted((null as any),['Popular']),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵeld(0,(null as any),(null as any),3,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
      import1.ɵeld(0,(null as any),(null as any),2,'a',[[
        'routerLink',
        'explore/categories'
      ]
    ],[
      [
        0,
        'target',
        0
      ]
      ,
      [
        3,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.MainFooterComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,25).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdid(335872,(null as any),0,import3.RouterLinkWithHref,[
      import3.Router,
      import3.ActivatedRoute,
      import4.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵted((null as any),['Categories']),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵeld(0,(null as any),(null as any),3,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
      import1.ɵeld(0,(null as any),(null as any),2,'a',[[
        'routerLink',
        'trending/teams'
      ]
    ],[
      [
        0,
        'target',
        0
      ]
      ,
      [
        3,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.MainFooterComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,30).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdid(335872,(null as any),0,import3.RouterLinkWithHref,[
      import3.Router,
      import3.ActivatedRoute,
      import4.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵted((null as any),['Trending teams']),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵeld(0,(null as any),(null as any),3,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
      import1.ɵeld(0,(null as any),(null as any),2,'a',[[
        'routerLink',
        'trending/users'
      ]
    ],[
      [
        0,
        'target',
        0
      ]
      ,
      [
        3,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.MainFooterComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,35).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdid(335872,(null as any),0,import3.RouterLinkWithHref,[
      import3.Router,
      import3.ActivatedRoute,
      import4.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵted((null as any),['Power users']),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵeld(0,(null as any),(null as any),3,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
      import1.ɵeld(0,(null as any),(null as any),2,'a',[[
        'routerLink',
        'highlights'
      ]
    ],[
      [
        0,
        'target',
        0
      ]
      ,
      [
        3,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.MainFooterComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,40).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdid(335872,(null as any),0,import3.RouterLinkWithHref,[
      import3.Router,
      import3.ActivatedRoute,
      import4.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵted((null as any),['Highlights']),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵeld(0,(null as any),(null as any),29,'ul',[
      [
        'class',
        'col-xs-6 col-md-3'
      ]
      ,
      [
        'style',
        'padding:0;list-style:none;'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n            ']),
      import1.ɵeld(0,(null as any),(null as any),1,'h5',[[
        'style',
        'text-transform:uppercase;letter-spacing:1px;font-weight:bold;'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['About us']),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵeld(0,(null as any),(null as any),3,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
      import1.ɵeld(0,(null as any),(null as any),2,'a',[[
        'routerLink',
        'about/welcome'
      ]
    ],[
      [
        0,
        'target',
        0
      ]
      ,
      [
        3,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.MainFooterComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,51).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdid(335872,(null as any),0,import3.RouterLinkWithHref,[
      import3.Router,
      import3.ActivatedRoute,
      import4.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵted((null as any),['An open letter to the internet']),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵeld(0,(null as any),(null as any),3,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
      import1.ɵeld(0,(null as any),(null as any),2,'a',[[
        'routerLink',
        'about/how-it-works'
      ]
    ],[
      [
        0,
        'target',
        0
      ]
      ,
      [
        3,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.MainFooterComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,56).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdid(335872,(null as any),0,import3.RouterLinkWithHref,[
      import3.Router,
      import3.ActivatedRoute,
      import4.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵted((null as any),['How it works']),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵeld(0,(null as any),(null as any),3,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
      import1.ɵeld(0,(null as any),(null as any),2,'a',[[
        'routerLink',
        'about/who-we-are'
      ]
    ],[
      [
        0,
        'target',
        0
      ]
      ,
      [
        3,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.MainFooterComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,61).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdid(335872,(null as any),0,import3.RouterLinkWithHref,[
      import3.Router,
      import3.ActivatedRoute,
      import4.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵted((null as any),['Who we are']),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵeld(0,(null as any),(null as any),3,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
      import1.ɵeld(0,(null as any),(null as any),2,'a',[[
        'routerLink',
        'jobs'
      ]
    ],[
      [
        0,
        'target',
        0
      ]
      ,
      [
        3,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.MainFooterComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,66).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdid(335872,(null as any),0,import3.RouterLinkWithHref,[
      import3.Router,
      import3.ActivatedRoute,
      import4.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵted((null as any),['Jobs']),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵeld(0,(null as any),(null as any),3,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
      import1.ɵeld(0,(null as any),(null as any),2,'a',[[
        'routerLink',
        'about/press'
      ]
    ],[
      [
        0,
        'target',
        0
      ]
      ,
      [
        3,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.MainFooterComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,71).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdid(335872,(null as any),0,import3.RouterLinkWithHref,[
      import3.Router,
      import3.ActivatedRoute,
      import4.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵted((null as any),['Press']),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵeld(0,(null as any),(null as any),33,'ul',[
      [
        'class',
        'col-xs-6 col-md-3'
      ]
      ,
      [
        'style',
        'padding:0;list-style:none;'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n            ']),
      import1.ɵeld(0,(null as any),(null as any),1,'h5',[[
        'style',
        'text-transform:uppercase;letter-spacing:1px;font-weight:bold;'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Help']),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵeld(0,(null as any),(null as any),3,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
      import1.ɵeld(0,(null as any),(null as any),2,'a',[[
        'routerLink',
        'help/faq'
      ]
    ],[
      [
        0,
        'target',
        0
      ]
      ,
      [
        3,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.MainFooterComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,82).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdid(335872,(null as any),0,import3.RouterLinkWithHref,[
      import3.Router,
      import3.ActivatedRoute,
      import4.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵted((null as any),['FAQ']),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵeld(0,(null as any),(null as any),2,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
      import1.ɵeld(0,(null as any),(null as any),1,'a',[[
        'href',
        'https://community.heystitch.io'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Community']),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵeld(0,(null as any),(null as any),3,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
      import1.ɵeld(0,(null as any),(null as any),2,'a',[[
        'routerLink',
        'help/support'
      ]
    ],[
      [
        0,
        'target',
        0
      ]
      ,
      [
        3,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.MainFooterComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,91).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdid(335872,(null as any),0,import3.RouterLinkWithHref,[
      import3.Router,
      import3.ActivatedRoute,
      import4.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵted((null as any),['Support']),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵeld(0,(null as any),(null as any),3,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
      import1.ɵeld(0,(null as any),(null as any),2,'a',[[
        'routerLink',
        'terms/use'
      ]
    ],[
      [
        0,
        'target',
        0
      ]
      ,
      [
        3,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.MainFooterComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,96).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdid(335872,(null as any),0,import3.RouterLinkWithHref,[
      import3.Router,
      import3.ActivatedRoute,
      import4.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵted((null as any),['Terms of use']),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵeld(0,(null as any),(null as any),3,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
      import1.ɵeld(0,(null as any),(null as any),2,'a',[[
        'routerLink',
        'terms/privacy'
      ]
    ],[
      [
        0,
        'target',
        0
      ]
      ,
      [
        3,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.MainFooterComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,101).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdid(335872,(null as any),0,import3.RouterLinkWithHref,[
      import3.Router,
      import3.ActivatedRoute,
      import4.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵted((null as any),['Privacy policy']),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵeld(0,(null as any),(null as any),3,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
      import1.ɵeld(0,(null as any),(null as any),2,'a',[[
        'routerLink',
        'terms/cookies'
      ]
    ],[
      [
        0,
        'target',
        0
      ]
      ,
      [
        3,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.MainFooterComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,106).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdid(335872,(null as any),0,import3.RouterLinkWithHref,[
      import3.Router,
      import3.ActivatedRoute,
      import4.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵted((null as any),['Cookie policy']),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵeld(0,(null as any),(null as any),18,'ul',[
      [
        'class',
        'col-xs-6 col-md-3'
      ]
      ,
      [
        'style',
        'padding:0;list-style:none;'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n            ']),
      import1.ɵeld(0,(null as any),(null as any),1,'h5',[[
        'style',
        'text-transform:uppercase;letter-spacing:1px;font-weight:bold;'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Keep in touch']),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵeld(0,(null as any),(null as any),2,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
      import1.ɵeld(0,(null as any),(null as any),1,'a',[[
        'href',
        'https://blog.heystitch.io'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Blog']),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵeld(0,(null as any),(null as any),3,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
      import1.ɵeld(0,(null as any),(null as any),2,'a',[[
        'routerLink',
        'newsletters'
      ]
    ],[
      [
        0,
        'target',
        0
      ]
      ,
      [
        3,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.MainFooterComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,121).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdid(335872,(null as any),0,import3.RouterLinkWithHref,[
      import3.Router,
      import3.ActivatedRoute,
      import4.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵted((null as any),['Newsletters']),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵeld(0,(null as any),(null as any),3,'li',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
      import1.ɵeld(0,(null as any),(null as any),2,'a',[[
        'routerLink',
        'contact'
      ]
    ],[
      [
        0,
        'target',
        0
      ]
      ,
      [
        3,
        'href',
        4
      ]

    ]
      ,[[
        (null as any),
        'click'
      ]
    ],(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.MainFooterComponent = view.component;
      if (('click' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,126).onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdid(335872,(null as any),0,import3.RouterLinkWithHref,[
      import3.Router,
      import3.ActivatedRoute,
      import4.LocationStrategy
    ]
      ,{routerLink: [
        0,
        'routerLink'
      ]
    },(null as any)),
    import1.ɵted((null as any),['Contact']),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵted((null as any),['\n        ']),
    import1.ɵted((null as any),['\n      ']),
    import1.ɵted((null as any),['\n      ']),
    import1.ɵeld(0,(null as any),(null as any),22,'div',[
      [
        'class',
        'col-xs-12 col-md-5'
      ]
      ,
      [
        'style',
        'padding:0 0 0 40px;'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n        ']),
      import1.ɵeld(0,(null as any),(null as any),19,'form',[[
        'novalidate',
        ''
      ]
    ],[
      [
        1,
        'ng-untouched'
      ]
      ,
      [
        1,
        'ng-touched'
      ]
      ,
      [
        1,
        'ng-pristine'
      ]
      ,
      [
        1,
        'ng-dirty'
      ]
      ,
      [
        1,
        'ng-valid'
      ]
      ,
      [
        1,
        'ng-invalid'
      ]
      ,
      [
        1,
        'ng-pending'
      ]

    ]
    ,[
      [
        (null as any),
        'submit'
      ]
      ,
      [
        (null as any),
        'reset'
      ]

    ]
    ,(view,eventName,$event) => {
      var allowDefault:boolean = true;
      var comp:import2.MainFooterComponent = view.component;
      if (('submit' === eventName)) {
        const pd_0:any = ((<any>import1.ɵnov(view,136).onSubmit($event)) !== false);
        allowDefault = (pd_0 && allowDefault);
      }
      if (('reset' === eventName)) {
        const pd_1:any = ((<any>import1.ɵnov(view,136).onReset()) !== false);
        allowDefault = (pd_1 && allowDefault);
      }
      return allowDefault;
    },(null as any),(null as any)),
    import1.ɵdid(8192,(null as any),0,import5.ɵbf,([] as any[]),(null as any),(null as any)),
    import1.ɵdid(270336,(null as any),0,import5.FormGroupDirective,[
      [
        8,
        (null as any)
      ]
      ,
      [
        8,
        (null as any)
      ]

    ]
      ,{form: [
        0,
        'form'
      ]
    },(null as any)),
    import1.ɵprd(1024,(null as any),import5.ControlContainer,(null as any),[import5.FormGroupDirective]),
    import1.ɵdid(8192,(null as any),0,import5.NgControlStatusGroup,[import5.ControlContainer],(null as any),(null as any)),
    import1.ɵted((null as any),['\n          ']),
      import1.ɵeld(0,(null as any),(null as any),1,'h3',[[
        'style',
        'margin-bottom:20px;'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Join our newsletter']),
    import1.ɵted((null as any),['\n          ']),
      import1.ɵeld(0,(null as any),(null as any),9,'div',[[
        'class',
        'input-group'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵeld(0,(null as any),(null as any),0,'input',[
      [
        'class',
        'form-control'
      ]
      ,
      [
        'placeholder',
        'awesome@email.com'
      ]
      ,
      [
        'type',
        'email'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n            ']),
      import1.ɵeld(0,(null as any),(null as any),4,'span',[[
        'class',
        'input-group-btn'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n              ']),
    import1.ɵeld(0,(null as any),(null as any),1,'button',[
      [
        'class',
        'btn btn-primary'
      ]
      ,
      [
        'type',
        'button'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['I want in']),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵted((null as any),['\n        ']),
    import1.ɵted((null as any),['\n      ']),
    import1.ɵted((null as any),['\n    ']),
    import1.ɵted((null as any),['\n  ']),
    import1.ɵted((null as any),['\n  ']),
    import1.ɵeld(0,(null as any),(null as any),1,'nav',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n    \n  '])
  ]
  ,(check,view) => {
    var comp:import2.MainFooterComponent = view.component;
    const currVal_0:any = 'explore/featured';
    check(view,15,0,currVal_0);
    const currVal_1:any = 'explore/popular';
    check(view,20,0,currVal_1);
    const currVal_2:any = 'explore/categories';
    check(view,25,0,currVal_2);
    const currVal_3:any = 'trending/teams';
    check(view,30,0,currVal_3);
    const currVal_4:any = 'trending/users';
    check(view,35,0,currVal_4);
    const currVal_5:any = 'highlights';
    check(view,40,0,currVal_5);
    const currVal_6:any = 'about/welcome';
    check(view,51,0,currVal_6);
    const currVal_7:any = 'about/how-it-works';
    check(view,56,0,currVal_7);
    const currVal_8:any = 'about/who-we-are';
    check(view,61,0,currVal_8);
    const currVal_9:any = 'jobs';
    check(view,66,0,currVal_9);
    const currVal_10:any = 'about/press';
    check(view,71,0,currVal_10);
    const currVal_11:any = 'help/faq';
    check(view,82,0,currVal_11);
    const currVal_12:any = 'help/support';
    check(view,91,0,currVal_12);
    const currVal_13:any = 'terms/use';
    check(view,96,0,currVal_13);
    const currVal_14:any = 'terms/privacy';
    check(view,101,0,currVal_14);
    const currVal_15:any = 'terms/cookies';
    check(view,106,0,currVal_15);
    const currVal_16:any = 'newsletters';
    check(view,121,0,currVal_16);
    const currVal_17:any = 'contact';
    check(view,126,0,currVal_17);
    const currVal_18:any = comp.newsletterForm;
    check(view,136,0,currVal_18);
  },(check,view) => {
    var comp:import2.MainFooterComponent = view.component;
    const currVal_0:any = import1.ɵnov(view,15).target;
    const currVal_1:any = import1.ɵnov(view,15).href;
    check(view,14,0,currVal_0,currVal_1);
    const currVal_2:any = import1.ɵnov(view,20).target;
    const currVal_3:any = import1.ɵnov(view,20).href;
    check(view,19,0,currVal_2,currVal_3);
    const currVal_4:any = import1.ɵnov(view,25).target;
    const currVal_5:any = import1.ɵnov(view,25).href;
    check(view,24,0,currVal_4,currVal_5);
    const currVal_6:any = import1.ɵnov(view,30).target;
    const currVal_7:any = import1.ɵnov(view,30).href;
    check(view,29,0,currVal_6,currVal_7);
    const currVal_8:any = import1.ɵnov(view,35).target;
    const currVal_9:any = import1.ɵnov(view,35).href;
    check(view,34,0,currVal_8,currVal_9);
    const currVal_10:any = import1.ɵnov(view,40).target;
    const currVal_11:any = import1.ɵnov(view,40).href;
    check(view,39,0,currVal_10,currVal_11);
    const currVal_12:any = import1.ɵnov(view,51).target;
    const currVal_13:any = import1.ɵnov(view,51).href;
    check(view,50,0,currVal_12,currVal_13);
    const currVal_14:any = import1.ɵnov(view,56).target;
    const currVal_15:any = import1.ɵnov(view,56).href;
    check(view,55,0,currVal_14,currVal_15);
    const currVal_16:any = import1.ɵnov(view,61).target;
    const currVal_17:any = import1.ɵnov(view,61).href;
    check(view,60,0,currVal_16,currVal_17);
    const currVal_18:any = import1.ɵnov(view,66).target;
    const currVal_19:any = import1.ɵnov(view,66).href;
    check(view,65,0,currVal_18,currVal_19);
    const currVal_20:any = import1.ɵnov(view,71).target;
    const currVal_21:any = import1.ɵnov(view,71).href;
    check(view,70,0,currVal_20,currVal_21);
    const currVal_22:any = import1.ɵnov(view,82).target;
    const currVal_23:any = import1.ɵnov(view,82).href;
    check(view,81,0,currVal_22,currVal_23);
    const currVal_24:any = import1.ɵnov(view,91).target;
    const currVal_25:any = import1.ɵnov(view,91).href;
    check(view,90,0,currVal_24,currVal_25);
    const currVal_26:any = import1.ɵnov(view,96).target;
    const currVal_27:any = import1.ɵnov(view,96).href;
    check(view,95,0,currVal_26,currVal_27);
    const currVal_28:any = import1.ɵnov(view,101).target;
    const currVal_29:any = import1.ɵnov(view,101).href;
    check(view,100,0,currVal_28,currVal_29);
    const currVal_30:any = import1.ɵnov(view,106).target;
    const currVal_31:any = import1.ɵnov(view,106).href;
    check(view,105,0,currVal_30,currVal_31);
    const currVal_32:any = import1.ɵnov(view,121).target;
    const currVal_33:any = import1.ɵnov(view,121).href;
    check(view,120,0,currVal_32,currVal_33);
    const currVal_34:any = import1.ɵnov(view,126).target;
    const currVal_35:any = import1.ɵnov(view,126).href;
    check(view,125,0,currVal_34,currVal_35);
    const currVal_36:any = import1.ɵnov(view,138).ngClassUntouched;
    const currVal_37:any = import1.ɵnov(view,138).ngClassTouched;
    const currVal_38:any = import1.ɵnov(view,138).ngClassPristine;
    const currVal_39:any = import1.ɵnov(view,138).ngClassDirty;
    const currVal_40:any = import1.ɵnov(view,138).ngClassValid;
    const currVal_41:any = import1.ɵnov(view,138).ngClassInvalid;
    const currVal_42:any = import1.ɵnov(view,138).ngClassPending;
    check(view,134,0,currVal_36,currVal_37,currVal_38,currVal_39,currVal_40,currVal_41,currVal_42);
  });
}
const RenderType_MainFooterComponent_Host:import1.RendererTypeV2 = import1.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_MainFooterComponent_Host_0():import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    import1.ɵeld(0,(null as any),(null as any),1,'main-footer',([] as any[]),(null as any),(null as any),(null as any),View_MainFooterComponent_0,RenderType_MainFooterComponent),
    import1.ɵdid(24576,(null as any),0,import2.MainFooterComponent,[import5.FormBuilder],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const MainFooterComponentNgFactory:import1.ComponentFactory<import2.MainFooterComponent> = import1.ɵccf('main-footer',import2.MainFooterComponent,View_MainFooterComponent_Host_0);