/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './press.component';
const styles_PressComponent:any[] = ([] as any[]);
export const RenderType_PressComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_PressComponent,
  data: {}
}
);
export function View_PressComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Press component'])],(null as any),(null as any));
}
const RenderType_PressComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_PressComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'press',([] as any[]),(null as any),(null as any),(null as any),View_PressComponent_0,RenderType_PressComponent),
    import0.ɵdid(24576,(null as any),0,import1.PressComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const PressComponentNgFactory:import0.ComponentFactory<import1.PressComponent> = import0.ɵccf('press',import1.PressComponent,View_PressComponent_Host_0);