/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './single-project.component';
const styles_SingleProjectComponent:any[] = ([] as any[]);
export const RenderType_SingleProjectComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_SingleProjectComponent,
  data: {}
}
);
export function View_SingleProjectComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Single Project component'])],(null as any),(null as any));
}
const RenderType_SingleProjectComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_SingleProjectComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'single-project',([] as any[]),(null as any),(null as any),(null as any),View_SingleProjectComponent_0,RenderType_SingleProjectComponent),
    import0.ɵdid(24576,(null as any),0,import1.SingleProjectComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const SingleProjectComponentNgFactory:import0.ComponentFactory<import1.SingleProjectComponent> = import0.ɵccf('single-project',import1.SingleProjectComponent,View_SingleProjectComponent_Host_0);