/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './help.component';
const styles_HelpComponent:any[] = ([] as any[]);
export const RenderType_HelpComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_HelpComponent,
  data: {}
}
);
export function View_HelpComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Help component'])],(null as any),(null as any));
}
const RenderType_HelpComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_HelpComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'help',([] as any[]),(null as any),(null as any),(null as any),View_HelpComponent_0,RenderType_HelpComponent),
    import0.ɵdid(24576,(null as any),0,import1.HelpComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const HelpComponentNgFactory:import0.ComponentFactory<import1.HelpComponent> = import0.ɵccf('help',import1.HelpComponent,View_HelpComponent_Host_0);