/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

export const styles:any[] = ['.card[_ngcontent-%COMP%] {\r\n  height: 320px;\r\n}\r\n\r\n.swiper-main[_ngcontent-%COMP%], .swiper-explore[_ngcontent-%COMP%] {\r\n  position: relative;\r\n}\r\n\r\n.swiper-wrapper[_ngcontent-%COMP%] {\r\n  padding: 0;\r\n  list-style: none;\r\n}\r\n\r\n.swiper-main[_ngcontent-%COMP%] {\r\n  background-color: #ccc;\r\n  height: 650px;\r\n  overflow: hidden;\r\n}\r\n\r\n.swiper-explore[_ngcontent-%COMP%] {\r\n  height: 340px;\r\n  overflow: hidden;\r\n}'];