/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from './discover.component.css.shim.ngstyle';
import * as import1 from '@angular/core';
import * as import2 from '@angular/common';
import * as import3 from './discover.component';
import * as import4 from '../shared/services/meta/meta.service';
import * as import5 from '../shared/services/api/api.service';
const styles_DiscoverComponent:any[] = [import0.styles];
export const RenderType_DiscoverComponent:import1.RendererTypeV2 = import1.ɵcrt({
  encapsulation: 0,
  styles: styles_DiscoverComponent,
  data: {}
}
);
function View_DiscoverComponent_1():import1.ɵViewDefinition {
  return import1.ɵvid(0,[
      import1.ɵeld(0,(null as any),(null as any),4,'li',[[
        'class',
        'swiper-slide'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵeld(0,(null as any),(null as any),1,'h3',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),[
      '',
      ''
    ]
    ),
    import1.ɵted((null as any),['\n          '])
  ]
  ,(null as any),(check,view) => {
    var comp:any = view.component;
    const currVal_0:any = view.context.$implicit.name;
    check(view,3,0,currVal_0);
  });
}
function View_DiscoverComponent_2():import1.ɵViewDefinition {
  return import1.ɵvid(0,[
      import1.ɵeld(0,(null as any),(null as any),19,'div',[[
        'class',
        'col-md-3'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n      ']),
      import1.ɵeld(0,(null as any),(null as any),16,'div',[[
        'class',
        'card'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n        ']),
    import1.ɵeld(0,(null as any),(null as any),0,'img',[
      [
        'alt',
        'Project banner image.'
      ]
      ,
      [
        'class',
        'card-img-top'
      ]
      ,
      [
        'height',
        '140'
      ]

    ]
      ,[[
        3,
        'src',
        4
      ]
    ],(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n        ']),
      import1.ɵeld(0,(null as any),(null as any),11,'div',[[
        'class',
        'card-block'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n          ']),
      import1.ɵeld(0,(null as any),(null as any),1,'h4',[[
        'class',
        'card-title'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),[
      '',
      ''
    ]
    ),
    import1.ɵted((null as any),['\n          ']),
      import1.ɵeld(0,(null as any),(null as any),1,'p',[[
        'class',
        'card-text'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),[
      '',
      ''
    ]
    ),
    import1.ɵted((null as any),['\n          ']),
      import1.ɵeld(0,(null as any),(null as any),2,'p',[[
        'class',
        'card-text'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
      import1.ɵeld(0,(null as any),(null as any),1,'small',[[
        'class',
        'text-muted'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),[
      '',
      ''
    ]
    ),
    import1.ɵted((null as any),['\n        ']),
    import1.ɵted((null as any),['\n      ']),
    import1.ɵted((null as any),['\n    '])
  ]
  ,(null as any),(check,view) => {
    var comp:any = view.component;
    const currVal_0:any = view.context.$implicit.bannerUrl;
    check(view,4,0,currVal_0);
    const currVal_1:any = view.context.$implicit.name;
    check(view,9,0,currVal_1);
    const currVal_2:any = view.context.$implicit.desc;
    check(view,12,0,currVal_2);
    const currVal_3:any = view.context.$implicit.created;
    check(view,16,0,currVal_3);
  });
}
function View_DiscoverComponent_3():import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    import1.ɵeld(0,(null as any),(null as any),4,'div',[
      [
        'class',
        'col-md-2'
      ]
      ,
      [
        'style',
        'text-align:center;'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n      ']),
    import1.ɵeld(0,(null as any),(null as any),1,'h3',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),[
      '',
      ''
    ]
    ),
    import1.ɵted((null as any),['\n    '])
  ]
  ,(null as any),(check,view) => {
    var comp:any = view.component;
    const currVal_0:any = view.context.$implicit.name;
    check(view,3,0,currVal_0);
  });
}
export function View_DiscoverComponent_0():import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    import1.ɵeld(0,(null as any),(null as any),28,'section',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n  ']),
      import1.ɵeld(0,(null as any),(null as any),1,'h1',[[
        'class',
        'sr-only'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Explore Stitch']),
    import1.ɵted((null as any),['\n  ']),
    import1.ɵeld(0,(null as any),(null as any),22,'article',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n    ']),
    import1.ɵeld(0,(null as any),(null as any),19,'section',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n      ']),
      import1.ɵeld(0,(null as any),(null as any),1,'h1',[[
        'class',
        'sr-only'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['What\'s new at Stitch?']),
    import1.ɵted((null as any),['\n      ']),
      import1.ɵeld(0,(null as any),(null as any),13,'div',[[
        'class',
        'swiper-container swiper-main'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n        ']),
      import1.ɵeld(0,(null as any),(null as any),4,'ul',[[
        'class',
        'swiper-wrapper'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵand(8388608,(null as any),(null as any),1,(null as any),View_DiscoverComponent_1),
    import1.ɵdid(401408,(null as any),0,import2.NgForOf,[
      import1.ViewContainerRef,
      import1.TemplateRef,
      import1.IterableDiffers
    ]
      ,{ngForOf: [
        0,
        'ngForOf'
      ]
    },(null as any)),
    import1.ɵted((null as any),['\n        ']),
    import1.ɵted((null as any),['\n        ']),
      import1.ɵeld(0,(null as any),(null as any),0,'div',[[
        'class',
        'swiper-pagination swiper-main-pagination'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n        ']),
      import1.ɵeld(0,(null as any),(null as any),0,'div',[[
        'class',
        'swiper-button-prev swiper-main-button-prev'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n        ']),
      import1.ɵeld(0,(null as any),(null as any),0,'div',[[
        'class',
        'swiper-button-next swiper-main-button-next'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n      ']),
    import1.ɵted((null as any),['\n    ']),
    import1.ɵted((null as any),['\n  ']),
    import1.ɵted((null as any),['\n']),
    import1.ɵted((null as any),['\n']),
      import1.ɵeld(0,(null as any),(null as any),162,'section',[[
        'class',
        'container'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n  ']),
    import1.ɵeld(0,(null as any),(null as any),1,'h5',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Explore']),
    import1.ɵted((null as any),['\n  ']),
      import1.ɵeld(0,(null as any),(null as any),156,'main',[[
        'class',
        'row'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n    ']),
      import1.ɵeld(0,(null as any),(null as any),148,'div',[[
        'class',
        'col-md-9 swiper-container swiper-explore'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n      ']),
      import1.ɵeld(0,(null as any),(null as any),145,'ul',[[
        'class',
        'swiper-wrapper'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n        ']),
      import1.ɵeld(0,(null as any),(null as any),46,'li',[[
        'class',
        'swiper-slide'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n          ']),
      import1.ɵeld(0,(null as any),(null as any),43,'div',[[
        'class',
        'row'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n            ']),
      import1.ɵeld(0,(null as any),(null as any),19,'div',[[
        'class',
        'col-md-8'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n              ']),
      import1.ɵeld(0,(null as any),(null as any),16,'div',[[
        'class',
        'card'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n                ']),
    import1.ɵeld(0,(null as any),(null as any),0,'img',[
      [
        'alt',
        'Card image'
      ]
      ,
      [
        'class',
        'card-img'
      ]
      ,
      [
        'src',
        'https://placehold.it/555x320'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n                ']),
      import1.ɵeld(0,(null as any),(null as any),11,'div',[[
        'class',
        'card-img-overlay'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n                  ']),
      import1.ɵeld(0,(null as any),(null as any),1,'h4',[[
        'class',
        'card-title'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Card title']),
    import1.ɵted((null as any),['\n                  ']),
      import1.ɵeld(0,(null as any),(null as any),1,'p',[[
        'class',
        'card-text'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.']),
    import1.ɵted((null as any),['\n                  ']),
      import1.ɵeld(0,(null as any),(null as any),2,'p',[[
        'class',
        'card-text'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
      import1.ɵeld(0,(null as any),(null as any),1,'small',[[
        'class',
        'text-muted'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Last updated 3 mins ago']),
    import1.ɵted((null as any),['\n                ']),
    import1.ɵted((null as any),['\n              ']),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵted((null as any),['\n            ']),
      import1.ɵeld(0,(null as any),(null as any),19,'div',[[
        'class',
        'col-md-4'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n              ']),
      import1.ɵeld(0,(null as any),(null as any),16,'div',[[
        'class',
        'card'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n                ']),
    import1.ɵeld(0,(null as any),(null as any),0,'img',[
      [
        'alt',
        'Card image cap'
      ]
      ,
      [
        'class',
        'card-img-top'
      ]
      ,
      [
        'src',
        'https://placehold.it/262x140'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n                ']),
      import1.ɵeld(0,(null as any),(null as any),11,'div',[[
        'class',
        'card-block'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n                  ']),
      import1.ɵeld(0,(null as any),(null as any),1,'h4',[[
        'class',
        'card-title'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Card title']),
    import1.ɵted((null as any),['\n                  ']),
      import1.ɵeld(0,(null as any),(null as any),1,'p',[[
        'class',
        'card-text'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['This card has supporting text below as a natural lead-in to additional content.']),
    import1.ɵted((null as any),['\n                  ']),
      import1.ɵeld(0,(null as any),(null as any),2,'p',[[
        'class',
        'card-text'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
      import1.ɵeld(0,(null as any),(null as any),1,'small',[[
        'class',
        'text-muted'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Last updated 3 mins ago']),
    import1.ɵted((null as any),['\n                ']),
    import1.ɵted((null as any),['\n              ']),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵted((null as any),['\n        ']),
    import1.ɵted((null as any),['\n        ']),
      import1.ɵeld(0,(null as any),(null as any),46,'li',[[
        'class',
        'swiper-slide'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n          ']),
      import1.ɵeld(0,(null as any),(null as any),43,'div',[[
        'class',
        'row'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n            ']),
      import1.ɵeld(0,(null as any),(null as any),19,'div',[[
        'class',
        'col-md-8'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n              ']),
      import1.ɵeld(0,(null as any),(null as any),16,'div',[[
        'class',
        'card'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n                ']),
    import1.ɵeld(0,(null as any),(null as any),0,'img',[
      [
        'alt',
        'Card image'
      ]
      ,
      [
        'class',
        'card-img'
      ]
      ,
      [
        'src',
        'https://placehold.it/555x320'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n                ']),
      import1.ɵeld(0,(null as any),(null as any),11,'div',[[
        'class',
        'card-img-overlay'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n                  ']),
      import1.ɵeld(0,(null as any),(null as any),1,'h4',[[
        'class',
        'card-title'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Card title']),
    import1.ɵted((null as any),['\n                  ']),
      import1.ɵeld(0,(null as any),(null as any),1,'p',[[
        'class',
        'card-text'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.']),
    import1.ɵted((null as any),['\n                  ']),
      import1.ɵeld(0,(null as any),(null as any),2,'p',[[
        'class',
        'card-text'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
      import1.ɵeld(0,(null as any),(null as any),1,'small',[[
        'class',
        'text-muted'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Last updated 3 mins ago']),
    import1.ɵted((null as any),['\n                ']),
    import1.ɵted((null as any),['\n              ']),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵted((null as any),['\n            ']),
      import1.ɵeld(0,(null as any),(null as any),19,'div',[[
        'class',
        'col-md-4'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n              ']),
      import1.ɵeld(0,(null as any),(null as any),16,'div',[[
        'class',
        'card'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n                ']),
    import1.ɵeld(0,(null as any),(null as any),0,'img',[
      [
        'alt',
        'Card image cap'
      ]
      ,
      [
        'class',
        'card-img-top'
      ]
      ,
      [
        'src',
        'https://placehold.it/262x140'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n                ']),
      import1.ɵeld(0,(null as any),(null as any),11,'div',[[
        'class',
        'card-block'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n                  ']),
      import1.ɵeld(0,(null as any),(null as any),1,'h4',[[
        'class',
        'card-title'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Card title']),
    import1.ɵted((null as any),['\n                  ']),
      import1.ɵeld(0,(null as any),(null as any),1,'p',[[
        'class',
        'card-text'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['This card has supporting text below as a natural lead-in to additional content.']),
    import1.ɵted((null as any),['\n                  ']),
      import1.ɵeld(0,(null as any),(null as any),2,'p',[[
        'class',
        'card-text'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
      import1.ɵeld(0,(null as any),(null as any),1,'small',[[
        'class',
        'text-muted'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Last updated 3 mins ago']),
    import1.ɵted((null as any),['\n                ']),
    import1.ɵted((null as any),['\n              ']),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵted((null as any),['\n        ']),
    import1.ɵted((null as any),['\n        ']),
      import1.ɵeld(0,(null as any),(null as any),46,'li',[[
        'class',
        'swiper-slide'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n          ']),
      import1.ɵeld(0,(null as any),(null as any),43,'div',[[
        'class',
        'row'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n            ']),
      import1.ɵeld(0,(null as any),(null as any),19,'div',[[
        'class',
        'col-md-8'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n              ']),
      import1.ɵeld(0,(null as any),(null as any),16,'div',[[
        'class',
        'card'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n                ']),
    import1.ɵeld(0,(null as any),(null as any),0,'img',[
      [
        'alt',
        'Card image'
      ]
      ,
      [
        'class',
        'card-img'
      ]
      ,
      [
        'src',
        'https://placehold.it/555x320'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n                ']),
      import1.ɵeld(0,(null as any),(null as any),11,'div',[[
        'class',
        'card-img-overlay'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n                  ']),
      import1.ɵeld(0,(null as any),(null as any),1,'h4',[[
        'class',
        'card-title'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Card title']),
    import1.ɵted((null as any),['\n                  ']),
      import1.ɵeld(0,(null as any),(null as any),1,'p',[[
        'class',
        'card-text'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.']),
    import1.ɵted((null as any),['\n                  ']),
      import1.ɵeld(0,(null as any),(null as any),2,'p',[[
        'class',
        'card-text'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
      import1.ɵeld(0,(null as any),(null as any),1,'small',[[
        'class',
        'text-muted'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Last updated 3 mins ago']),
    import1.ɵted((null as any),['\n                ']),
    import1.ɵted((null as any),['\n              ']),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵted((null as any),['\n            ']),
      import1.ɵeld(0,(null as any),(null as any),19,'div',[[
        'class',
        'col-md-4'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n              ']),
      import1.ɵeld(0,(null as any),(null as any),16,'div',[[
        'class',
        'card'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n                ']),
    import1.ɵeld(0,(null as any),(null as any),0,'img',[
      [
        'alt',
        'Card image cap'
      ]
      ,
      [
        'class',
        'card-img-top'
      ]
      ,
      [
        'src',
        'https://placehold.it/262x140'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n                ']),
      import1.ɵeld(0,(null as any),(null as any),11,'div',[[
        'class',
        'card-block'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n                  ']),
      import1.ɵeld(0,(null as any),(null as any),1,'h4',[[
        'class',
        'card-title'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Card title']),
    import1.ɵted((null as any),['\n                  ']),
      import1.ɵeld(0,(null as any),(null as any),1,'p',[[
        'class',
        'card-text'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['This card has supporting text below as a natural lead-in to additional content.']),
    import1.ɵted((null as any),['\n                  ']),
      import1.ɵeld(0,(null as any),(null as any),2,'p',[[
        'class',
        'card-text'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
      import1.ɵeld(0,(null as any),(null as any),1,'small',[[
        'class',
        'text-muted'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Last updated 3 mins ago']),
    import1.ɵted((null as any),['\n                ']),
    import1.ɵted((null as any),['\n              ']),
    import1.ɵted((null as any),['\n            ']),
    import1.ɵted((null as any),['\n          ']),
    import1.ɵted((null as any),['\n        ']),
    import1.ɵted((null as any),['\n      ']),
    import1.ɵted((null as any),['\n    ']),
    import1.ɵted((null as any),['\n    ']),
      import1.ɵeld(0,(null as any),(null as any),3,'div',[[
        'class',
        'col-md-3'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n      ']),
      import1.ɵeld(0,(null as any),(null as any),0,'div',[[
        'class',
        'swiper-pagination swiper-explore-pagination'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n    ']),
    import1.ɵted((null as any),['\n  ']),
    import1.ɵted((null as any),['\n']),
    import1.ɵted((null as any),['\n']),
      import1.ɵeld(0,(null as any),(null as any),10,'section',[[
        'class',
        'container'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n  ']),
    import1.ɵeld(0,(null as any),(null as any),1,'h5',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Recommended']),
    import1.ɵted((null as any),['\n  ']),
      import1.ɵeld(0,(null as any),(null as any),4,'main',[[
        'class',
        'row'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n    ']),
    import1.ɵand(8388608,(null as any),(null as any),1,(null as any),View_DiscoverComponent_2),
    import1.ɵdid(401408,(null as any),0,import2.NgForOf,[
      import1.ViewContainerRef,
      import1.TemplateRef,
      import1.IterableDiffers
    ]
      ,{ngForOf: [
        0,
        'ngForOf'
      ]
    },(null as any)),
    import1.ɵted((null as any),['\n  ']),
    import1.ɵted((null as any),['\n']),
    import1.ɵted((null as any),['\n']),
      import1.ɵeld(0,(null as any),(null as any),10,'section',[[
        'class',
        'container'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n  ']),
    import1.ɵeld(0,(null as any),(null as any),1,'h5',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['Recommended']),
    import1.ɵted((null as any),['\n  ']),
      import1.ɵeld(0,(null as any),(null as any),4,'main',[[
        'class',
        'row'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any)),
    import1.ɵted((null as any),['\n    ']),
    import1.ɵand(8388608,(null as any),(null as any),1,(null as any),View_DiscoverComponent_3),
    import1.ɵdid(401408,(null as any),0,import2.NgForOf,[
      import1.ViewContainerRef,
      import1.TemplateRef,
      import1.IterableDiffers
    ]
      ,{ngForOf: [
        0,
        'ngForOf'
      ]
    },(null as any)),
    import1.ɵted((null as any),['\n  ']),
    import1.ɵted((null as any),['\n'])
  ]
  ,(check,view) => {
    var comp:import3.DiscoverComponent = view.component;
    const currVal_0:any = comp.slides;
    check(view,17,0,currVal_0);
    const currVal_1:any = comp.recommended;
    check(view,202,0,currVal_1);
    const currVal_2:any = comp.users;
    check(view,214,0,currVal_2);
  },(null as any));
}
const RenderType_DiscoverComponent_Host:import1.RendererTypeV2 = import1.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_DiscoverComponent_Host_0():import1.ɵViewDefinition {
  return import1.ɵvid(0,[
    import1.ɵeld(0,(null as any),(null as any),1,'discover',([] as any[]),(null as any),(null as any),(null as any),View_DiscoverComponent_0,RenderType_DiscoverComponent),
    import1.ɵdid(57344,(null as any),0,import3.DiscoverComponent,[
      'isBrowser',
      import4.MetaService,
      import5.ApiService
    ]
    ,(null as any),(null as any))
  ]
  ,(check,view) => {
    check(view,1,0);
  },(null as any));
}
export const DiscoverComponentNgFactory:import1.ComponentFactory<import3.DiscoverComponent> = import1.ɵccf('discover',import3.DiscoverComponent,View_DiscoverComponent_Host_0);