/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './404-routing.module';
import * as import2 from '@angular/router';
import * as import3 from './404.component.ngfactory';
import * as import4 from './404.component';
class NotFoundRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.NotFoundRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _NotFoundRoutingModule_1:import1.NotFoundRoutingModule;
  __ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,[import3.NotFoundComponentNgFactory],([] as any[]));
  }
  get _ROUTES_2():any[] {
      if ((this.__ROUTES_2 == null)) { (this.__ROUTES_2 = [[
        {
          path: '404',
          component: import4.NotFoundComponent
        }
        ,
        {
          path: '**',
          redirectTo: '/404'
        }

      ]
    ]); }
    return this.__ROUTES_2;
  }
  createInternal():import1.NotFoundRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)));
    this._NotFoundRoutingModule_1 = new import1.NotFoundRoutingModule();
    return this._NotFoundRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.NotFoundRoutingModule)) { return this._NotFoundRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const NotFoundRoutingModuleNgFactory:import0.NgModuleFactory<import1.NotFoundRoutingModule> = new import0.NgModuleFactory<any>(NotFoundRoutingModuleInjector,import1.NotFoundRoutingModule);