/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './404.component';
const styles_NotFoundComponent:any[] = ([] as any[]);
export const RenderType_NotFoundComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_NotFoundComponent,
  data: {}
}
);
export function View_NotFoundComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['404 component'])],(null as any),(null as any));
}
const RenderType_NotFoundComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_NotFoundComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'not-found',([] as any[]),(null as any),(null as any),(null as any),View_NotFoundComponent_0,RenderType_NotFoundComponent),
    import0.ɵdid(24576,(null as any),0,import1.NotFoundComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const NotFoundComponentNgFactory:import0.ComponentFactory<import1.NotFoundComponent> = import0.ɵccf('not-found',import1.NotFoundComponent,View_NotFoundComponent_Host_0);