/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './highlights.component';
const styles_HighlightsComponent:any[] = ([] as any[]);
export const RenderType_HighlightsComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_HighlightsComponent,
  data: {}
}
);
export function View_HighlightsComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Highlights component'])],(null as any),(null as any));
}
const RenderType_HighlightsComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_HighlightsComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'highlights',([] as any[]),(null as any),(null as any),(null as any),View_HighlightsComponent_0,RenderType_HighlightsComponent),
    import0.ɵdid(24576,(null as any),0,import1.HighlightsComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const HighlightsComponentNgFactory:import0.ComponentFactory<import1.HighlightsComponent> = import0.ɵccf('highlights',import1.HighlightsComponent,View_HighlightsComponent_Host_0);