/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './highlights-routing.module';
import * as import2 from '@angular/router';
import * as import3 from './highlights.component.ngfactory';
import * as import4 from './highlights.component';
class HighlightsRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.HighlightsRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _HighlightsRoutingModule_1:import1.HighlightsRoutingModule;
  __ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,[import3.HighlightsComponentNgFactory],([] as any[]));
  }
  get _ROUTES_2():any[] {
        if ((this.__ROUTES_2 == null)) { (this.__ROUTES_2 = [[{
          path: 'highlights',
          component: import4.HighlightsComponent
        }
    ]]); }
    return this.__ROUTES_2;
  }
  createInternal():import1.HighlightsRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)));
    this._HighlightsRoutingModule_1 = new import1.HighlightsRoutingModule();
    return this._HighlightsRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.HighlightsRoutingModule)) { return this._HighlightsRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const HighlightsRoutingModuleNgFactory:import0.NgModuleFactory<import1.HighlightsRoutingModule> = new import0.NgModuleFactory<any>(HighlightsRoutingModuleInjector,import1.HighlightsRoutingModule);