/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './team-dashboard.component';
const styles_TeamDashboardComponent:any[] = ([] as any[]);
export const RenderType_TeamDashboardComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_TeamDashboardComponent,
  data: {}
}
);
export function View_TeamDashboardComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Team Dashboard component'])],(null as any),(null as any));
}
const RenderType_TeamDashboardComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_TeamDashboardComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'team-dashboard',([] as any[]),(null as any),(null as any),(null as any),View_TeamDashboardComponent_0,RenderType_TeamDashboardComponent),
    import0.ɵdid(24576,(null as any),0,import1.TeamDashboardComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const TeamDashboardComponentNgFactory:import0.ComponentFactory<import1.TeamDashboardComponent> = import0.ɵccf('team-dashboard',import1.TeamDashboardComponent,View_TeamDashboardComponent_Host_0);