/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './project-routing.module';
import * as import2 from '@angular/router';
import * as import3 from './single/single-project.component.ngfactory';
import * as import4 from './single/dashboard/project-dashboard.component.ngfactory';
import * as import5 from './single/single-project.component';
import * as import6 from './single/dashboard/project-dashboard.component';
class ProjectRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.ProjectRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _ProjectRoutingModule_1:import1.ProjectRoutingModule;
  __ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,[
      import3.SingleProjectComponentNgFactory,
      import4.ProjectDashboardComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _ROUTES_2():any[] {
      if ((this.__ROUTES_2 == null)) { (this.__ROUTES_2 = [[
        {
          path: 'project/:slug',
          component: import5.SingleProjectComponent
        }
        ,
        {
          path: 'project/:slug/dashboard',
          component: import6.ProjectDashboardComponent
        }
        ,
        {
          path: 'project/:slug/dashboard/applications',
          component: import6.ProjectDashboardComponent
        }
        ,
        {
          path: 'project/:slug/dashboard/application/:application_id',
          component: import6.ProjectDashboardComponent
        }

      ]
    ]); }
    return this.__ROUTES_2;
  }
  createInternal():import1.ProjectRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)));
    this._ProjectRoutingModule_1 = new import1.ProjectRoutingModule();
    return this._ProjectRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.ProjectRoutingModule)) { return this._ProjectRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ProjectRoutingModuleNgFactory:import0.NgModuleFactory<import1.ProjectRoutingModule> = new import0.NgModuleFactory<any>(ProjectRoutingModuleInjector,import1.ProjectRoutingModule);