/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './single-team.component';
const styles_SingleTeamComponent:any[] = ([] as any[]);
export const RenderType_SingleTeamComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_SingleTeamComponent,
  data: {}
}
);
export function View_SingleTeamComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Single Team component'])],(null as any),(null as any));
}
const RenderType_SingleTeamComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_SingleTeamComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'single-team',([] as any[]),(null as any),(null as any),(null as any),View_SingleTeamComponent_0,RenderType_SingleTeamComponent),
    import0.ɵdid(24576,(null as any),0,import1.SingleTeamComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const SingleTeamComponentNgFactory:import0.ComponentFactory<import1.SingleTeamComponent> = import0.ɵccf('single-team',import1.SingleTeamComponent,View_SingleTeamComponent_Host_0);