/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './components.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/router';
import * as import4 from '@angular/forms';
class SharedComponentsModuleInjector extends import0.ɵNgModuleInjector<import1.SharedComponentsModule> {
  _CommonModule_0:import2.CommonModule;
  _RouterModule_1:import3.RouterModule;
  _ɵba_2:import4.ɵba;
  _ReactiveFormsModule_3:import4.ReactiveFormsModule;
  _SharedComponentsModule_4:import1.SharedComponentsModule;
  __NgLocalization_5:import2.NgLocaleLocalization;
  __FormBuilder_6:import4.FormBuilder;
  __ɵi_7:import4.ɵi;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_5():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_5 == null)) { (this.__NgLocalization_5 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_5;
  }
  get _FormBuilder_6():import4.FormBuilder {
    if ((this.__FormBuilder_6 == null)) { (this.__FormBuilder_6 = new import4.FormBuilder()); }
    return this.__FormBuilder_6;
  }
  get _ɵi_7():import4.ɵi {
    if ((this.__ɵi_7 == null)) { (this.__ɵi_7 = new import4.ɵi()); }
    return this.__ɵi_7;
  }
  createInternal():import1.SharedComponentsModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._RouterModule_1 = new import3.RouterModule(this.parent.get(import3.ɵa,(null as any)));
    this._ɵba_2 = new import4.ɵba();
    this._ReactiveFormsModule_3 = new import4.ReactiveFormsModule();
    this._SharedComponentsModule_4 = new import1.SharedComponentsModule();
    return this._SharedComponentsModule_4;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.RouterModule)) { return this._RouterModule_1; }
    if ((token === import4.ɵba)) { return this._ɵba_2; }
    if ((token === import4.ReactiveFormsModule)) { return this._ReactiveFormsModule_3; }
    if ((token === import1.SharedComponentsModule)) { return this._SharedComponentsModule_4; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_5; }
    if ((token === import4.FormBuilder)) { return this._FormBuilder_6; }
    if ((token === import4.ɵi)) { return this._ɵi_7; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const SharedComponentsModuleNgFactory:import0.NgModuleFactory<import1.SharedComponentsModule> = new import0.NgModuleFactory<any>(SharedComponentsModuleInjector,import1.SharedComponentsModule);