/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './terms-routing.module';
import * as import2 from '@angular/router';
import * as import3 from './terms.component.ngfactory';
import * as import4 from './use/use.component.ngfactory';
import * as import5 from './privacy/privacy.component.ngfactory';
import * as import6 from './cookies/cookies.component.ngfactory';
import * as import7 from './terms.component';
import * as import8 from './use/use.component';
import * as import9 from './privacy/privacy.component';
import * as import10 from './cookies/cookies.component';
class TermsRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.TermsRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _TermsRoutingModule_1:import1.TermsRoutingModule;
  __ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,[
      import3.TermsComponentNgFactory,
      import4.UseComponentNgFactory,
      import5.PrivacyComponentNgFactory,
      import6.CookiesComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _ROUTES_2():any[] {
      if ((this.__ROUTES_2 == null)) { (this.__ROUTES_2 = [[
        {
          path: 'terms',
          component: import7.TermsComponent
        }
        ,
        {
          path: 'terms/use',
          component: import8.UseComponent
        }
        ,
        {
          path: 'terms/privacy',
          component: import9.PrivacyComponent
        }
        ,
        {
          path: 'terms/cookies',
          component: import10.CookiesComponent
        }

      ]
    ]); }
    return this.__ROUTES_2;
  }
  createInternal():import1.TermsRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)));
    this._TermsRoutingModule_1 = new import1.TermsRoutingModule();
    return this._TermsRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.TermsRoutingModule)) { return this._TermsRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const TermsRoutingModuleNgFactory:import0.NgModuleFactory<import1.TermsRoutingModule> = new import0.NgModuleFactory<any>(TermsRoutingModuleInjector,import1.TermsRoutingModule);