/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './terms.component';
const styles_TermsComponent:any[] = ([] as any[]);
export const RenderType_TermsComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_TermsComponent,
  data: {}
}
);
export function View_TermsComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Terms component'])],(null as any),(null as any));
}
const RenderType_TermsComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_TermsComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'terms',([] as any[]),(null as any),(null as any),(null as any),View_TermsComponent_0,RenderType_TermsComponent),
    import0.ɵdid(24576,(null as any),0,import1.TermsComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const TermsComponentNgFactory:import0.ComponentFactory<import1.TermsComponent> = import0.ɵccf('terms',import1.TermsComponent,View_TermsComponent_Host_0);