/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './auth-routing.module';
import * as import2 from '@angular/router';
import * as import3 from '../components/login/login.component.ngfactory';
import * as import4 from '../components/signup/signup.component.ngfactory';
import * as import5 from '../components/login/login.component';
import * as import6 from '../components/signup/signup.component';
class AuthRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.AuthRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _AuthRoutingModule_1:import1.AuthRoutingModule;
  __ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,[
      import3.LoginComponentNgFactory,
      import4.SignupComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _ROUTES_2():any[] {
      if ((this.__ROUTES_2 == null)) { (this.__ROUTES_2 = [[
        {
          path: 'login',
          component: import5.LoginComponent
        }
        ,
        {
          path: 'signup',
          component: import6.SignupComponent
        }

      ]
    ]); }
    return this.__ROUTES_2;
  }
  createInternal():import1.AuthRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)));
    this._AuthRoutingModule_1 = new import1.AuthRoutingModule();
    return this._AuthRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.AuthRoutingModule)) { return this._AuthRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const AuthRoutingModuleNgFactory:import0.NgModuleFactory<import1.AuthRoutingModule> = new import0.NgModuleFactory<any>(AuthRoutingModuleInjector,import1.AuthRoutingModule);