/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './trending-routing.module';
import * as import2 from '@angular/router';
import * as import3 from './trending.component.ngfactory';
import * as import4 from './users/trending-users.component.ngfactory';
import * as import5 from './teams/trending-teams.component.ngfactory';
import * as import6 from './trending.component';
import * as import7 from './users/trending-users.component';
import * as import8 from './teams/trending-teams.component';
class TrendingRoutingModuleInjector extends import0.ɵNgModuleInjector<import1.TrendingRoutingModule> {
  _RouterModule_0:import2.RouterModule;
  _TrendingRoutingModule_1:import1.TrendingRoutingModule;
  __ROUTES_2:any[];
  constructor(parent:import0.Injector) {
    super(parent,[
      import3.TrendingComponentNgFactory,
      import4.TrendingUsersComponentNgFactory,
      import5.TrendingTeamsComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _ROUTES_2():any[] {
      if ((this.__ROUTES_2 == null)) { (this.__ROUTES_2 = [[
        {
          path: 'trending',
          component: import6.TrendingComponent
        }
        ,
        {
          path: 'trending/users',
          component: import7.TrendingUsersComponent
        }
        ,
        {
          path: 'trending/teams',
          component: import8.TrendingTeamsComponent
        }

      ]
    ]); }
    return this.__ROUTES_2;
  }
  createInternal():import1.TrendingRoutingModule {
    this._RouterModule_0 = new import2.RouterModule(this.parent.get(import2.ɵa,(null as any)));
    this._TrendingRoutingModule_1 = new import1.TrendingRoutingModule();
    return this._TrendingRoutingModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.RouterModule)) { return this._RouterModule_0; }
    if ((token === import1.TrendingRoutingModule)) { return this._TrendingRoutingModule_1; }
    if ((token === import2.ROUTES)) { return this._ROUTES_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const TrendingRoutingModuleNgFactory:import0.NgModuleFactory<import1.TrendingRoutingModule> = new import0.NgModuleFactory<any>(TrendingRoutingModuleInjector,import1.TrendingRoutingModule);