/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './trending.component';
const styles_TrendingComponent:any[] = ([] as any[]);
export const RenderType_TrendingComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_TrendingComponent,
  data: {}
}
);
export function View_TrendingComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Trending component'])],(null as any),(null as any));
}
const RenderType_TrendingComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_TrendingComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'trending',([] as any[]),(null as any),(null as any),(null as any),View_TrendingComponent_0,RenderType_TrendingComponent),
    import0.ɵdid(24576,(null as any),0,import1.TrendingComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const TrendingComponentNgFactory:import0.ComponentFactory<import1.TrendingComponent> = import0.ɵccf('trending',import1.TrendingComponent,View_TrendingComponent_Host_0);