/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core';
import * as import1 from './project-applications.component';
const styles_ProjectApplicationsComponent:any[] = ([] as any[]);
export const RenderType_ProjectApplicationsComponent:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_ProjectApplicationsComponent,
  data: {}
}
);
export function View_ProjectApplicationsComponent_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[import0.ɵted((null as any),['Project Applications component'])],(null as any),(null as any));
}
const RenderType_ProjectApplicationsComponent_Host:import0.RendererTypeV2 = import0.ɵcrt({
  encapsulation: 2,
  styles: ([] as any[]),
  data: {}
}
);
function View_ProjectApplicationsComponent_Host_0():import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    import0.ɵeld(0,(null as any),(null as any),1,'project-applications',([] as any[]),(null as any),(null as any),(null as any),View_ProjectApplicationsComponent_0,RenderType_ProjectApplicationsComponent),
    import0.ɵdid(24576,(null as any),0,import1.ProjectApplicationsComponent,['req'],(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const ProjectApplicationsComponentNgFactory:import0.ComponentFactory<import1.ProjectApplicationsComponent> = import0.ɵccf('project-applications',import1.ProjectApplicationsComponent,View_ProjectApplicationsComponent_Host_0);